### ISSUE TITLE
Parameter `T_subseq_isconstant` in `core.process_isconstant` should be set to `None` as default

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#1013]
The docstring says:
```
T_subseq_isconstant : numpy.ndarray, function, or list, default None 
```

However, the parameter is not set to None.

https://github.com/TDAmeritrade/stumpy/blob/3077d0ddfb315464321dc86f8ec3bf2cab9ce3b1/stumpy/core.py#L4224-L4244

**Comment by seanlaw** [comment]
@NimaSarajpoor Perhaps we should update the docstring and remove `, default None`?

**Comment by NimaSarajpoor** [comment]
This function returns `T_subseq_isconstant ` and thus, it may make sense to allow users to only pass `T` and `m` (and nothing else) if they want to capture constant subsequences. 

So, I think we just set it to `None` as default. What do you think?

**Comment by seanlaw** [comment]
@NimaSarajpoor That sounds fine. Change it and run the tests again to see if anything breaks
