### ISSUE TITLE
_motifs max_matches=None bug

### ISSUE THREAD

**Issue by ejorgensen-wl** [TDAmeritrade/stumpy#1014]
When finding motifs, the function encounters a bug when `max_matches` is set to `None` to not restrict the number of matches. If the `max_matches` argument is set to `None` for `stumpy.motifs`, it assigns `max_matches = np.inf` before passing to `_motifs` which then tries to slice the `query_matches` with `np.inf` as seen in the error below.

Example:
```
>>> import numpy as np
>>> import stumpy
>>> arr = np.array([0.,1,2,2,0,1,2,2,0,0,0,0])
>>> mp = stumpy.stump(arr, m=3)
>>> stumpy.motifs(arr, mp[:,0], max_matches=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user0/code/venv/lib/python3.10/site-packages/stumpy/core.py", line 138, in inner_wrapper
    return norm(*args, **kwargs)
  File "/Users/user0/code/venv/lib/python3.10/site-packages/stumpy/motifs.py", line 361, in motifs
    motif_distances, motif_indices = _motifs(
  File "/Users/user0/code/venv/lib/python3.10/site-packages/stumpy/motifs.py", line 134, in _motifs
    motif_distances.append(query_matches[:max_matches, 0])
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by ejorgensen-wl** [comment]
I based the issue off of my understanding of [the docs for `motifs`](https://stumpy.readthedocs.io/en/latest/api.html#motifs) which indicates `None` should be used to not restrict the number of matches. The functionality to allow that is already implemented [here](https://github.com/TDAmeritrade/stumpy/blob/3077d0ddfb315464321dc86f8ec3bf2cab9ce3b1/stumpy/motifs.py#L336), but wasn't fixed in the corresponding `_motifs` function.

I'm not well versed in public API conventions, but it seems that the main options are to:
- Modify code and documentation to no longer handle `None` and enforce an `int` type for `max_matches`
OR
- Bug fix the functionality that is indicated by the docs that `max_matches=None` should allow any number of matches, as I attempted in [this PR](https://github.com/TDAmeritrade/stumpy/pull/1015).

**Comment by seanlaw** [comment]
That's fair! I think the bug fix approach is the way to go and thank you for the PR. Please allow me a little bit of time to review it
