### ISSUE TITLE
Tutotorials raises KeyboardInterrupt

### ISSUE THREAD

**Issue by th0ger** [TDAmeritrade/stumpy#1020]
Several places in the tutorials (latest and stable), output cells are failing. 

They all seem to be caused by "KeyboardInterrupt", see:

https://stumpy.readthedocs.io/en/latest/search.html?q=KeyboardInterrupt#

**Comment by seanlaw** [comment]
@th0ger Thank you for reporting this! I will take a look and see if I can resolve this. It appears to be a problem with `numpy`

**Comment by seanlaw** [comment]
I can confirm that the `KeyboardInterrupt` is appearing on the following two pages:

* https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html
* https://stumpy.readthedocs.io/en/latest/Tutorial_Pattern_Matching.html

**Comment by seanlaw** [comment]
> I can confirm that the `KeyboardInterrupt` is appearing on the following two pages:
> 
> * https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html
> * https://stumpy.readthedocs.io/en/latest/Tutorial_Pattern_Matching.html

This is consistent with the errors that I am seeing in the readthedocs logs:

> /home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/docs/Tutorial_Matrix_Profiles_For_Streaming_Data.ipynb: WARNING: Executing notebook failed: CellTimeoutError [mystnb.exec]
/home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/docs/Tutorial_Matrix_Profiles_For_Streaming_Data.ipynb: WARNING: Notebook exception traceback saved in: /home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/_readthedocs/html/reports/Tutorial_Matrix_Profiles_For_Streaming_Data.err.log [mystnb.exec]
/home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/docs/Tutorial_Pattern_Matching.ipynb: WARNING: Executing notebook failed: CellTimeoutError [mystnb.exec]
/home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/docs/Tutorial_Pattern_Matching.ipynb: WARNING: Notebook exception traceback saved in: /home/docs/checkouts/readthedocs.org/user_builds/stumpy/checkouts/latest/_readthedocs/html/reports/Tutorial_Pattern_Matching.err.log [mystnb.exec]

Specifically, there are some notebooks cells that are taking a bit too long to execute and we are seeing a `CellTimeoutError`. I think I've fixed the `Tutorial_Pattern_Matching.html` one by shortening the example to `100_000` data points and [this enhancement](https://github.com/TDAmeritrade/stumpy/pull/1001#issuecomment-2263946013) by @NimaSarajpoor might actually clear things up for `Tutorial_Matrix_Profiles_For_Streaming_Data.html` once it is merged.

**Comment by th0ger** [comment]
Suggest adding CI tests, if possible, to ensure notebooks completed fully.

**Comment by seanlaw** [comment]
> Suggest adding CI tests, if possible, to ensure notebooks completed fully.

@th0ger Do you have any suggestions on this or can point to some relevant resources for me to learn? Locally, the everything builds without issues and the timeout isn't actually causing readthedocs to fail and so the docs ultimately end up getting built. 

> I can't seem to figure out how to increase the timeout.

It appears that we can try to increase the timeout by doing

```
# Notebook cell execution timeout; defaults to 30.
nb_execution_timeout = None
```

**Comment by th0ger** [comment]
@seanlaw Sorry, I'm not that experienced with readthedocs.

**Comment by seanlaw** [comment]
@th0ger The issue appears to be resolved now. You may need to clear your browser cache to see the updates. Feel free to re-open if the problem persists and thanks again for bring it to our attention!
