### ISSUE TITLE
Add First-class Support for Pandas Series/DataFrames

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#11]
In the tutorial, it's a little awkward that one has to extract the values from the pandas dataframe. First-class support for pandas Series/DataFrames (casting to a NumPy array, or potentially even returning a DataFrame with the same keys, if a DataFrame is passed in) would be a really nice feature.

**Comment by seanlaw** [comment]
@bdice Have you seen examples of how one might support this? I see this in sklearn but I'm not sure it's worth the hassle since `df['some_column'].values` is pretty straightforward.

**Comment by bdice** [comment]
I experimented with this for a bit. Two suggestions below.

A one-way conversion would be possible, so that a pandas `Series` could be auto-converted (and similarly for a `DataFrame` with multiple `Series`). An example of how you could do this:

```python
# in a common/util file

try:
    import pandas
    PANDAS = True
except ImportError:  # Fallback if the user doesn't have pandas installed
    PANDAS = False

def preprocess(array):
    if PANDAS and isinstance(array, pandas.Series):
        return array.values
    else:
        return array
```

Then call `preprocess(array)` or similar when accepting user input.

Another thing to consider would be NumPy structured arrays. The stumpy results are currently of dtype `object` because they're a mixture of floats and ints. This would let the results' columns be self-documenting. As a bonus, performance should improve if data is stored in a structured array with defined and aligned types.
https://docs.scipy.org/doc/numpy/user/basics.rec.html

This uses the pandas `DataFrame` from tutorial 1 as an example. Note: The `object` datatype doesn't play well with `fromrecords`, so I had to manually convert the results to a list of tuples first.

```python
>>> struct_arr = np.rec.fromrecords([tuple(r) for r in stump_results],
                                    formats='f8, i4, i4, i4', aligned=True,
                                    names=['mp', 'inx', 'left', 'right'])
>>> struct_arr
rec.array([(0.46253642, 1680,   -1, 1680), (0.46541273, 1681,   -1, 1681),
           (0.46710424, 1682,   -1, 1682), ...,
           (0.80379041, 3214, 3214,   -1), (0.81525842, 3215, 3215,   -1),
           (0.82933601, 2208, 2208,   -1)],
          dtype=[('mp', '<f8'), ('inx', '<i4'), ('left', '<i4'), ('right', '<i4')])
```

**Comment by seanlaw** [comment]
Thanks for looking into this. I also had some conversations with others to really figure out if this is something that should be included or if we should wait until there is enough user feedback.

My initial thought is that I would hate to add another dependency (Pandas) just so we could check the type. I'm not sure that the juice is worth the squeeze since adding this dependency would :

1. literally save the user from typing 7 additional characters (`.values`)
2. be more implicit and less explicit
3. feel compelled to hand back a pandas dataframe if that were the input 

Again, just thinking out loud here.

> Another thing to consider would be NumPy structured arrays. The stumpy results are currently of dtype object because they're a mixture of floats and ints. This would let the results' columns be self-documenting. As a bonus, performance should improve if data is stored in a structured array with defined and aligned types.

I like the thought here in that the types would be clearer. That has bugged me. However, I don't think that we'd actually see any performance improvements if any since the output array being returned is strictly being used for the storage of the results and not for the intermediate calculations (which are typically of the same type and not of mixed type). But, perhaps, you are referring to performance bumps when you want to operate on the matrix profile itself afterwards?

**Comment by bdice** [comment]
For sure - given those considerations, I think that it's perfectly fine to not support pandas data as inputs. I agree that it appears to be a pain and not worth the effort unless users demand it. Holding new feature ideas (like this one) to a high standard and critical eye is necessary to preserve your time and energy, as well as keep the package from being bloated / hard to maintain. If you'd like to mark this "wontfix" or just close it, feel free.

Just to clarify - the code I included with `except ImportError` would make `pandas` a "soft" dependency - if `pandas` can't be found, then the code would only accept NumPy arrays. (But users won't be passing in pandas data unless they have it installed, so you're safe that way.)

**Comment by seanlaw** [comment]
> Just to clarify - the code I included with except ImportError would make pandas a "soft" dependency - if pandas can't be found, then the code would only accept NumPy arrays. (But users won't be passing in pandas data unless they have it installed, so you're safe that way.)

Now, why did you have to go and say that? You've made me reconsider adding this to `core.py`. Thanks for the clarification. I will throw something together.

**Comment by bdice** [comment]
We do this in `signac` if you want a reference, but it's for optional pandas outputs (not inputs), so the logic is slightly different.

https://github.com/glotzerlab/signac/blob/cbe589d155c505e3c892fca63db173e627e9c1b2/signac/contrib/project.py#L1809-L1827

Test:
https://github.com/glotzerlab/signac/blob/88ede71b9d16a61c92f43f05c9662ef6725518b2/tests/test_pandas_integration.py

**Comment by seanlaw** [comment]
It turns out that we may not even need to depend on pandas at all since I learned that pandas dataframes and series both support the numpy `__array__` protocol so:

```
df = pd.Series([1, 2, 3, 4])
np.asarray(df)
```

or

```
a = np.array([1,2,3,4])
np.asarray(a)
```

will BOTH return

```
array([1, 2, 3, 4])
```

I'm going to update the code to reflect this but my initial checks seems to pass the unit tests when I removed all of the pandas bits.

**Comment by seanlaw** [comment]
For future reference, a really nice and simple way to check if something is a DataFrame without importing Pandas is to use the `__name__` attribute from `type`:

```
if type(df).__name__ == 'DataFrame':
    print("This is a DataFrame")
```
