### ISSUE TITLE
Add SCRIMP++

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#113]
The original SCRIMP++ paper is [here](https://www.cs.ucr.edu/~eamonn/SCRIMP_ICDM_camera_ready_updated.pdf)

The original data, source code, and reference website for SCRIMP++ is [here](https://sites.google.com/site/scrimpplusplus/)

Additional [paper from another group](https://github.com/TDAmeritrade/stumpy/files/4477514/10.1007%40s11227-020-03199-w.pdf)

To compile the C++ code above:

```
conda install -y fftw
export LD_LIBRARY_PATH=/path/to/miniconda3/lib"
g++ -o prescrimp -I/path/to/miniconda3/include -L/path/to/miniconda3/lib -lfftw3 prescrimp.cpp
```

Then, create a time series input file with:

```
584.0
-11.0
23.0
79.0
1001.0
0.0
-19.0
```

And run the executable:

```
export LD_LIBRARY_PATH="/path/to/miniconda3/lib"
./prescrimp time_series 3 1
```

**Comment by seanlaw** [comment]
According to Stuart Archibald (Numba dev), to force SCRIMP++ to complete within a user specified time, one could try something like:

```
from numba import njit
import numpy as np
import threading

@njit
def foo(m, n, FLAG):
    X = np.zeros((m, n))
    acc = 0
    while FLAG[0] == 0:
        print("In loop")
        acc += np.linalg.svd(X)[1][0]
    print("Got signal, exiting")
    return acc


m = n = 1000
FLAG = np.array([0])
runner_thread = threading.Thread(target=foo, args=(m, n, FLAG))

def SIGNAL_FLAG(flag):
    FLAG[0] = 1

# finish in permitted_time seconds or signal to stop
permitted_time = 5
timeout = threading.Timer(permitted_time, SIGNAL_FLAG, args=(FLAG,))
try:
    timeout.start()
    runner_thread.start()
    runner_thread.join()
finally:
    timeout.cancel()
```

**Comment by seanlaw** [comment]
The example that was used in Figure 5, Figure 9, Figure 11, and Figure 12 was the typical steamgen data set:

```
import urllib
import ssl
import io
import os
import pandas as pd

colnames = ['drum pressure',
            'excess oxygen',
            'water level',
            'steam flow'
           ]

context = ssl.SSLContext()  # Ignore SSL certificate verification for simplicity
url = 'https://www.cs.ucr.edu/~eamonn/iSAX/steamgen.dat'
raw_bytes = urllib.request.urlopen(url, context=context).read()
data = io.BytesIO(raw_bytes)
steam_df = pd.read_csv(data, header=None, sep="\s+")
steam_df.columns = colnames
steam_df['steam flow'].head()
```

**Comment by mexxexx** [comment]
On my machine some of the tests for Scrimp fail. I appears to depend on the random data, because sometime they pass, sometimes not.

**Comment by seanlaw** [comment]
@mexxexx Thanks for letting me know. I have some time this afternoon and I will take a look. Are you able to tell me what the random seed is that causes the test to fail?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mexxexx** [comment]
Okay, I just saw that this is cause by some change I did to naive_mass, sorry for the confusion. I will open a separate Issue to discuss that change.

**Comment by seanlaw** [comment]
@mexxexx I just committed the code so please take a look and you can contribute a blog in this issue #165

**Comment by mexxexx** [comment]
Hi @seanlaw , I like the way the code is structured and the fact that it is a generator. I will play around with it and see if I come across any things that need to be clarified. Thank you for implementing it!

**Comment by seanlaw** [comment]
@mexxexx Depending on which version you are looking at, for consistency, I renamed "SCRIMP" to "SCRUMP" (which happens to also mean "Anything small or undersized" or derived from "to shrink", amongst other things) so you should see `scrump` and `prescrump`.

I plan to further refactor the code so that `prescrump` can be parallelized with all threads. It will take some time and then I will probably focus on adding `np.nan/np.inf` supoort to `gpu_stump`

**Comment by mexxexx** [comment]
Hi sean, I started to write the tutorial based on the streamgen dataset you used in another tutorial, but if you want, we can change the data sets. However, I noticed that I don't understand how the generator is expected to work.

From what I understand it does the following:
1. You choose a percentage for scrimp (lets say 10%).
2. Then, the length of the generator is calculated by 1.0/percentage = 10 iterations.
3. Each of these iterations refines the matrixprofile.

What exactly is the goal here? To have the full matrix profile after these 10 iterations? I don't think this is guaranteed, as each time the chosen subsequences should be random.

**Comment by seanlaw** [comment]
@mexxexx At the extreme of `percentage=1.0`, this is 100% (`percentage` is bounded between 0.0 and 1.0 but maybe this is confusing and we should rename this parameter but this is documented) and so the matrix profile should yield the exact same matrix profile results as `stump` (ignore the indices) and it takes about the same time as `stump` (well, half the time since it currently only supports self-joins and only computes the upper triangular distance matrix).  Obviously, if the user doesn't have the time to go to 100% completion then they can stop early. Technically, even at 10%, the matrix profile is being refined since it has already ran through multiple diagonals and updated the matrix profile according to approximately 10% of the distance matrix. If you take the next iteration of the generator then the matrix profile will have updated the matrix profile according to approximately 20% of the distance matrix and so on.

> What exactly is the goal here? To have the full matrix profile after these 10 iterations?  I don't think this is guaranteed, as each time the chosen subsequences should be random.

Actually, if `percentage=0.1` (i.e., 10%) then the full, exact matrix profile is guaranteed after 10 iterations. This is why `stomp` should be replaced with `scrimp` since at `percentage=1.0`, the output should be equal.

**Comment by mexxexx** [comment]
> At the extreme of percentage=1.0, this is 100% (percentage is bounded between 0.0 and 1.0 but maybe this is confusing and we should rename this parameter but this is documented)

That is clear, I don't think anything should be change here, as I would say this is classic or general terminology.

> Actually, if percentage=0.1 (i.e., 10%) then the full, exact matrix profile is guaranteed after 10 iterations. This is why stomp should be replaced with scrimp since at percentage=1.0, the output should be equal.

I didn't know this. How is this implemented? I thought that one run of `_stump` chooses some of the sub sequences by random. So does this mean that two iterations of a 10% scrump call is the same as one iteration of a 20% call?

**Comment by seanlaw** [comment]
> So does this mean that two iterations of a 10% scrump call is the same as one iteration of a 20% call?

Yes, exactly. Mind you, since it is "random", the order of the `orders` array will change each time you call `scrump` to give you a new generator. You can replace

```
orders = np.random.permutation(range(excl_zone + 1, n - m + 2))
```

with
```
orders = np.arange(excl_zone + 1, n - m + 2)
```

And then you should always get the same `orders` array and then you'll see that 2x10% should give the same output as 1x20%

**Comment by seanlaw** [comment]
> How is this implemented? I thought that one run of _stump chooses some of the sub sequences by random. 

So, it feels like it's choosing a subsequence at random but it is not. It is choosing a diagonal at random. For instance, if we have the following fake distance matrix that might be computed:

```
[[1, 2, 3, 4, 5],
 [6, 1, 2, 3, 4],
 [7, 6, 1, 2, 3],
 [8, 7, 6, 1, 2],
 [9, 8, 7, 6, 1]] 
``` 

With `stumpy.stump`, you'd compute the distance matrix row-by-row and then update the matrix profile and matrix profile index. That is, you compute `[1, 2, 3, 4, 5]` distances first and update P, I along each column (or row). Then you compute `[6, 1, 2, 3, 4]` and update P, I.

With `stumpy.scrump`, you choose a random diagonal (technically, you randomize the order of the diagonals and produce an array called `orders` and then you iterate over `orders`) and you compute only the distances from that diagonal. So, instead of going across each row, you go diagonally across a diagonal. In my array, I've purposely made the diagonal values in the distance matrix the same so we can call the identity/eye diagonal `diag-1` (i.e., where all the values are `1`), the off diagonal above that is `diag-2`, the off diagonal below the identity as `diag-6`, etc. So, if we start off with `P = [inf, inf, inf, inf, inf]` and the first "diagonal` is, say, `diag-3` then we'd get all of the "new" distances and update P to `[inf, inf, 3, 3, 3]`. Then you choose another diagonal, say, `diag-9` and update P to `[9, inf, 3, 3, 3]`. Eventually, you'd run through all of the diagonals and end up with the exact matrix profile.

In the case of `scrump`, we parallelize things so that we actually take our `orders` array and roughly chop up the total number of distance computations into approximately equal chunks so that each thread performs roughly the same number of distance computations (since it is different from each diagonal).

**Comment by mexxexx** [comment]
Thank you for that explanation! Would you mind explaining how the `_get_orders_ranges` function works/what it is doing?

**Comment by seanlaw** [comment]
> Thank you for that explanation! Would you mind explaining how the _get_orders_ranges function works/what it is doing?

Certainly! Note that this function is super naive but since it's only being called once, I just went with it but I have plans to eventually overhaul it with something that is NumPy vectorized (see `stumpy.core._get_array_ranges).

> In the case of scrump, we parallelize things so that we actually take our orders array and roughly chop up the total number of distance computations into approximately equal chunks so that each thread performs roughly the same number of distance computations (since it is different from each diagonal).

As mentioned above, what `_get_orders_ranges` is doing is to split up the diagonals so that each thread roughly computes the same number of diagonals. So, continuing with our previous example:

```
[[1, 2, 3, 4, 5],
 [6, 1, 2, 3, 4],
 [7, 6, 1, 2, 3],
 [8, 7, 6, 1, 2],
 [9, 8, 7, 6, 1]] 
```

For ease of explanation, let's start with some assumptions: 

1. We only have 2 threads for parallelization
2. We don't care about about any exclusion zones so all (upper) diagonals are fair game (this is not the reality) 
3. the user only wants to compute 40% at each iteration of the generator 
4. since we only support self-joins (for now), we are only considering the upper triangle of the distance matrix (the distance matrix is symmetrical)

First, we randomly shuffle the diagonals so we might get `orders = [diag_5, diag_3, diag_2, diag_4, diag_1]`. If we look at the total number of (upper triangular) distance computations for an exact matrix profile, there would be `5 + 4 + 3 + 2 + 1 = 15`. So, 40% of 15 would be 6 distances to minimally compute (but we need whole numbers though!). From `orders`, the number of distances being computed in each diagonal would be `[1, 3, 4, 2, 5]`. Let's say we start with a single thread (serial, no parallelization), then the `_get_orders_ranges` would count the number of distances for `diag_5` and see that it hasn't met/exceeded the 40% threshold (or 6 distances) and so it moves onto `diag_3` (next in `orders`) and see that `1 + 3 = 4` (still below the threshold). Then, it adds `diag_2` and sees that `1 + 3 + 4 = 8` which exceeds the the threshold of 40%/6 distances and we can stop. What this means is that for a single thread, the `start` index corresponding to `orders` would be `0` and the (exclusive) `stop` index would be `3`. Note that no actual distances have been computed here, only the count of how many distances would ultimately be computed. For a single thread, `n_splits = 1` and the array that gets returned will be

```
[[0, 3]]
```

So, for 40%, we know that regardless of how many threads, we want to stop at index 3 (exclusive). This is what `_get_max_order_idx` does. It takes the `orders` array, starts at some `start` index value and increments and tells you where you should stop when you've met or exceeded the desired percentage (in this case, 40%). When you want the "next" 40% then you simply supply index 3 as your `start` value to `get_max_order_idx` and it will tell you which diagonal index you need to stop at when you've met or exceeded the next 40% computation of distances. 

In the case where there are two threads (parallel), we want each thread to roughly compute the same number of distances. So, `_get_orders_ranges` takes the set of "allowed diagonals" from `orders` and splits up those diagonals (roughly) and gives us the start/stop index ranges (corresponding to the index of `orders`). Since there are two threads, `n_split = 2` and we are then aiming for each thread to compute 20% of the desired 40% total distances. So, it does what we did with the single thread case but, instead, it aims to meet/exceed the 20% threshold for each thread (instead of 40% each). Remember, we are bounded by starting at index 0 and stopping at index 3 (thanks to _get_max_order_idx`. 

So, `get_orders_ranges` would run through the for loop and count the number of distances for `diag_5` and see that it hasn't met/exceeded the 20% threshold (or 3 distances) for `n_split = 2` and so it moves onto `diag_3` (next in `orders`) and see that `1 + 3 = 4` met/exceed the 20% threshold for one thread and so the start/stop index for thread 1 is `[0, 2]`. Then, works on thread 2 by running through the remaining indices of `orders` in the range of `[2, 3]`. It starts with index 2 from `orders` which correspond to `diag_2` and sees that the number of distances to be computed is `4` which exceeds the the threshold of 20%/3 distances and we can stop. So, for thread 2, the `start` index corresponding to `orders` would be `2` and the (exclusive) `stop` index would be `3`. Again, note that no actual distances have been computed here, only the count of how many distances would ultimately be computed. The output of `_get_orders_ranges` for `n_split = 2` would be:

```
[[0, 2],
 [2, 3]]
``` 

The natural question is what happens if there are not enough indices to satisfy the number of threads? Like, `n_split = 3`? `_get_orders_ranges` would just return:

```
[[0, 2],
 [2, 3],
 [3, 3]]
```

So, the last thread would do nothing (i.e., it would not compute any distances and leave it to the first two threads)!  However, this will be exceedingly rare and really only occur for super short time series so I'm not concerned. And, for long time series, the rough counts being split across all threads are fairly equal based on some naive tests that I've done. The goal isn't to be perfect about it but to ensure that all threads are computing for roughly the same amount of time.

**Comment by mexxexx** [comment]
Great explanation, that totally makes sense! I just couldn't figure it out from reading only the code.

**Comment by seanlaw** [comment]
>  I just couldn't figure it out from reading only the code.

I agree that this is hard to read. This chunking idea seems to be a recurring theme in Numba parallelization and so it will be a work in progress to add some utility functions in `core.py` that will make it easier to split arrays and return indices for `prange` usage

**Comment by mexxexx** [comment]
Is it right that both tests currently are only for the complete matrix profile? As I saw that presrcump needs `s=1` and from scrump you run through the whole generator.

How about a `naive_scrump` that calculates the complete distance matrix using mass, and then selects the same diagonals as scrimp? (maybe write a `naive_get_orders_ranges` to compute the ranges, and do the following:

```
def naive_scrump(orders_ranges, percentage):
    dist_matrix = ... #compute all pairwise distances
    profile = ... #select diagonals from orders_ranges based on percentage

seed = np.random.integer() # however this is done, just too keep the randomness
#seed = 0 #deterministic alternative
percentage = xxx #maybe as a new parameter as pytest fixture

np.random.seed(seed)
orders = np.random.permutation(range(excl_zone + 1, n - m + 2))
orders_ranges = naive_orders_ranges(orders)
left = naive_scrump(orders_ranges, percentage )

np.random.seed(seed)
right_gen = scrump(percentage)
right = next(right_gen)
```

This is obviously only pseudo code, but the idea is to reset the seed to get the same permutations in scrump and naive_scrump, so to actually test the approximation of scrump. One can do the same for naive_prescrump and then even test the preprocessing phase this way. And then, as percentage fixture one could pass `[0.01, 0.1, 0.5, 1.0]`for example.

**Comment by mexxexx** [comment]
I was trying to refactor the tests and I think I found an indexing error:

Lets assume we have a time series with `n=6, m=3`.  Lets call the distance between subsequence starting at i and at another at j `d_ij`. Then we have the upper triangle of the distance matrix that we want to compute (doing it zero based as it is what we use)

```
d_00 d_00 d_02 d_03
     d_11 d_12 d_13
          d_22 d_23
               d_33
```

The exclusion zone will be 1 (3/4+1), so all the distance where I will write the `d` with a capital letter will be inf.


```
D_00 D_00 d_02 d_03
     D_11 D_12 d_13
          D_22 D_23
               D_33
```
So we only have to compute diagonals 2 and 3. Hence we should have `orders=np.random.permutation(range(excl_zone + 1, n - m + 1))`, since `n-m+1=4`. However, in the code the upper bound for the range is `n - m + 2`. (`stumpy.scrump`)

Furthermore, there is a small error in the `_compute_diagonal` method:
Let's say we compute diagonal 2 (this means `k=2`), then we have to calculate `d_02` and `d_13`.

Currently, the code is the following:
```
for i in range(0, n - m + 2 - k):
            if i == 0:
                QT = np.dot(T[i : i + m], T[i + k - 1 : i + k - 1 + m])
            else:
                QT = QT - T[i - 1] * T[i + k - 2] + T[i + m - 1] * T[i + k + m - 2]

            D_squared = core._calculate_squared_distance(
                m, QT, μ[i], σ[i], μ[i + k - 1], σ[i + k - 1],
            )
```
This means we would calculate the distances `d_01`, `d_12`, `d_23`. But we already excluded this diagonal with the exclusion zone, see above. So actually we would need 

```
for i in range(0, n - m + 1 - k)
```
(notice +1 instead of +2), and 

```
D_squared = core._calculate_squared_distance(
                m, QT, μ[i], σ[i], μ[i + k], σ[i + k],
)
``` 

(since we want the distance `d_ik` and not `d_i(k-1)`. 

Then, we also have to adapt the calculation of QT to the right indices. They should be

```
if i == 0:
    QT = np.dot(T[i : i + m], T[i + k : i + k + m])
else:
    QT = QT - T[i - 1] * T[i + k - 1] + T[i + m - 1] * T[i + k + m - 1]
```

Do you agree on this? Did I miss anything? There might be some errors in the paper, its difficult to say since say use one-based indexing, but I think what I outlined here makes the most sense in our case.

By the way, because the exclusion zone is handled so nicely by not starting from the zeroth diagonal, the checks for the exclusion zone in `_compute_diagonal` can be ignored.

**Comment by seanlaw** [comment]
@mexxexx Give me some time to digest the indexing issues. I had a hell of a time trying to follow their paper and converting their one-based indexing over and have the output match `stumpy.stump`. I will review your comments and maybe we should open a new issue.

Regarding the exclusion zone, the reason why I left it in there was because I was planning ahead to generalize this to AB-joins in the future. So, instead of maintaining separate codes, we'd just have one function for both AB-joins and self-joins.

**Comment by seanlaw** [comment]
> Is it right that both tests currently are only for the complete matrix profile? As I saw that presrcump needs `s=1` and for scrump you run through the whole generator.
> 
> How about a `naive_scrump` that calculates the complete distance matrix using mass, and then selects the same diagonals as scrimp? (maybe write a `naive_get_orders_ranges` to compute the ranges, and do the following:
> 
> ```
> def naive_scrump(orders_ranges, percentage):
>     dist_matrix = ... #compute all pairwise distances
>     profile = ... #select diagonals from orders_ranges based on percentage
> 
> seed = np.random.integer() # however this is done, just too keep the randomness
> #seed = 0 #deterministic alternative
> percentage = xxx #maybe as a new parameter as pytest fixture
> 
> np.random.seed(seed)
> orders = np.random.permutation(range(excl_zone + 1, n - m + 2))
> orders_ranges = naive_orders_ranges(orders)
> left = naive_scrump(orders_ranges, percentage )
> 
> np.random.seed(seed)
> right_gen = scrump(percentage)
> right = next(right_gen)
> ```
> 
> This is obviously only pseudo code, but the idea is to reset the seed to get the same permutations in scrump and naive_scrump, so to actually test the approximation of scrump. One can do the same for naive_prescrump and then even test the preprocessing phase this way. And then, as percentage fixture one could pass `[0.01, 0.1, 0.5, 1.0]`for example.

I like this as it is already better than what is currently in place. When I was coding up SCRUMP, I was actually thinking about adding a parameter that allows the user to provide the `orders` array and, if it is `None` then you just generate it and permute it. Of course, you'd have to ensure that the length is the correct length, the min/max is in the correct range. This would be helpful if the user wanted to prioritize which diagonals to traverse first AND you could use it for reproducible tests instead of having to set the random seed (you'd just pass in your `orders` array to both `scrump` and `naive_scrump`.

**Comment by mexxexx** [comment]
> Of course, you'd have to ensure that the length is the correct length, the min/max is in the correct range. This would be helpful if the user wanted to prioritize which diagonals to traverse first AND you could use it for reproducible tests instead of having to set the random seed (you'd just pass in your orders array to both scrump and naive_scrump. Thoughts?

Can you think of any scenario, where the user would need/want control over the orders?

**Comment by seanlaw** [comment]
> Can you think of any scenario, where the user would need/want control over the orders?

The short answer is "I don't know". I can dream up contrived scenarios where the user wants to reproduce the approximate matrix profile at a later date but this can still be done by setting the random seed before calling `scrump`. This is purely gut instinct and it doesn't have to be added.

**Comment by seanlaw** [comment]
> I was trying to refactor the tests and I think I found an indexing error:
> 
> Lets assume we have a time series with `n=6, m=3`. Lets call the distance between subsequence starting at i and at another at j `d_ij`. Then we have the upper triangle of the distance matrix that we want to compute (doing it zero based as it is what we use)
> 
> ```
> d_00 d_00 d_02 d_03
>      d_11 d_12 d_13
>           d_22 d_23
>                d_33
> ```
> 
> The exclusion zone will be 1 (3/4+1), so all the distance where I will write the `d` with a capital letter will be inf.
> 
> ```
> D_00 D_00 d_02 d_03
>      D_11 D_12 d_13
>           D_22 D_23
>                D_33
> ```
> 
> So we only have to compute diagonals 2 and 3. Hence we should have `orders=np.random.permutation(range(excl_zone + 1, n - m + 1))`, since `n-m+1=4`. However, in the code the upper bound for the range is `n - m + 2`. (`stumpy.scrump`)
> 
> Furthermore, there is a small error in the `_compute_diagonal` method:
> Let's say we compute diagonal 2 (this means `k=2`), then we have to calculate `d_02` and `d_13`.
> 
> Currently, the code is the following:
> 
> ```
> for i in range(0, n - m + 2 - k):
>             if i == 0:
>                 QT = np.dot(T[i : i + m], T[i + k - 1 : i + k - 1 + m])
>             else:
>                 QT = QT - T[i - 1] * T[i + k - 2] + T[i + m - 1] * T[i + k + m - 2]
> 
>             D_squared = core._calculate_squared_distance(
>                 m, QT, μ[i], σ[i], μ[i + k - 1], σ[i + k - 1],
>             )
> ```
> 
> This means we would calculate the distances `d_01`, `d_12`, `d_23`. But we already excluded this diagonal with the exclusion zone, see above. So actually we would need
> 
> ```
> for i in range(0, n - m + 1 - k)
> ```
> 
> (notice +1 instead of +2), and
> 
> ```
> D_squared = core._calculate_squared_distance(
>                 m, QT, μ[i], σ[i], μ[i + k], σ[i + k],
> )
> ```
> 
> (since we want the distance `d_ik` and not `d_i(k-1)`.
> 
> Then, we also have to adapt the calculation of QT to the right indices. They should be
> 
> ```
> if i == 0:
>     QT = np.dot(T[i : i + m], T[i + k : i + k + m])
> else:
>     QT = QT - T[i - 1] * T[i + k - 1] + T[i + m - 1] * T[i + k + m - 1]
> ```
> 
> Do you agree on this? Did I miss anything? There might be some errors in the paper, its difficult to say since say use one-based indexing, but I think what I outlined here makes the most sense in our case.
> 
> By the way, because the exclusion zone is handled so nicely by not starting from the zeroth diagonal, the checks for the exclusion zone in `_compute_diagonal` can be ignored.

You know, I actually tried this originally and I couldn't seem to get the results to line up with the `stumpy.stump` results. If this works (i.e., matches `stumpy.stump`) then I would be happy to accept the PR as it certainly fits the bill. In fact, it's even better if you can figure out how to make this work for AB-joins as well 😄

**Comment by seanlaw** [comment]
> You know, I actually tried this originally and I couldn't seem to get the results to line up with the stumpy.stump results.

I just tried it again by replacing the components that you had mentioned above but my matrix profile didn't match `stumpy.stump`. I don't fully understand why
