### ISSUE TITLE
Handling NaN and inf Values for MSTUMP

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#117]
This is a follow up to #115 to handle NaN/inf values in `mstump`

**Comment by mexxexx** [comment]
I'm doing some work on mstump right now and I will probably look into this issue soon.

**Comment by seanlaw** [comment]
Ohh, awesome! I plan to find some time on Friday afternoon to work on the GPU part of this. Can I assign this (N-D) issue to you for now?

**Comment by mexxexx** [comment]
Sure! I will have to see how much time I will have to work on it

**Comment by seanlaw** [comment]
Note that this is the single server version. The Dask Distributed version `mstumped` can be found in #130
