### ISSUE TITLE
Add Tutorial for SDTS 

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#118]
The original SDTS paper is [here](https://www.cs.ucr.edu/~eamonn/WeaklyLabeledTimeSeries.pdf)

The supporting SDTS data/code is [here](https://sites.google.com/view/weaklylabeled)

The goal of this issue is to create a simple tutorial that reproduces an example from the paper. Following this, we can **consider potentially** improving the code, extracting it, and adding it to the core of STUMPY. Adding a minimum tutorial is just the first step to contributing to STUMPY. There are a lot of other details, questions, and design decisions that would still need to be addressed before it is fully documented/tested/supported and released/exposed to the public. Our goal is never to rush getting features into the core.

**Comment by seanlaw** [comment]
There doesn't seem to be much momentum so closing this for now

**Comment by Ninimama** [comment]
@seanlaw 

(if you need help with this:)
I checked out the paper and I probably go through it anyway as I might try to apply it on my data and see how it works. So I will probably go through this paper after finishing the time series chain project #211 and see if I can implement it.

**Comment by seanlaw** [comment]
> I checked out the paper and I probably go through it anyway as I might try to apply it on my data and see how it works. So I will probably go through this paper after finishing the "geometric chain" project.

Sounds good to me! I don't know much about this paper (will have to re-read it as it has been a while) but @mexxexx might be able to help answer some questions too on this one.

**Comment by Ninimama** [comment]
@seanlaw 
I am going to submit a PR to start reading and implementing this paper.

**Comment by seanlaw** [comment]
Great!

**Comment by seanlaw** [comment]
@NimaSarajpoor Please feel free to re-open if you are still considering working on this
