### ISSUE TITLE
Move MSTUMP / MSTUMPED to Using Rolling Chunked STDDEV

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#129]
Currently, `core.compute_mean_std` might be able to handle chunked STDDEV calculation for multi-dimensional times series data. However, `mstump`/`mstumped` are not currently using this function to compute its STDDEV. Instead, `mstump`/`mstumped` uses `mstump._multi_compute_mean_std`.

**Comment by mexxexx** [comment]
I'm taking care of this issue in my implementation for the handling of nan/inf values

**Comment by seanlaw** [comment]
I just wanted to break this out so that each PR is small instead of one big PR. It makes it a lot easier to review too

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seanlaw** [comment]
It just occurred to me that maybe we should move `mstump._multi_compute_mean_std` into `test_mstump.py` and call it `naive_multi_compute_mean_std` since the current test is using NumPy directly. So, our (future) chunked implementation (NumPy) and test (NumPy) are nearly identical and this is bad. We should test the future chunked implementation against a modified version of `mstump._multi_compute_mean_std`.

The same thing is true regarding `core.test_compute_mean_std`. It is currently testing against NumPy. We should probably replace the naive implementation with the original `core.compute_mean_std`. 

To be clear, I don't think we need to test `np.inf`/`np.nan` in these cases. This should be handled by NumPy's own testing. For the most part, we should trust that NumPy is correctly computing mean/stddev and what we should be testing is whether our function returns back the promised mean/stddev pair. Just thinking out loud here.

**Comment by mexxexx** [comment]
> I just wanted to break this out so that each PR is small instead of one big PR. It makes it a lot easier to review too

I agree. But right now I have everything almost ready in one big pull pull request. Any suggestions?

**Comment by mexxexx** [comment]
I modified `core.compute_mean_std` in the following way

```
def compute_mean_std(T, m, num_chunks=1, max_iter=10):
    if len(T.shape) == 1:
        shape = 0
    elif len(T.shape) == 2:
        shape = 1
    else:  # pragma nocover
        raise ValueError("T has to be one or two dimensional!")

    for iteration in range(max_iter):
        try:
            chunk_size = math.ceil((T.shape[shape] + 1) / num_chunks)

            mean_chunks = []
            std_chunks = []
            for chunk in range(num_chunks):
                start = chunk * chunk_size
                stop = min(start + chunk_size + m - 1, T.shape[shape])

                tmp_mean = np.mean(rolling_window(T[start:stop], m), axis=shape + 1)
                mean_chunks.append(tmp_mean)
                tmp_std = np.nanstd(rolling_window(T[start:stop], m), axis=shape + 1)
                std_chunks.append(tmp_std)

            M_T = np.hstack(mean_chunks)
            Σ_T = np.hstack(std_chunks)
            break

        except MemoryError:  # pragma nocover
            num_chunks *= 2

    if iteration < max_iter - 1:
        M_T[np.isnan(M_T)] = np.inf
        Σ_T[np.isnan(Σ_T)] = 0

        return M_T, Σ_T
    else:  # pragma nocover
        raise MemoryError(
            "Could not calculate mean and standard deviation. "
            "Increase the number of chunks or maximal iterations."
        )
```

So the function can handle the one and multidimensional case. 

I agree about the tests. They should be changed to using the version like in `mstump._multi_compute_mean_std`.

**Comment by seanlaw** [comment]
I think we can eliminate some code:

```
def compute_mean_std(T, m, num_chunks=1, max_iter=10):
    if T.ndim > 2:  # pragma nocover
        raise ValueError("T has to be one or two dimensional!")

    for iteration in range(max_iter):
        try:
            chunk_size = math.ceil((T.shape[0] + 1) / num_chunks)  # This is always T.shape[0] and not actually dependent on the shape

            mean_chunks = []
            std_chunks = []
            for chunk in range(num_chunks):
                start = chunk * chunk_size
                stop = min(start + chunk_size + m - 1, T.shape[0])  # This is always T.shape[0] and not actually dependent on the shape

                tmp_mean = np.mean(rolling_window(T[start:stop], m), axis=T.ndim)
                mean_chunks.append(tmp_mean)
                tmp_std = np.nanstd(rolling_window(T[start:stop], m), axis=T.ndim)
                std_chunks.append(tmp_std)

            M_T = np.hstack(mean_chunks)
            Σ_T = np.hstack(std_chunks)
            break

        except MemoryError:  # pragma nocover
            num_chunks *= 2

    if iteration < max_iter - 1:
        M_T[np.isnan(M_T)] = np.inf
        Σ_T[np.isnan(Σ_T)] = 0

        return M_T, Σ_T
    else:  # pragma nocover
        raise MemoryError(
            "Could not calculate mean and standard deviation. "
            "Increase the number of chunks or maximal iterations."
        )
```

**Comment by seanlaw** [comment]
> I think it is better to have two private functions _rolling_mean_std and _rolling_mean_std_multidimensional that are called accordingly. Only to not bloat this function to much.

Can you elaborate on this? I don't understand what your vision is regarding this

**Comment by seanlaw** [comment]
Okay, I see the PR for this now. I don't feel like this function is bloated. It is fairly self contained and I think that splitting up is adding unnecessary complexity especially if you consider my suggestion above.

**Comment by mexxexx** [comment]
That looks way more natural, thank you!

**Comment by seanlaw** [comment]
@mexxexx You are right and `T.shape[-1]` is pretty clear. Let's go with that and let's not split the functions up and keep it all in one. Does that work?

**Comment by mexxexx** [comment]
Yes that is the best solution I would say

**Comment by seanlaw** [comment]
If you wouldn't mind, can you please resubmit a new PR and close out the current #133 ?
