### ISSUE TITLE
NaN/Inf and zero-mean subsequences

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#139]
I ran into a bug concerning time series containing NaN/Infs and subsequences with zero mean. 

Sadly I didn't manage to reproduce it with a small example in the jitted case, but with disabling numba jitting (`export NUMBA_DISABLE_JIT=1`) here is a demonstration:

```
>>> T = np.array([-1, 0, 1, np.inf, 1, 0, -1])
>>> stumpy.stump(T, 3)
array([nan, nan, 1.732051, nan, nan])
```
I only printed the Matrix Profile. Clearly this result is wrong, and the correct MP would be the following:
```
array([3.4641012, inf, inf, inf, 3.4641012])
```

Now I investigated the problem and the reason of this weird behavior lies in the `core._calculate_square_distance_profile` function:

```
D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
```
For handling `nan`/`inf` values, we set the means of the affected sub-sequences to `np.inf` and the rationale behind this is that that `D_squared` at these points will be `inf`. This is true in general, since `x * np.inf = np.inf`. However, not for `x=0`: `0 * np.inf = np.nan`.

So this line produces `nan` results if either `μ_Q=0` and `M_T[i]=np.inf` or `μ_Q=np.inf` and `M_T[i]=0`. With code compiled with `fastmath=True` the behaviour is undefined, what is why I couldn't reproduce the error, but it is definitely there as I saw it with my data.

The solution for this is simple, as we just need to handle the special cases. As a first draft I propose this, but I think it's not pretty and readable:

```
@njit(parallel=True, fastmath=True)
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero
    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
    inf_mask = np.isinf(D_squared)

    if np.isinf(μ_Q):
        D_squared[:] = np.inf
    else:
        if μ_Q == 0.0:
            D_squared = np.abs(2 * m * (1.0 - QT / denom))

        threshold = 1e-7
        if σ_Q < threshold:  # pragma: no cover
            D_squared[:] = m
        D_squared[Σ_T < threshold] = m
        D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0
        D_squared[inf_mask] = np.inf

    return D_squared
```

**Comment by seanlaw** [comment]
Great. Let me take a closer look and see if we can simplify the logic and avoid branching.

Minimally, we should add this test case to the unit tests.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seanlaw** [comment]
Would something like this work?

```
@njit(parallel=True, fastmath=True)
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero

    if np.isinf(μ_Q):
        D_squared[:] = np.inf
    elif μ_Q == 0.0:
        D_squared = np.abs(2 * m * (1.0 - QT / denom))
    else:
        D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    inf_mask = np.isinf(D_squared)

    threshold = 1e-7
    if σ_Q < threshold:  # pragma: no cover
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0
    D_squared[inf_mask] = np.inf

    return D_squared
```

I don't even think these two lines are necessary:

```
elif μ_Q == 0.0:
    D_squared = np.abs(2 * m * (1.0 - QT / denom))
```

Since `if μ_Q == 0.0`, then `m * μ_Q * M_T == 0` and so it would already be handled by:

```
else:
    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
```

**Comment by mexxexx** [comment]
I think the code should work, but leaving in the lines

```
elif μ_Q == 0.0:
    D_squared = np.abs(2 * m * (1.0 - QT / denom))
```
is important. Because if `M_T` is `inf` at a certain position, let's say `i`, then we would have `m * μ_Q * M_T[i] == np.nan`

**Comment by seanlaw** [comment]
Ahh, got it. Let's make sure to get the right tests in place to catch these things if we change the code in the future.

**Comment by mexxexx** [comment]
What do you think about the following solution?

```
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero

    D_squared = np.full(QT.shape[0], np.inf)
    if not np.isinf(μ_Q):
        D_squared[:] = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

        threshold = 1e-7
        if σ_Q < threshold:  # pragma: no cover
            D_squared[:] = m
        D_squared[Σ_T < threshold] = m
        D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

        D_squared[np.isinf(M_T)] = np.inf #########

    return D_squared
```

If `μ_Q==np.inf` then `D_squared == inf` and we dont need to calculate anything else. If this is not the case, then `D_squared[i] == np.inf` iif `M_T[i]==np.inf`. So we can actually remove the `inf_mask` that we used before. Also by this approach we eliminate the other problematic case where `μ_Q==0` and `M_T[i]==np.inf`, as any undefined value that will be produced there will be overwritten in the highlighted line anyways.

**Comment by mexxexx** [comment]
In python we could even do the following:
```
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero

    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    threshold = 1e-7
    if σ_Q < threshold:  # pragma: no cover
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

    D_squared[np.isinf(M_T)] = np.inf #########
    D_squared[np.isinf(μ_Q)] = np.inf #########

    return D_squared
```
but this doesn't seem to work with numba, because numba does not support indexing using only a bool.

**Comment by seanlaw** [comment]
@mexxexx For large arrays (100 M elements), if Numba is faster than we should stick to Numba.

**Comment by mexxexx** [comment]
> It also isn't clear why we need the denom = np.asarray(denom)? That is true, I didn't realize it even was there.

**Comment by seanlaw** [comment]
I remember now. There is some weird scenarios when it is a singleton floating point value

**Comment by seanlaw** [comment]
Btw, would this work in Numba?

```
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero

    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    threshold = 1e-7
    if σ_Q < threshold:  # pragma: no cover
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

    for i in numba.prange(D_squared.shape[0]):  # This will be parallelized in Numba I think
        if np.isinf(M_T[i]):
            D_squared[i] = np.inf
        if np.isinf(μ_Q):
            D_squared[i] = np.inf

    return D_squared
```

**Comment by seanlaw** [comment]
> We can even remove this line
>    denom[denom == 0] = 1e-10  # Avoid divide by zero
Because denom[i]==0 iif σ_Q==0 or Σ_T[i]==0 and both cases are caught afterwards.

I don't think this is True. IIRC, NumPy will print out a ton of warnings when there is any divide by zero situation

**Comment by mexxexx** [comment]
> Btw, would this work in Numba? 

yes it works, do you think it is faster? If it is, can the other vectorized operations also be done in a for loop instead?

**Comment by seanlaw** [comment]
Frankly, having all of the right tests in place to test all of the scenarios is the most important thing. It will provide a sanity for when we change/modify the code. I think this is the point in test-driven-development and when they discuss "red-green" refactoring (red is a failed test, green is a passing test).

1. Write a test that covers a new edge case
2. Run ALL of the tests
3. New test should fail (red) since code doesn't cover the edge case
4. Update code to handle new test
5. Run ALL of the tests
6. All tests including the new test should pass (green)

**Comment by seanlaw** [comment]
> yes it works, do you think it is faster? If it is, can the other vectorized operations also be done in a for loop instead?

The answer is "maybe". Numba takes some liberties and actually takes NumPy functions and converts/optimizes them in the background into a for-loop. One should just profile the execution of that function with different inputs and many times. There's no better way to know besides profiling unfortunately

**Comment by mexxexx** [comment]
Should we stick to the 'classic' numpy version for this issue and move the profiling somewhere else?

**Comment by seanlaw** [comment]
If this works (copied from above) and all tests pass:

```
def _calculate_squared_distance_profile(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero

    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    threshold = 1e-7
    if σ_Q < threshold:  # pragma: no cover
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

    for i in numba.prange(D_squared.shape[0]):  # This will be parallelized in Numba I think
        if np.isinf(M_T[i]):
            D_squared[i] = np.inf
        if np.isinf(μ_Q):
            D_squared[i] = np.inf

    return D_squared
```

Then I propose that we go with this

**Comment by mexxexx** [comment]
I did some profiling work and found the following (jupyter notebook in firefox, Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, 4 threads):

```
import numpy as np
from numba import njit, prange

@njit(parallel=True, fastmath=True)
def _calculate_squared_distance_profile_numpy(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero
    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    threshold = 1e-7
    if σ_Q < threshold:
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

    D_squared[np.isinf(M_T)] = np.inf
    if np.isinf(μ_Q):
        D_squared[:] = np.inf

    return D_squared

@njit(parallel=True, fastmath=True)
def _calculate_squared_distance_profile_parallel_inf(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    denom = m * σ_Q * Σ_T
    denom = np.asarray(denom)
    denom[denom == 0] = 1e-10  # Avoid divide by zero
    D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

    threshold = 1e-7
    if σ_Q < threshold:
        D_squared[:] = m
    D_squared[Σ_T < threshold] = m
    D_squared[(Σ_T < threshold) & (σ_Q < threshold)] = 0

    for i in prange(D_squared.shape[0]):
        if np.isinf(M_T[i]):
            D_squared[i] = np.inf
        if np.isinf(μ_Q):
            D_squared[i] = np.inf

    return D_squared

@njit(parallel=True, fastmath=True)
def _calculate_squared_distance_profile_parallel(m, QT, μ_Q, σ_Q, M_T, Σ_T):
    D_squared = np.empty(M_T.shape[0]) 
    threshold = 1e-7
    for i in prange(D_squared.shape[0]):
        if np.isinf(M_T[i]) or np.isinf(μ_Q):
            D_squared[i] = np.inf
        else:
            if σ_Q < threshold or Σ_T[i] < threshold:
                 D_squared[i] = m
            else:
                denom = m * σ_Q * Σ_T[i]
                if denom == 0:
                    denom = 1e-10
                D_squared[i] = np.abs(2 * m * (1.0 - (QT[i] - m * μ_Q * M_T[i]) / denom))

            if σ_Q < threshold and Σ_T[i] < threshold:
                D_squared[i] = 0

    return D_squared
```

```
import stumpy

size = 1000000
T = np.random.uniform(-1000, 1000, size)
m = 20

index = 1000
Q = T[index:index+m]

M_T, Σ_T = stumpy.core.compute_mean_std(T, m)
QT = stumpy.core.sliding_dot_product(Q, T)

μ_Q = M_T[index]
σ_Q = Σ_T[index]
```

size = 1e4:
```
>>> %timeit -n 10000 _calculate_squared_distance_profile_numpy(m, QT, μ_Q, σ_Q, M_T, Σ_T)
26.4 µs ± 809 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
>>> %timeit -n 10000 _calculate_squared_distance_profile_parallel_inf(m, QT, μ_Q, σ_Q, M_T, 
Σ_T)
29 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
>>> %timeit -n 10000 _calculate_squared_distance_profile_parallel(m, QT, μ_Q, σ_Q, M_T, Σ_T)
14.2 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

size = 1e5:
```
>>> %timeit -n 10000 _calculate_squared_distance_profile_numpy(m, QT, μ_Q, σ_Q, M_T, Σ_T)
98 µs ± 4.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
>>> %timeit -n 10000 _calculate_squared_distance_profile_parallel_inf(m, QT, μ_Q, σ_Q, M_T, 
Σ_T)
104 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
>>> %timeit -n 10000 _calculate_squared_distance_profile_parallel(m, QT, μ_Q, σ_Q, M_T, Σ_T)
78.9 µs ± 3.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

size = 1e6:
```
>>> %timeit -n 1000 _calculate_squared_distance_profile_numpy(m, QT, μ_Q, σ_Q, M_T, Σ_T)
6.89 ms ± 39.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n 1000 _calculate_squared_distance_profile_parallel_inf(m, QT, μ_Q, σ_Q, M_T, 
Σ_T)
6.93 ms ± 35.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n 1000 _calculate_squared_distance_profile_parallel(m, QT, μ_Q, σ_Q, M_T, Σ_T)
2.84 ms ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

size = 5e6:
```
>>> %timeit -n 1000 _calculate_squared_distance_profile_numpy(m, QT, μ_Q, σ_Q, M_T, Σ_T)
36.1 ms ± 46.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n 1000 _calculate_squared_distance_profile_parallel_inf(m, QT, μ_Q, σ_Q, M_T, 
Σ_T)
36.3 ms ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit -n 1000 _calculate_squared_distance_profile_parallel(m, QT, μ_Q, σ_Q, M_T, Σ_T)
16.7 ms ± 387 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

I precompiled all three functions before running the tests. All the time all of my four cores where used, because numba manages to parallelize the numpy code even without explicitly using `prange` if the `parallel=True` keyword is given. While `_calculate_squared_distance_profile_parallel` is around 2x faster than the other two, it will be incredibly slow if jitting is disabled. I don't see a reason for this in a real application though.

**Comment by JaKasb** [comment]
Never compare floating point numbers for exact equality.
`denom[denom == 0] = 1e-10  # Avoid divide by zero`
Because `1e-300 == 0.0` evaluates to `False`

Comparing floating point numbers is tricky, if the values are close to 0.0 
Even `numpy.isclose()` needs adjusted parameters for small magnitudes.

A float64 has a precision of 1e-15.
https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64

But if you already chose `1-e10` as the minimum-value, you could use
`denom = np.clip(denom, a_min=1e-10, a_max=None)`

Additional Information:
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

Further Reading (for masochists)
https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by seanlaw** [comment]
> I precompiled all three functions before running the tests. All the time all of my four cores where used, because numba manages to parallelize the numpy code even without explicitly using prange if the parallel=True keyword is given. While _calculate_squared_distance_profile_parallel is around 2x faster than the other two, it will be incredibly slow if jitting is disabled. I don't see a reason for this in a real application though.

@mexxexx This is excellent profiling! Thank you for taking the time to do it. 

If I'm reading this correctly, it looks like `_calculate_squared_distance_profile_numpy` and `_calculate_squared_distance_profile_parallel_inf` are basically the same and `_calculate_squared_distance_profile_parallel` is twice as fast but at the cost of significantly reduced readability. 

While speed is important, I tend to prefer readability since it will make it easier to manage in the long run. So, my vote is to choose `_calculate_squared_distance_profile_numpy` since it is the most readable and similar to the original. 

Something seems funny to me. Fundamentally, all three functions are parallel and it doesn't look like `_calculate_squared_distance_profile_parallel` isn't doing anything special. Maybe the speedup in `_calculate_squared_distance_profile_parallel` is coming from not having to perform a certain time consuming action that could also be avoided in the first/second function?

Ultimately, you are the user so you get a vote too 😄

**Comment by seanlaw** [comment]
> Never compare floating point numbers for exact equality.
denom[denom == 0] = 1e-10 # Avoid divide by zero
Because 1e-300 == 0.0 evaluates to False

Comparing floating point numbers is tricky, if the values are close to 0.0
Even numpy.isclose() needs adjusted parameters for small magnitudes.

@JaKasb Thanks for pointing this out. Would you mind submitting this as a new issue? It would be useful to incorporate this into the code.

**Comment by mexxexx** [comment]
> Something seems funny to me. Fundamentally, all three functions are parallel and it doesn't look like _calculate_squared_distance_profile_parallel isn't doing anything special. Maybe the speedup in _calculate_squared_distance_profile_parallel is coming from not having to perform a certain time consuming action that could also be avoided in the first/second function?

This might be the case, but a factor of two seems really high. I think I read somewhere that numba prefers loops, since this is how you would implement it in C, but I don't know.

> While speed is important, I tend to prefer readability since it will make it easier to manage in the long run. So, my vote is to choose _calculate_squared_distance_profile_numpy since it is the most readable and similar to the original.

I think we should profile stump as a whole. If most of the time is lost calculating the distance profile, then I would say that the speed improvement is worth it. I agree that the readability is a bit better in the numpy case, but if you think of the parallel function as being implemented in C, it does nothing to fancy and is still easily understandable.

**Comment by seanlaw** [comment]
> I think we should profile stump as a whole. If most of the time is lost calculating the distance profile, then I would say that the speed improvement is worth it. I agree that the readability is a bit better in the numpy case, but if you think of the parallel function as being implemented in C, it does nothing to fancy and is still easily understandable.

The more I stare at `_calculate_squared_distance_profile_parallel`, the more I feel comfortable with it. Considering that `_calculate_squared_distance_profile_parallel` is at the core of every matrix profile (CPU) calculation, it makes sense for it to be as optimized as possible. I am fairly convinced that it is significantly faster (usually, my threshold is 20% faster and this far exceeds it). Assuming that the tests all pass (along with any new test that you have), I say we go with `_calculate_squared_distance_profile_parallel`.

**Comment by mexxexx** [comment]
Ok! Should I add the notebook to the `docs` folder for future reference?

**Comment by seanlaw** [comment]
> Should I add the notebook to the docs folder for future reference?

@mexxexx Can you provide more detail as to what notebook are you referring to? Is it a tutorial or a notebook for profiling?

**Comment by mexxexx** [comment]
I mean the jupyter notebook I used for profiling the three functions.

**Comment by seanlaw** [comment]
> I mean the jupyter notebook I used for profiling the three functions.

I am indifferent. I trust you and leave that decision up to you. 👍

**Comment by mexxexx** [comment]
>  (because we now have a record of it above)

That is true. Nevertheless, I created a separate issue #140 for this, so we can find it easier in the future

**Comment by seanlaw** [comment]
> I created a separate issue #140 for this, so we can find it easier in the future

Perfect! I was thinking the same thing
