### ISSUE TITLE
Update MSTUMP/MSTUMPED Input Dimensionality Check

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#14]
Compared to STUMP, one may intuitively expect the behavior of MSTUMP when passing a multi-dimensional array into MSTUMP -- Currently, three 1D matrix profiles instead of a single matrix profile for the 3D data is returned. 

Realistically, STUMP should only accept a 1D array. I have no idea what happens when you pass a multi-dimensional array into STUMP.

It might make sense to check the shape of the input array and then simply:

- [x] Warn the user that they might want to use MSTUMP/MSTUMPED instead
- [x] Warn the user that only the first dimension is used and the rest is ignored
<s>- [ ] Only take the first dimension of the input array and use that to compute a 1D matrix profile using STUMP/STUMPED</s>

**Comment by marcusau** [comment]
I have tried multi-dimensional array to  mstump with stock prices and its technical indicators 

    #### step 2 : Feature creation
    df1=df.copy()

    df1['Close_pct']=np.log(df1['Close'] / df1['Close'].shift(1)).dropna()
    df1['STDDEV']= ta.STDDEV(df1['Close'], timeperiod=5, nbdev=1)
    ### Volume Indicator Functions
    df1['OBV']=ta.OBV(df1['Close'], df1['Volume'])
    df1['Chaikin AD'] = ta.AD(df1['High'], df1['Low'], df1['Close'], df1['Volume'])

    ### momentum Indicator

    macd, macdsignal, macdhist = ta.MACD(df1['Close'], fastperiod=12, slowperiod=26, signalperiod=9)
    df1['macdhist']=macdhist

    df1['RSI']= ta.RSI(df1['Close'], timeperiod=14)

    # Volatility Indicator Functions
    df1['NATR'] = ta.NATR(df1['High'], df1['Low'], df1['Close'], timeperiod=14)
    df1['TRANGE'] = ta.TRANGE(df1['High'], df1['Low'], df1['Close'])
    print(df1.tail())


    print(list(set(df.columns) ^ set(df1.columns)))

    feature_cols=list(set(df.columns) ^ set(df1.columns))
    df1=df1.loc[:,feature_cols].dropna()
    print(df1.head())


    #Store these values in the NumPy array for using in our models later:
    f_x=()
    for f in feature_cols:
      f_x += (df1[f].values.reshape(-1,1),)
    X = np.concatenate(f_x,axis=1)
    X=X.T
    print(X.shape)
    >>>> (8, 2429)
<img width="839" alt="Screenshot 2019-08-25 at 6 55 35 PM" src="https://user-images.githubusercontent.com/31444195/63648956-fc4e6380-c769-11e9-81c2-88d71f7a558c.png">


    window_size = 10  # Approximately, how many data points might be found in a pattern

    matrix_profile, matrix_profile_indices = stumpy.mstump(X, m=window_size)

    left_matrix_profile_index = matrix_profile[:, 2]
    right_matrix_profile_index = matrix_profile[:, 3]


as you said, mstumpy only support 1-D data, however, what is the explanation of the results in mstumpy?

**Comment by seanlaw** [comment]
@marcusau Can you please start a new issue for your specific question. This is issue is for adding docs/tutorial.
