### ISSUE TITLE
MSTUMP columnwise sort performance

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#143]
Some profiling showed that the current approach to the necessary column-wise sort in MSTUMP is far from efficient.

I tried `mstump` using the two different sorting techniques and I got the following results (`m=10`):
|   | `n=10000, d=5` | `n=50000, d=5` | `n=10000, d=20` | CPU usage |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| sort_numba | 69s  | 80s | 1741s |~390% |
| sort_numpy  | 9s | 49s | 268s |~210-220% |

I did a single run with every configuration, precompiled mstump and tried to leave my computer running without doing anything else. 

So while the numpy version does not parallelize well, it is still faster by a large margin. We should check if somehow the numpy sorting algorithm can be leveraged to numba, for example in parallel chunks.

_Originally posted by @mexxexx in https://github.com/TDAmeritrade/stumpy/issues/135#issuecomment-597058818_

**Comment by mexxexx** [comment]
That's a huge difference. According to the Numba documentation (and some conversations on their Gitter channel), it shouldn't be that slow. I've posted an issue on the [Numba Github issue tracker](https://github.com/numba/numba/issues/5373).

_Originally posted by @seanlaw in https://github.com/TDAmeritrade/stumpy/issues/135#issuecomment-597073220_

**Comment by mexxexx** [comment]
Another possible solution is to parallelize numpy directly using the `multiprocessing` library.

Below is a working example of a parallelized sorting. For the size of 20x1e8 I did not notice a speed difference between four and eight cores, even though all of them were used (1.2s per call vs 3.9s for single core).

```
import multiprocessing
import ctypes
import numpy as np

import time

shared_array = None
def sort_np(s):
    #shared_array[:,s].sort(axis=0) # Use this if you want sorting to actually happend
    np.sort(shared_array[:, s], axis=0)

def main():
    d = 20
    n = 10000000
    
    shared_array_base = multiprocessing.Array(ctypes.c_double, d*n)
    
    global shared_array
    shared_array = np.frombuffer(shared_array_base.get_obj())
    shared_array = shared_array.reshape(d, n)
    
    num_cores = 4
    pool = multiprocessing.Pool(num_cores)
    
    step = 1 + n // num_cores
    slices = [slice(step * i, step * (i+1)) for i in range(num_cores)]
    
    shared_array[:] = np.random.uniform(-100, 100, (d, n))
        
    num_reps = 10
    
    start = time.time()
    #for i in range(num_reps):
    #    np.sort(shared_array, axis=0)
    end = time.time()
    print("Sequential per rep: {}".format((end-start) / num_reps))
    
    start = time.time()
    for i in range(num_reps):
        pool.map(sort_np, slices)
    end = time.time()
    print("Parallel per rep: {}".format((end-start) / num_reps))
    
    
if __name__ == '__main__':
    main()
```

_Originally posted by @mexxexx in https://github.com/TDAmeritrade/stumpy/issues/135#issuecomment-597322379_

**Comment by seanlaw** [comment]
I wonder if this [sorting code](https://github.com/filemonmateus/sorting) would be helpful. 

Perhaps, @filemonmateus may be generous enough to help us with solving this or be willing to donate his code to our open source package (or assign a BSD3 license to his code).

**Comment by seanlaw** [comment]
@mexxexx I tried to do some more research to see if there was a simpler solution but, sadly, I couldn't find one. It looks like NumPy's mergesort (really C) is super efficient and it's just hard to replicate in Python/Numba.

**Comment by mexxexx** [comment]
Well there is still the possibility to just parallelize it using the common python tools.

**Comment by seanlaw** [comment]
> Well there is still the possibility to just parallelize it using the common python tools.

I am open to that. My only major question is what will happen when Dask is involved. Usually, Numba can get pickled pretty easily and processes clean up nicely. With multiprocessing, parent processes can die and child processes can get orphaned.

**Comment by mexxexx** [comment]
Sadly I don't know enough about dask to voice an opinion here... From what I understand each dask worker can have `num_processes` processes, i.e. it can run this number of threads in parallel. You are saying that if a worker dies, these processes can get orphaned?

**Comment by seanlaw** [comment]
> You are saying that if a worker dies, these processes can get orphaned?

Yes, exactly. But, honestly, I am totally open to testing it out using multiprocessing first (I can test it if you want to implement it). We could revert back if necessary.

**Comment by mexxexx** [comment]
Perfect, I'll try to implement it in the next days and submit a PR for you to try it out, you seem to have more knowledge of Dask than I do!

**Comment by mexxexx** [comment]
Okay, so the approach I posted above definitely works for `mstump`, although I cannot say anything about speed improvements.
However, it fails with `mstumped` because I cannot create subprocesses with `multithreading.Pool`: `AssertionError: daemonic processes are not allowed to have children`.

**Comment by seanlaw** [comment]
Hmm, I'm not sure why it says `multithreading.Pool` rather than `multiprocesssing`?

**Comment by mexxexx** [comment]
Sorry, that was my mistake, I meant `multiprocessing`. 
I know that is impossible for you to debug like this, I just wanted to say that it is not as easy as thought :smile:

**Comment by seanlaw** [comment]
Does that come about when you run the unit tests?

[I think that this may be related](https://github.com/dask/distributed/issues/2142)

**Comment by seanlaw** [comment]
@mexxexx If you want to create a function called `core._parallel_sort` and then, in `mstump.py`, replace the `np.sort` line with `core._parallel_sort` then, if it is indeed faster (and passes the original tests) then we can create a PR for that first.

Then, if you go into `mstumped.py` and add a comment on where/how you'd use `core._parallel_sort` then I can clone it and see if I can help figure it out. If it doesn't work then maybe we just accept the divergence
