### ISSUE TITLE
STUMPY Performance on Small Datasets

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#156]
User @codyschank had noticed that for [small datasets, `stumpy.stomp._stomp` is faster than `stumpy.stump`](https://github.com/TDAmeritrade/stumpy/issues/149#issuecomment-604171227). Here is some very rough timing calculations from my 2-core laptop:

```
    length       stomp       stump  stomp/stump   stump/stomp
0      128    0.006628    0.018066     0.366867      2.725782
1      256    0.013663    0.035015     0.390198      2.562803
2      512    0.030750    0.067728     0.454026      2.202518
3     1024    0.067139    0.139564     0.481063      2.078728
4     2048    0.142935    0.282102     0.506678      1.973639
5     4096    0.328754    0.592946     0.554442      1.803614
6     8192    0.825290    1.337432     0.617071      1.620560
7    16384    2.373994    2.943206     0.806601      1.239770
8    32768    7.598626    7.118338     1.067472      0.936793
9    65536   25.799881   21.424903     1.204201      0.830426
10  131072  104.186424   71.917796     1.448688      0.690280
11  262144  434.137795  273.057443     1.589914      0.628965
```

The first column is the length of the input time series, the second/third column are the elapsed time in seconds (run one time), and the fourth/fifth column are the timing ratios. We very clearly see that:

1. for small datasets (`length` smaller than `2**11 = 2048`), `stumpy.stomp._stomp` is around 2x faster
2. the breakeven point is somewhere between `length = 2**14 = 16384` and `length = 2**15 = 32768`
3. for datasets larger than about 100,000 datapoints, `stumpy.stump` is faster and that gap seems to increase as the data size increases

There may be an opportunity to provide a heuristic and have `stumpy.stump` call `stumpy.stomp._stomp` for datasets smaller than `2**15` and to call `stumpy._stump` otherwise. 

However, it would be important to:

1. change `test_stump.py` to test `stumpy._stump` directly and not to be testing `stumpy.stump` because, otherwise, we'd just be testing `stumpy.stump` which would be actually calling `stumpy.stomp._stomp`
2. Give the user the option (as an argument to `stumpy.stump`) to turn on/off `stumpy.stomp._stomp`
3. Remove the warning in `stumpy.stomp._stomp`

**Comment by seanlaw** [comment]
We should also refactor and consolidate the checking of input array(s)

**Comment by seanlaw** [comment]
Okay, I've been doing a little more digging/reading into the recent performance improvements for computing matrix profiles and it appears that [we are potentially leaving a lot of performance on the table based on these timing calculations on a single CPU core](https://github.com/TDAmeritrade/stumpy/issues/106#issuecomment-571888772). The only trick is to make all of this code maintainable and readable. The core of the performance improvement comes from the [SCAMP paper](https://www.cs.ucr.edu/~eamonn/public/GPU_Matrix_profile_VLDB_30DraftOnly.pdf)

@mexxexx I may need your help (again) with taking a look at the `np.nan`/`np.inf` once I have an implementation that I like. Do you think I can call upon you then? The API won't change as I'll just be replacing  the innards of `stumpy.stump` and, hopefully, the unit tests will pass.

**Comment by mexxexx** [comment]
Hi @seanlaw , of course, I'm eager to help!

I have some trouble understanding your timings. The timings for two CPUs in this thread is for stomp/stump, correct? And the timings in the thread you linked? Is it for scamp or also stump?

To be honest, I don't know if it is worth doing this trouble of it only benefits small data sets, because it really does not matter if you have to wait for one or two seconds I think. But maybe I misunderstood something :)

**Comment by seanlaw** [comment]
> I have some trouble understanding your timings. The timings for two CPUs in this thread is for stomp/stump, correct? 

Yes, this is correct.

> And the timings in the thread you linked? Is it for scamp or also stump? 

So, in my mental model, matrix profile started with the algorithms in the following order of speedup:

1. STAMP
2. STOMP  (GPU-STOMP is similar but this is basically what STUMP is based on)
3. STOMPopt - which is really cherry picking components from something called GPU-STOMPopt that would also work for CPUs. The key here is some interesting optimizations that make things significantly faster as it leverages a new way to compute the distance based on Pearson correlation (less computation, more numerically stable)
4. SCAMP - builds off of GPU-STOMPopt (or STOMPopt) and primarily targets GPUs and does some fancy tiling work and considers the use of single precision and is possibly an anytime algorithm.

The timings in the other ["SCAMP" issue](https://github.com/TDAmeritrade/stumpy/issues/106#issuecomment-571888772) is really Python code for "STOMPopt". But, to be 100% clear, the timing is for a single CPU core (notice that it does not leverage `numba.prange`. I've combined all three timings below but note that `stump` and `stomp` below are 2-core:

```
    length       stomp       stump   stomp_opt  stomp/stump  stump/stomp  stump/stomp_opt
0      128    0.006628    0.018066    0.000718     0.366867     2.725782        25.165824
1      256    0.013663    0.035015    0.001577     0.390198     2.562803        22.204952
2      512    0.030750    0.067728    0.005366     0.454026     2.202518        12.621488
3     1024    0.067139    0.139564    0.009947     0.481063     2.078728        14.031013
4     2048    0.142935    0.282102    0.031575     0.506678     1.973639         8.934357
5     4096    0.328754    0.592946    0.060295     0.554442     1.803614         9.834065
6     8192    0.825290    1.337432    0.171770     0.617071     1.620560         7.786164
7    16384    2.373994    2.943206    0.594898     0.806601     1.239770         4.947413
8    32768    7.598626    7.118338    2.359407     1.067472     0.936793         3.017003
9    65536   25.799881   21.424903    9.210498     1.204201     0.830426         2.326139
10  131072  104.186424   71.917796   39.090677     1.448688     0.690280         1.839768
11  262144  434.137795  273.057443  164.951866     1.589914     0.628965         1.655377
```

As you can see `stomp_opt` (with a single core) is around 66% faster than 2-core `stump`. And I haven't even tried optimizing the `stomp_opt` code yet or parallelized it. In the matrixprofile-ts package, this `stomp_opt`-like algorithm is currently implemented as the `mpx` algorithm but with Cython and it is really fast. So, I am optimistic that we'll likely see similar performance boost.

**Comment by seanlaw** [comment]
> To be honest, I don't know if it is worth doing this trouble of it only benefits small data sets, because it really does not matter if you have to wait for one or two seconds I think. But maybe I misunderstood something :)

Well, this is true if you are analyzing a single time series but in the other "phone call" case where they have thousands of time series with 2,000 data points (on average) and needing to perform an n x n pairwise comparison, then the time really adds up. In fact, according to the timing, it might be done in a matter minutes instead of hours.

**Comment by zpzim** [comment]
Hi Sean, sorry a bit of a late reply here. I was trying to convey this in our discussions in January, it is not just about small datasets, large datasets also have lots of performance left on the table here.

Has there been any progress here? Can I help clarify anything?

**Comment by zpzim** [comment]
I found out you already have some work done on this, seems like you have things under control.
