### ISSUE TITLE
Computing Matrix Profile with Non-normalized Euclidean Distance

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#157]
[Here is a paper](https://arxiv.org/abs/1901.05708) that claims to compute a matrix profile with non-normalized Euclidean distances

This may be of some interest to users

**Comment by tylerwmarrs** [comment]
I spent a lot of time trying to get good results from this research working with the authors to implement the algorithms without success. Adding these algorithms into your library would be more or less toy/experimental features as they tend to disagree with UCR algorithms causing confusion. Another member at MPF, Francisco Bischoff, attempted to implement the research as well without success. Here is a blog post I wrote earlier last year that may give you more insight. https://tylermarrs.com/posts/aamp-matrix-profile/

Cheers.

**Comment by seanlaw** [comment]
Thanks for the heads up @tylerwmarrs! This will save us some time and effort
