### ISSUE TITLE
Refactor SCRIMP

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#158]
In 0efc3992f4ea57f028babca4a4f91139c41d560f, we refactored and updated the way that the distance profile was calculated so that we would only need to make changes in a single place. However, SCRIMP is still currently using its own distance profile calculation:

https://github.com/TDAmeritrade/stumpy/blob/master/stumpy/scrimp.py#L81-L91

```
for order in prange(orders.shape[0]):
        if n_dist_computed / (l * l) > percentage:  # pragma: no cover
            break
        k = orders[order]
        for i in range(0, n - m + 2 - k):
            if i == 0:
                QT = np.dot(T[i : i + m], T[i + k - 1 : i + k - 1 + m])
            else:
                QT = QT - T[i - 1] * T[i + k - 2] + T[i + m - 1] * T[i + k + m - 2]

            denom = m * σ[i] * σ[i + k - 1]
            if denom == 0:
                denom = 1e-10  # Avoid divide by zero
            D = np.sqrt(np.abs(2 * m * (1.0 - (QT - m * μ[i] * μ[i + k - 1]) / denom)))
            threshold = 1e-7
            if σ[i] < threshold:  # pragma: no cover
                D = np.sqrt(m)
            if σ[i + k - 1] < threshold:  # pragma: no cover
                D = np.sqrt(m)
            if σ[i] < threshold and σ[i + k - 1] < threshold:
                D = 0
```

I've tried replacing the core lines:

```
    denom = m * σ[i] * σ[i + k - 1]
            if denom == 0:
                denom = 1e-10  # Avoid divide by zero
            D = np.sqrt(np.abs(2 * m * (1.0 - (QT - m * μ[i] * μ[i + k - 1]) / denom)))
            threshold = 1e-7
            if σ[i] < threshold:  # pragma: no cover
                D = np.sqrt(m)
            if σ[i + k - 1] < threshold:  # pragma: no cover
                D = np.sqrt(m)
            if σ[i] < threshold and σ[i + k - 1] < threshold:
                D = 0
```

 but, unfortunately, these calculations are scalar values while `calculate_distance_profile` operates on NumPy vectors. It ins't clear how best to update `calculate_distance_profile` or `_calculate_squared_distance_profile` so that we can also accommodate this input as well.

**Comment by seanlaw** [comment]
@mexxexx Any ideas?  I'd like to keep it all within one function instead of having a separate function for scalars

**Comment by mexxexx** [comment]
I'm not entirely sure but wouldn't something like this work?:

```
QT = np.empty(1, dtype=float)
for order in prange(orders.shape[0]):
        if n_dist_computed / (l * l) > percentage:  # pragma: no cover
            break
        k = orders[order]
        for i in range(0, n - m + 2 - k):
            if i == 0:
                QT[0] = np.dot(T[i : i + m], T[i + k - 1 : i + k - 1 + m])
            else:
                QT[0] = QT[0] - T[i - 1] * T[i + k - 2] + T[i + m - 1] * T[i + k + m - 2]

        core._calculate_squared_distance_profile(m, QT, μ[i], [i], μ[i + k - 1, np.newaxis], σ[i + k - 1, np.newaxis]):
```

**Comment by seanlaw** [comment]
Thanks for the suggestion. Sadly, `np.newaxis` isn't supported by Numba yet. I'll have to play with things a little more but I think I'm close to a solution.

**Comment by seanlaw** [comment]
Alright, I was able to further refactor the calculation of the squared distance profile so that it now calls another function that handles computing a single squared distance (not a profile, just scalar inputs with scalar outputs)
