### ISSUE TITLE
MEXXEXX DM

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#163]
@mexxexx [said](https://github.com/TDAmeritrade/stumpy/issues/112#issuecomment-619268074):

> However, if you feel like you need support please feel free to ask, I'd like to help add some new functionality.

**Comment by seanlaw** [comment]
@mexxexx I’ve really enjoyed working with you and I can certainly use and welcome your help! 

Depending on your availability, I could definitely use some help:

- adding new tutorials 
- maintaining NaN/inf code (and adding it to new code) as I still get confused when I don’t touch it in a while
- completing existing issues (or breaking them into smaller ones so you feel more comfortable contributing)
- basically anything that you’d be interested in 😊

My goal for STUMPY over the next while will not be to add features. Instead, I would like to focus on making the computation of the matrix profile rock solid and consistent across the code base. Essentially, I want to continue to strengthen the current foundation so that others can build off of it in the future.

Your assistance would be greatly appreciated!

**Comment by mexxexx** [comment]
Hi! I think its a good approach to really have the current functionality working and adding tutorials.

I can definitely assist in maintaining NaN and inf values, also I can look at it for scrimp, once you have restructured the code. Also for the other issues of course, but it is always a bit difficult to completely understand a new topic.

**Comment by seanlaw** [comment]
Awesome! Btw, I was able to add NaN/inf support to SCRIMP and all unit tests by following what you had done with `stumpy.stump`. It was rather painless thanks to your earlier work!

In fact, I converted SCRIMP into a generator so that one can quickly and easily iterate and incrementally (and randomly) update the matrix profile. The next step is to add preSCRIMP (and then we can release SCRIMP++ as a new feature).

After that, I’d like to add NaN/inf support to GPU_STUMP and then focus on adding tutorials. Again, you are welcome to take on any of this stuff and I will support you where you need me to! So don’t feel like you are going at it alone.

**Comment by seanlaw** [comment]
Now that I have SCRIMP (not preSCRIMP and SCRIMP++) completed, I have learned a lot about how to traverse the matrix across the diagonals (instead of row-wise). Indeed `stumpy.scrimp` is about the same speed (for self-joins) as `stumpy.stump`. Additionally, I have discovered a lot about how to parallel program using Numba’s `prange` when you don’t have direct access to each thread and so this will come in handy later.

The diagonal processing is fundamental to improving the speed but the further more significant speed up (and added numerical stability) comes from the new way to compute the pairwise distances using correlation/covariance. From my rough estimates, this is about a 5x speedup but it’ll be worth profiling. I think this is one place that you might be able to help and that you may find interesting.

**Comment by seanlaw** [comment]
> Also for the other issues of course, but it is always a bit difficult to completely understand a new topic.

I don’t dispute this but, since I trust you, I also don’t think that it is bad to add individual byte sized functions (or even isolated modules) to the code base that is based on the algorithms/pseudocode from an existing paper. I think SCRIMP in its current form is a good example of this where I started a module and it was a single function with tests. Then I slowly added parallelization and finally NaN/inf support. Eventually, we’ll have preSCRIMP and then SCRIMP++ will be done. But SCRIMP is the foundation. While we obviously want to avoid starting 10 things at the same time, I think it’s okay to have some “work in progress” code as long as there are unit tests to go along with it. I don’t consider a function to be “public” until it is added our docs (and I’d prefer having a tutorial over that). I have been known to start a module with tests and commit it and then decided to redesign it because I figured out a better way. No big deal.

I see something similar with the noisy data issue. Personally, I would add the distance calculation first (along with appropriate tests), assume that the choice is boolean for now, and then eventually add a threshold/float/array. I’ll try not to get into the weeds here with this one but hopefully you get my point that we can iterate together.

**Comment by mexxexx** [comment]
> Awesome! Btw, I was able to add NaN/inf support to SCRIMP and all unit tests by following what you had done with stumpy.stump. It was rather painless thanks to your earlier work!

Great, I'm happy to hear this!

> In fact, I converted SCRIMP into a generator so that one can quickly and easily iterate and incrementally (and randomly) update the matrix profile. The next step is to add preSCRIMP (and then we can release SCRIMP++ as a new feature).

Cool! If you want, we can work on this together, e.g. I can doublecheck anything you propose. I found the paper rather confusing, so I'm not sure if I could implement prescrimp myself.

> After that, I’d like to add NaN/inf support to GPU_STUMP and then focus on adding tutorials. Again, you are welcome to take on any of this stuff and I will support you where you need me to! So don’t feel like you are going at it alone.

I can write a tutorial on how to use scrimp if you want. I dont have a GPU so I cannot help with this part.

**Comment by mexxexx** [comment]
> Now that I have SCRIMP (not preSCRIMP and SCRIMP++) completed, I have learned a lot about how to traverse the matrix across the diagonals (instead of row-wise). Indeed stumpy.scrimp is about the same speed (for self-joins) as stumpy.stump. Additionally, I have discovered a lot about how to parallel program using Numba’s prange when you don’t have direct access to each thread and so this will come in handy later.

That is good, I also think that implementing algorithms is a great way to learn a language/specifics.

> The diagonal processing is fundamental to improving the speed but the more significant speed up (and added numerical stability) comes from the new way to compute the pairwise distances using correlation/covariance. From my rough estimates, this is about a 5x speedup but it’ll be worth profiling. I think this is one place that you might be able to help and that you may find interesting.

Definitely, you just have to clarify what you mean exacltly, maybe in a separate issue.

**Comment by seanlaw** [comment]
@mexxexx Here are some links:

[Google Colab GPUs](https://tiny.cc/stumpy_colab)
[Suffix Array Library](https://github.com/louisabraham/pydivsufsort)
[Suffix Array YouTube Playlist](https://www.youtube.com/watch?v=zqKlL3ZpTqs&list=PLDV1Zeh2NRsCQ_Educ7GCNs3mvzpXhHW5)

**Comment by mexxexx** [comment]
So about definition 13 in the mstomp profile: for the multidimensional profile you sort the distance profiles column wise, and by this lose the information in which order the distances where combined (i.e. for the two dimensional distance profile the two lowest distances are averaged, but if we have more than two dimensions in our time series, we lose the information about which dimensions played a role here). So the idea of Def 13 is to keep track of it with something called the matrix profile subspace. 

Say that you have a three dimensional series and compute the following distances

```
[1, 2, 3]
[2, 3, 1]
[1, 3, 2]
```

Then, after sorting you get
```
[10, 20, 10]
[10, 30, 20]
[20, 30, 30]
```
And averaging (`D_prime_prime`)
```
[10, 20, 10]
[10, 2.5, 15]
[16.6, 26.6, 20]
```
So for this query the profile would be `[10, 10, 16.6]`. Now, if you want to find the closest subsequence in two dimensions, how do you know in which dimensions you have to look? You know that the closest distance is 10, but is it in dimensions (1,2), (2,3) or (1,3)?

For our example the MP subspace would be (the column wise sort order9
```
[1, 1, 2]
[3, 2, 3]
[2, 3, 1]
```
Hence, as the MP value of 10 os at index zero, we know that for two dimensions we have to look at dimensions (1,3) combined.

**Comment by mexxexx** [comment]
This isn't the greatest explanation, but maybe it gives a hint of why we need this information.

**Comment by seanlaw** [comment]
Okay, thank you. This rings a bell.  So, it sounds like we'd need to replace the `D.sort(axis=0)` with `sorted_idx = np.argsort(D, axis=0)`, then store the indices that are associated with each number of dimensions, and then do `D = D[sorted_idx]`.  I vaguely remember this when I first implemented `mstump` and I avoided the subspace stuff because I couldn't come up with a good way to store this information inside of a NumPy array. I think that once we can figure the output then the rest shouldn't be too hard (as you pointed out).

Thanks for explaining it!

**Comment by seanlaw** [comment]
Okay, it's not the best option but apparently you can do:

```
import numpy as np
subspace = np.ones((5, 10), dtype=np.ndarray) * -1
subspace[2, 0] = np.array([2, 4, 1])
```

which gives:

```
array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [array([2, 4, 1]), -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]], dtype=object)
```

**Comment by mexxexx** [comment]
Wouldn't it be enough to return the results of `argsort`? In the example above we had the distance profile (`D_prime_prime`)
```
[10, 20, 10]
[10, 2.5, 15]
[16.6, 26.6, 20]
```
and the `argsort` results would be

```
[1, 1, 2]
[3, 2, 3]
[2, 3, 1]
```

So for the multidimensional profile, we look in each dimension for the lowest index (the matrix profile indices) and find `[0, 0, 0]` to be the indices for the given query. So we would have the matrix profile value (`P`) `[10, 10, 16.6]` and the matrix profile subspace (`S`?) `[1, 3, 2]`.

So, if we take this same query, we would know that the lowest distance if we include two dimensions will be `10` (`P[1]`) and to get this value we must average the distance profiles of dimension `1` and `3` (`S[:1]`).

This means for each index the matrix profile subspace is a `d` dimensional array (as are the matrix profile and matrix profile indices) and we have `n-m+1` indices, so `S` has to be a numpy array of shape `(d, n-m+1)`.

**Comment by seanlaw** [comment]
Of course! Thank you for saving me from overcomplicating things 😭

I've opened issue #188 for this.

**Comment by seanlaw** [comment]
@mexxexx STUMPY 1.4.0 is now live. Thanks again for all of your contributions! This was a really, really great one.

**Comment by mexxexx** [comment]
That is great! You're welcome!

I'm sorry I didn't have much time to work on the motif discovery module lately, hopefully it will be something for the next release.

**Comment by seanlaw** [comment]
@mexxexx Regarding [your question about setting the mean to zero and stddev to one](https://github.com/TDAmeritrade/stumpy/issues/207#issuecomment-657208503), I play around with it a little but I'm sure that I'm missing something. In `stumpy.stump`, I follow the `core.preprocessing` steps by explicitly setting:

```
T_A, M_T, Σ_T = core.preprocess(T_A, m)
T_B, μ_Q, σ_Q = core.preprocess(T_B, m)

M_T[~np.isnan(M_T)] = 0
Σ_T[~np.isnan(Σ_T)] = 1
μ_Q[~np.isnan(μ_Q)] = 0
σ_Q[~np.isnan(σ_Q)] = 1
```

This did not produce the same answer as my `aamp`/`naive_aamp` implementations. Then, I realized that `stumpy.stump` calls `_get_first_stump_profile`, which ultimately calls `core.mass`. Internally, `core.mass` re-computes `μ_Q` and `σ_Q` for the first subsequence window, which can have a snowball effect on the rest of the distance calculations. So, in `core.mass` tried to explicitly set:

```
QT = sliding_dot_product(Q, T)
μ_Q, σ_Q = compute_mean_std(Q, m)
μ_Q = μ_Q[0]
σ_Q = σ_Q[0]
μ_Q = 0
σ_Q = 1
distance_profile[:] = _mass(Q, T, QT, μ_Q, σ_Q, M_T, Σ_T)
```

Again, the final matrix profile did not match that of `aamp`/`naive_aamp`. I learned two things from this exercise:

1. I'm definitely missing something. In theory, this should work and, because it doesn't, there must be another place where the mean/stddev are being recomputed that I'm not accounting for
2. Trying to incorporate non-normalized Euclidean distance into the z-normalized code is making things look unnecessarily complex (I understand that this was to satisfy your curiosity and, frankly, mine too). Additionally, I asked the original author (Keogh) about non-normalized Euclidean distance and he advises against it saying that "none of the published papers on this topic actually point out where non-normalized Euclidean distance is actually helpful" (paraphrased).

I will likely leave the `aamp` code in STUMPY (strictly for reference like `stumpy.stomp`) but not add it to our API documentation.

**Comment by mexxexx** [comment]
That is indeed strange, but I also have no idea what could cause the discrepancy. Maybe changing in directly in `calculate_squared_distance_profile` might work...

But I agree, I wouldn't mix it into the existing code. I only thought that it might be a cool thing to be able to call for example stump like this: `stump(T, m, M_T, Σ_T)` and by doing so skipping the preprocessing step we are doing. 

I don't know about Keoghs opinion, because I think there are some usecases where the scale of the motif does indeed play an important role. But for now, its probably best to leave it out, until more people request the feature.

**Comment by seanlaw** [comment]
> That is indeed strange, but I also have no idea what could cause the discrepancy. Maybe changing in directly in calculate_squared_distance_profile might work...

I just tried this and it still produces different results from `aamp` 🤷‍♂️ 

FYI, I think I'm just about ready to work on the performance improvements. If you are interested, it is based on [Section 3.3 of this paper](https://www.cs.ucr.edu/~eamonn/public/GPU_Matrix_profile_VLDB_30DraftOnly.pdf). Essentially, (starting with SCRIMP's diagonal traversal), they (Keogh's group) have replaced the original sliding dot product with a much more stable and performant "centered sum-of-products" formula. To do this, they've resorted to computing the z-normalized Euclidean distance using the Pearson correlation (there's a direct relationship) and then, since correlation depends on the covariance (which requires less computation), they've optimized the computation of the Pearson correlation. To put it simply, you traverse along a diagonal and you compute the current correlation relative to the last correlation along the diagonal using a fast incremental approach. This depends on an old "trick" by Welford.

I've derived the primary matrix profile equations [here](https://nbviewer.jupyter.org/github/TDAmeritrade/stumpy/blob/master/docs/Matrix_Profile_Derivation.ipynb) and provide a review/derivation of Welford's work [here](https://nbviewer.jupyter.org/github/TDAmeritrade/stumpy/blob/master/docs/Welford_Review.ipynb?flush_cache=false). You mentioned that you like to learn new things so I thought this might be interesting to you.

**Comment by mexxexx** [comment]
Thank you!

By the way, I think the answer to why just changing standard deviation and mean to 1 and 0 lies in the same document, because there are some assumptions made in serving the formula `2m(1-QT...)`, namely that the Euclidean norm of a z normalized subsequence is `m^2`, which is not the case for the unnormalized one. Maybe you understand what I try to say, I can't really pinpoint at what point it goes wrong :smile:

**Comment by seanlaw** [comment]
Sorry, I don't follow your meaning 😅

**Comment by mexxexx** [comment]
I think what I tried to say is the following: While
```
dist_znorm(A, B)^2 = 2 * m (1 - (A*B - m * mu_A * mu_B) / (m * σ_A * σ_B))
```
is valid, but

```
dist_euclidean(A, B)^2 = 2 * m (1 - (A*B - m) / (m))
```
is not. So you compute a wrong distance (or better said, not the euclidean distance) if you just pass `mu=0` and `σ=1`.

**Comment by seanlaw** [comment]
> FYI, I think I'm just about ready to work on the performance improvements. If you are interested, it is based on Section 3.3 of this paper. Essentially, (starting with SCRIMP's diagonal traversal), they (Keogh's group) have replaced the original sliding dot product with a much more stable and performant "centered sum-of-products" formula. To do this, they've resorted to computing the z-normalized Euclidean distance using the Pearson correlation (there's a direct relationship) and then, since correlation depends on the covariance (which requires less computation), they've optimized the computation of the Pearson correlation. To put it simply, you traverse along a diagonal and you compute the current correlation relative to the last correlation along the diagonal using a fast incremental approach. This depends on an old "trick" by Welford.

> I've derived the primary matrix profile equations here and provide a review/derivation of Welford's work here. You mentioned that you like to learn new things so I thought this might be interesting to you.

@mexxexx I got this working now for CPUs! It's really, really fast and produces the same results as `stumpy.stump`. I'm looking to see if there are other places where we could shave off a little bit more time. I still need to support NaN/Inf though, write tests, and update the code base to use Pearson correlation

**Comment by zpzim** [comment]
@mexxexx I appreciate you helping Sean implement GPU-STOMPopt/SCAMP. By the way SCRIMP came AFTER the diagonal update method you are using.

@seanlaw  Can you please cite SCAMP [paper](https://dl.acm.org/doi/abs/10.1145/3357223.3362721) and [source code](https://github.com/zpzim/SCAMP) in your repo when you start using the updated formula? Thanks!

Also if you update the performance charts, please include a fair comparison to SCAMP.
