### ISSUE TITLE
Add SCRIMP++ Tutorial

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#165]
Now that SCRIMP++ (for self-joins) has been implemented, it would be nice to have a blog that reproduces a figure from the paper.

**Comment by mexxexx** [comment]
Do you have any figure in particular in mind or would a demo on e.g. a random walk be good?

**Comment by seanlaw** [comment]
From [this paper](https://www.cs.ucr.edu/~eamonn/SCRIMP_ICDM_camera_ready_updated.pdf), I was hoping to reproduce Fig 9 or Fig 11 or Fig 12 as they all use the same data. Unfortunately, I can't get the author to provide the data.

So, we may need to just do what of the random walk ones (assuming that it is "interesting enough). If it's boring, then we could find another example. What do you think?

**Comment by seanlaw** [comment]
@mexxexx Has crafted a nice tutorial in PR #167

**Comment by seanlaw** [comment]
I'll need to make some edits to the tutorial, add the Tutorial to the docs, and added the function to the API but it shouldn't take much effort as you've done most of the heavy lifting.
