### ISSUE TITLE
Handling NaN/Inf in core.mass and stamp.mass

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#166]
In [this comment](https://github.com/TDAmeritrade/stumpy/issues/149#issuecomment-625534271) a user is trying to use `core.mass` (or `stamp.mass`) to compute a distance profile but their data contains `np.nan/np.inf`. Currently, `nan/inf` handling is handled at a higher abstraction level (which is fine) but it would be beneficial to allow `core.mass`/`stamp.mass` to automatically handle `nan/inf` since these functions will inevitably be called upon when finding matches to a single known pattern/motif.

**Comment by seanlaw** [comment]
@mexxexx Taking a look at the previous comment above, can you think of a way where the user can easily use `core.mass` or `stamp.mass` directly with data that contains `np.nan/np.inf` without having to manually perform the pre-processing step themselves? Right now, you'd have to do something like:

```
T = np.random.rand(1000)
m = 50

# Some pre-processing steps that is usually handled by `stumpy.stump` but you need to do this manually
T_copy = T.copy()  # Leave original time series unchanged
T_copy[np.isinf(T_copy)] = np.nan
M_T, Σ_T = core.compute_mean_std(T_copy, m)
T_copy[np.isnan(T_copy)] = 0
zone = excl_zone = int(np.ceil(m / 4))

# You compute the matrix profile and find a motif at `i = 10`
Q = T_copy[10: 10 + m]
P, I = stamp.mass(Q, T_copy, M_T, Σ_T, trivial_idx=10, excl_zone=zone)
```

There are several issues that one would need to solved:

1. Making a copy of `T` so as not to overwrite the original time series
2. Convert all `inf` to `nan` before computing the sliding window mean and standard deviation
3. Convert `nan` to zero before calling `core.mass` or `stamp.mass`

Do you have any thoughts?

**Comment by mexxexx** [comment]
There is some nan inf handling in `core.mass`, so it might be possible to do all this work there. We would need to have a look where core.mass is called and of this would lead to any conflicts, but from the first glance it should be fine.

If the query contains nans, an infinite distance profile is returned, so there should be no problem doing the same if the query contains infs. And if there are nans in the time series, they should be handled correctly too, so just adding some more checks shouldn't be a problem.

**Comment by mexxexx** [comment]
I think in general there should be only one mass function public to the user, and I would choose core.mass, because no exclusion zone is applied there and if you only want the distance profile you probably don't need the exclusion zone anyways.

**Comment by seanlaw** [comment]
@codyschank Would you mind supplying us with a small/short example `Q` and `T` pair that fails with `core.mass`? This would help us test and improve the code. Thanks in advance!

**Comment by seanlaw** [comment]
> I think in general there should be only one mass function public to the user, and I would choose core.mass, because no exclusion zone is applied there and if you only want the distance profile you probably don't need the exclusion zone anyways.

I agree with you. Do you feel like `stamp.mass` is doing too much?

**Comment by mexxexx** [comment]
I don't think it's doing to much, but maybe we should think about remaining it to capture that it is actually computing a single matrix profile value based on the distance profile. If I remember correctly the authors call only the calculation of the distance profile MASS.

**Comment by seanlaw** [comment]
Ahh, you're right. I totally forgot that `stamp.mass` only returns single matrix profile and single matrix profile index. We should probably update the documentation to reflect this. Right now, it says that an `ndarray` is returned by `P` is probably just a float while `I` can include the left/right indices.

**Comment by seanlaw** [comment]
> maybe we should think about remaining it to capture that it is actually computing a single matrix profile value based on the distance profile

Okay, I am assuming you mean "renaming it" and I think that's a good idea. What should we rename it to?

> If I remember correctly the authors call only the calculation of the distance profile MASS.

Yes, I think you're right!

**Comment by mexxexx** [comment]
> Okay, I am assuming you mean "renaming it" and I think that's a good idea. What should we rename it to?

Maybe something like `_calculate_matrix_profile_value`? Also, the docstring has to be update to explain better what the function in doing.

**Comment by seanlaw** [comment]
> Maybe something like _calculate_matrix_profile_value? Also, the docstring has to be update to explain better what the function in doing.

How would you feel about `stamp.mass_PI`?  I think it captures the fact that it is using the `mass` algorithm to compute the distance profile (and not a different algo) and then return the `P` and `I`.  If you are agreeable then I can go ahead and change this.

**Comment by mexxexx** [comment]
That works. Maybe make the function private?

**Comment by seanlaw** [comment]
> Maybe make the function private?

Hmmm, it almost feels like we need two functions. One for `stamp._mass_PI` that returns `P` and `I` and possibly another one `stamp.mass` that returns the distance profile but with the exclusion zone set to inf

**Comment by mexxexx** [comment]
I agree, that makes sense.

**Comment by seanlaw** [comment]
> There is some nan inf handling in core.mass, so it might be possible to do all this work there. We would need to have a look where core.mass is called and of this would lead to any conflicts, but from the first glance it should be fine.

> If the query contains nans, an infinite distance profile is returned, so there should be no problem doing the same if the query contains infs. And if there are nans in the time series, they should be handled correctly too, so just adding some more checks shouldn't be a problem.

@mexxexx Do you think you could provide a checklist on the steps that you think are necessary to get this to work? And then, I could try to take a stab at it and report back if I encounter any challenges

**Comment by JaKasb** [comment]
In `core.sliding_dot_product()`
https://github.com/TDAmeritrade/stumpy/blob/bc5b81c99aea6e43544432404eb0b483b199235e/stumpy/core.py#L756

FFT based convolution fails, if a single entry is `NaN` or `inf`
Direct convolution works, but is slower than fftconvolve

> import numpy as np
> from scipy.signal import convolve, fftconvolve, oaconvolve
> a = np.random.rand(1024)
> b = np.random.rand(1024)
> b[1] = np.nan
> 
> convolve(a,b, method='direct')
> np.convolve(a,b)
> 
> oaconvolve(a,b) 
> fftconvolve(a,b)

> array([0.06525139,        nan,        nan, ..., 0.6020596 , 0.35588406,
>        0.16277495])
> 
> array([0.06525139,        nan,        nan, ..., 0.6020596 , 0.35588406,
>        0.16277495])
> 

> array([nan, nan, nan, ..., nan, nan, nan])
> 
> array([nan, nan, nan, ..., nan, nan, nan])

**Comment by seanlaw** [comment]
@JaKasb Thanks for pointing this out! Would it be sufficient to update `core.sliding_dot_product()` to:

```
def sliding_dot_product(Q, T):
    n = T.shape[0]
    m = Q.shape[0]
    if np.any(np.isnan(Q)) or np.any(np.isinf(Q)) or np.any(np.isnan(T)) or np.any(np.isinf(T)):
        out = np.convolve(Q, T)
    else:
        Qr = np.flipud(Q)  # Reverse/flip Q
        QT = convolution(Qr, T)
        out = QT.real[m - 1 : n]

return out
```

**Comment by JaKasb** [comment]
I would write it as:
```
Qr = np.flipud(Q)  # Reverse/flip Q
if np.all(np.isfinite(Q)) and np.all(np.isfinite(T)):
    QT = scipy.signal.convolve(Qr, T, mode='???',  method='auto')
    # QT = scipy.signal.oaconvolve(Qr, T, mode='???')
else:
    QT = scipy.signal.convolve(Qr, T, mode='???', method='direct')
out = QT[m - 1 : n]
```
I dont understand why `np.convolve` operates on `Q` instead of `Qr` ?
I am not shure which `mode` to use in the convolution for the correct padding...
AFAIK `scipy.signal.convolve` returns real numbers for real-valued inputs. No need to access `QT.real`

By calling `scipy.signal.convolve` directly, one can remove the global variable `convolution`.
https://github.com/TDAmeritrade/stumpy/blob/bc5b81c99aea6e43544432404eb0b483b199235e/stumpy/core.py#L756
The variable `convolution` is only used in `sliding_dot_product`.


Making `sliding_dot_product` compatible with NaN is not enough for computing the Matrix Profile.
In the row-wise minimum-reduction, the comparison must also be NaN aware.
```
np.nan > 0 -> False 
np.nan < 0 -> False
```
In my projects I use a test:
`assert np.any(np.isfinite(distances))`

BONUS:
Mueen's MASS v3 uses overlap-add, overlap-save for convolution.
Overlap Convolution is faster if one array much smaller than the other array.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.oaconvolve.html#scipy.signal.oaconvolve

Regarding the high-level API:
MASS is used to re-identify known patterns.
I use MASS to spot occurences of known motifs.
`core.mass` is more than just a private helper function to me.

**Comment by seanlaw** [comment]
> I dont understand why np.convolve operates on Q instead of Qr ?

Oops, you're right. It should be `np.convolve` on `Qr` and not `Q`

> By calling scipy.signal.convolve directly, one can remove the global variable convolution.

There are two reasons for this:

1. We wanted to make sure that we were following the notation from the original paper
2. We had originally considered using PyFFTW, np.convolve, or scipy.signal.fftconvolve and so we opted to abstract this part out but, in hindsight, we could call the function(s) directly now that only one function needs a convolution

**Comment by seanlaw** [comment]
> The variable convolution is only used in sliding_dot_product.
Making sliding_dot_product compatible with NaN is not enough for computing the Matrix Profile.
In the row-wise minimum-reduction, the comparison must also be NaN aware.

> np.nan > 0 -> False 
> np.nan < 0 -> False
> In my projects I use a test:
> assert np.any(np.isfinite(distances))

@JaKasb I don't follow what is happening here. Would you mind elaborating? My data doesn't contain `NaN` so your experience and insight would be greatly valuable here.  

Would you care to submit a PR to fix this current issue in a general way?

> Regarding the high-level API:
MASS is used to re-identify known patterns.
I use MASS to spot occurences of known motifs.
core.mass is more than just a private helper function to me.

This is precisely what this current issue is trying to address. From what I can tell, in order to find other occurrences of known motifs (i.e., identified via `stump`), one would have to do something like:

```
T = np.random.rand(1000)
m = 50

# Some pre-processing steps that is usually handled by `stumpy.stump` but you need to do this manually
T_copy = T.copy()  # Leave original time series unchanged
T_copy[np.isinf(T_copy)] = np.nan
M_T, Σ_T = core.compute_mean_std(T_copy, m)
T_copy[np.isnan(T_copy)] = 0
zone = excl_zone = int(np.ceil(m / 4))

# You compute the matrix profile, say, using `stumpy.stump` and find a motif at `i = 10`
motif_idx = 10
Q = T_copy[motif_idx: motif_idx + m]
distance_profile = core.mass(Q, T_copy, M_T, Σ_T)
zone_start = max(0, trivial_idx - excl_zone)
zone_stop = min(T.shape[0] - Q.shape[0] + 1, trivial_idx + excl_zone)
distance_profile[zone_start : zone_stop + 1] = np.inf

# Use `distance_profile` to locate motifs within some threshold
```

@JaKasb Is this what you do? It would be wonderful and helpful to others if you could confirm/modify any steps that I may have missed.

**Comment by mexxexx** [comment]
What do you think of having a separate module called `motifs.py` where we have an implementation of the k-top-motif search?

> Do you think you could provide a checklist on the steps that you think are necessary to get this to work?

I would suggest the following: 
* Leave core.mass as it is, because 8t does exactly what MASS was made for, i.e. finding the distance profile of a query. 
* Rename stump.mass like you proposed
* In motifs.py have a function `find_occurences` (or something different) that does the following:
1. Gets a query Q, time series T and optionally the index of Q in T and an exclusion zone.
2. Replaces nan/inf in a copy of T and computes mean and stddev (basically does all the usual preprocessing)
3. Computes the distance profile of Q and T (the modified version) using core.mass
4. Returns all indices below a threshold
* Then around this function (and by doing some caching, as to not do the preprocessing of T every time) one cans build a k motif search implementation.

**Comment by mexxexx** [comment]
And maybe we can have a core.preprocessing function, that takes T, m and returns Tnew, meanT, sigmaT, that does all the nan/inf handling. Then we can replace redundant code in all the stump and stomp functions, and if a user wants to compute a distance profile of a time series containing nans he would do
```
Tnew, meanT, sigmaT = stumpy.core.preprocessing(T, m)
Distances = stumpy.core.mass(Q, Tnew, meanT, sigmaT)
```

**Comment by mexxexx** [comment]
Or even better, if no mean and sigma of T are provided to core.mass (they are optional and computes if not passed), automatically call the preprocessing function first.

**Comment by seanlaw** [comment]
> What do you think of having a separate module called motifs.py where we have an implementation of the k-top-motif search?

I think this is a great idea as it really addresses the core issue which is users are trying to use mass to find patterns/motifs

> I would suggest the following:
Leave core.mass as it is, because 8t does exactly what MASS was made for, i.e. finding the distance profile of a query.
Rename stump.mass like you proposed
In motifs.py have a function find_occurences (or something different) that does the following:
Gets a query Q, time series T and optionally the index of Q in T and an exclusion zone.
Replaces nan/inf in a copy of T and computes mean and stddev (basically does all the usual preprocessing)
Computes the distance profile of Q and T (the modified version) using core.mass, and if provided applies the exclusion zone.
Returns all indices below a threshold
Then around this function (and by doing some caching, as to not do the preprocessing of T every time) one cans build a k motif search implementation.

Awesome! I'm down for this.

> And maybe we can have a core.preprocessing function, that takes T, m and returns Tnew, meanT, sigmaT, that does all the nan/inf handling. Then we can replace redundant code in all the stump and stomp functions, and if a user wants to compute a distance profile of a time series containing nans he would do

> Tnew, meanT, sigmaT = stumpy.core.preprocessing(T, m)
Distances = stumpy.core.mass(Q, Tnew, meanT, sigmaT)

I would like this but, say, in `stumpy.stump`, we currently set `T_B[np.isnan(T_B)] = 0` only after the first profile is computed (via `_get_first_stump_profile`). How would we avoid or overcome this issue? Maybe I don't understand where exactly the preprocessing step would go within `stumpy.stump`

**Comment by mexxexx** [comment]
> How would we avoid or overcome this issue?

I think it would be enough to check if `M_Q[0]` is nan. We only do the setting to zero afterwards to handle the case that the first subsequence contains a nan value, and this is information is also stored in `M_Q[0]`.

**Comment by seanlaw** [comment]
Sounds good!
