### ISSUE TITLE
Add AB joins for SCRIMP 

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#171]
A reference/discussion for adding AB joins for SCRIMP (`stumpy.scrump`). 

This can be done without changing much, we only have to keep in mind to calculate the whole distance matrix instead of the upper triangle.

**Comment by seanlaw** [comment]
I'm really excited about this!

**Comment by seanlaw** [comment]
[This PR](742babaefca827e898992663ac3d12bc74c7db8) fixes some of this to be consistent with having `T_B` containing the query subsequences
