### ISSUE TITLE
Process getting killed at compute_mean_std

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#172]
When I want to compute a large matrix profile and don't have enough memory to compute mean and standard deviation (as we saw, especially the second operation is very memory consuming), the stumpy process gets killed. It should throw a MemoryError, but apparently (I'm on Ubuntu) this doesn't happen, see here: https://stackoverflow.com/q/52248531

Therefore, I would appreciate a possibility to pass the `number_of_chunks` parameter to stumpy. Maybe it would be a wiser idea to have a global variable in `stumpy.core`.

**Comment by seanlaw** [comment]
I'm digging into this a little. IIUC, it appears that the Linux kernel detects OOM and then sends a `SIGKILL` to the Python process?  And there's no way to catch a `SIGKILL`. 

Usually, Linux allows some level of "spill-over" from memory to disk when memory is running out. Is this an option?

I'm open to exploring solutions though. What I want to avoid is OS-specific code but I understand that your proposal for a global variable would likely work and is general

**Comment by mexxexx** [comment]
I have a 2GB swap file, but even with this I run into problem. I don't think that's a viable solution, because I don't want to alter my system only to run stumpy (and if my time series increases, I might have to do the same thing again).

I agree on not having os specific code in the library, that why I think giving the user control with a setting makes sense. (Maybe bundle it into a settings class/structure for future settings)

**Comment by seanlaw** [comment]
Understood. How soon do you need this? I’d like to do some research on this and present some possible options

**Comment by mexxexx** [comment]
Yes don't worry, we should find a solution that works in the long term and until then I can just modify the code myself.

Maybe you could have a look at how pandas implements it's options (pd.set_option I think), as that seems like a good approach for global settings.

**Comment by seanlaw** [comment]
Okay, I did a little research and am learning that the proper way to [share variables across modules](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules) is through a `config.py` file. I think this is a clean and simple way to handle things. So, we create `stumpy/config.py` file and in it:

```
# config.py

STUMPY_THREADS_PER_BLOCK = 512
STUMPY_MEAN_STD_N_CHUNKS = 1
```

```
# core.py

from . import config

def compute_mean_std(T, m, num_chunks=config.STUMPY_MEAN_STD_N_CHUNKS, max_iter=10):
    .
    .
    .
```

```
# main.py

import stumpy
import numpy as np
from stumpy import config

config.STUMPY_MEAN_STD_N_CHUNKS = 16

x = np.random.rand(100_000_000)
m = 50
stumpy.stump(x, m)
```

I see the same thing (i.e., use of `config`) in Numba. What do you think?  Will this solution suffice?

**Comment by mexxexx** [comment]
Yes, I think that would be great!

**Comment by seanlaw** [comment]
After sleeping on it, I don't like that in:

```
def compute_mean_std(T, m, num_chunks=config.STUMPY_MEAN_STD_N_CHUNKS, max_iter=10):
```

`num_chunks=config.STUMPY_MEAN_STD_N_CHUNKS` is not explicit. But if I change it to:

```
# stumpy/config.py

STUMPY_THREADS_PER_BLOCK = None
STUMPY_MEAN_STD_N_CHUNKS = None


# stumpy/core.py

from . import config

def compute_mean_std(T, m, num_chunks=1, max_iter=10):
    if config.STUMP_MEAN_STD_N_CHUNKS is not None:
        num_chunks = config.STUMP_MEAN_STD_N_CHUNKS
    .
    .
    .


# /path/to/some/directory/main.py

import stumpy
import numpy as np
from stumpy import config

config.STUMPY_MEAN_STD_N_CHUNKS = 16

x = np.random.rand(100_000_000)
m = 50
stumpy.stump(x, m)
```

which means that "globals always overrides locals". What do you think?

**Comment by mexxexx** [comment]
I think that may be confusing since we have the same thing in two different places. Maybe completely remove the `num_chnunks` argument, to not confuse useres with chunks when they only try to compute mean and stddev? I think the user should have to think about function internals as little as possible, and if he really needs control he should be able to set an option variable.

**Comment by seanlaw** [comment]
I see. I like your suggestions and will go with what you proposed. It’s such a subtle thing and really only advance users such as yourself should care. For 99.9% of the cases, the default of `num_chunks=1` should be sufficient.

I will try to incorporate this and test it today

**Comment by mexxexx** [comment]
> only advance users

Or users wiithout enough RAM :smile:

**Comment by seanlaw** [comment]
@mexxexx Would you mind testing it out and re-open if it isn't fixed?

There are three global variables now:

```
# stumpy/config.py

STUMPY_THREADS_PER_BLOCK = 512
STUMPY_MEAN_STD_NUM_CHUNKS = 1
STUMPY_MEAN_STD_MAX_ITER = 10
```

Note that it is `STUMPY_MEAN_STD_NUM_CHUNKS` and not `STUMPY_MEAN_STD_N_CHUNKS`

**Comment by mexxexx** [comment]
Thank you, I will!
