### ISSUE TITLE
Add SCRIMP++ Test 

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#173]
Essentially, we need to add a proper `naive_prescrump` tests

**Comment by seanlaw** [comment]
@mexxexx This is here for your reference

**Comment by seanlaw** [comment]
@mexxexx I really like your idea of building the entire distance matrix first and then cherry picking the distances needed to create a `naive` implementation! I plan to use the same approach for testing `prescrump`

**Comment by seanlaw** [comment]
I have made some progress and added back the `prescrump` test along with a `naive_prescrump`. It seems to be fine for self-joins and with different `s` size

I still need to write the tests for an AB-join. Again, your idea for creating a distance matrix has greatly simplified the testing so thank you for that wonderful gem!  Have a wonderful vacation.

**Comment by mexxexx** [comment]
That's great! But I would change the `for s in range(1, zone+1)` part, because in the `m=3` case you only test for `s=1`. Maybe add a new test case with a longer sequence and a slightly larger window.

**Comment by seanlaw** [comment]
Indeed, you probably missed it but I had split that part out and also tested larger values of `s` in `test_prescrump_self_join_larger_window` which should be right below the test that you were looking at

**Comment by mexxexx** [comment]
Ah, great! Yes I didn't see that

**Comment by seanlaw** [comment]
This was fully resolved in 2742babaefca827e898992663ac3d12bc74c7db8
