### ISSUE TITLE
Update SCRUMP Function Docstrings

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#175]
Some of the docstrings need to be cleaned up according to the [PR comment](https://github.com/TDAmeritrade/stumpy/pull/170#pullrequestreview-410784752)

**Comment by seanlaw** [comment]
@mexxexx I've invited you to be an "external collaborator" for this repo so that I can assign issues to you more easily. It's my first time trying it so please excuse/forgive the noisy emails until I figure things out.

**Comment by mexxexx** [comment]
Thanks, I'll look into it tomorrow!
