### ISSUE TITLE
Inconsistent test for SCRUMP

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#178]
Following the notation of the original matrix profile papers, an AB-join involves taking "queries" from time series `T_B` (i.e., `Q = T_B[i : i + m]`) and comparing it to all subsequences in `T_A`. So, the output matrix profile should be of length `l = n_B - m + 1`. In STUMPY, we try to follow and adhere to this notation for consistency. However, the `naive_scrump` in `tests_scrump.py` is:

```
def naive_scrump(T_A, m, T_B, percentage, exclusion_zone, pre_scrump, s):
    distance_matrix = np.array(
        [utils.naive_distance_profile(Q, T_B, m) for Q in core.rolling_window(T_A, m)]
    )
```

I believe that this notation should really be:

```
def naive_scrump(T_A, m, T_B, percentage, exclusion_zone, pre_scrump, s):
    distance_matrix = np.array(
        [utils.naive_distance_profile(Q, T_A, m) for Q in core.rolling_window(T_B, m)]
    )
```

So that the "queries" are taken from `T_B` rather than `T_A` (i.e., `Q in core.rolling_window(T_B, m)]`). This may possibly affect `naive_get_max_order_idx` and `naive_get_orders_ranges` as well.

However, I can confirm that the output of `stumpy.scrump` is identical to `stumpy.stump` for AB-joins and the length of the matrix profile is indeed `l = n_B - m + 1`. This may suggest that everything is flipped around just perfectly to accommodate.

**Comment by seanlaw** [comment]
@mexxexx Would you mind taking a look when you have time?

**Comment by mexxexx** [comment]
When I implemented the code I did it exactly the way you suggested, but the matrix came out Transposed of what I thought it should be like.

Maybe we should try to change it, but i don't know how this would affect AB joins

**Comment by seanlaw** [comment]
Yeah, I saw the same thing when I tried to flip it and I don’t understand it either. However, do you agree that, from a syntax standpoint, that line is incorrect/backwards?

**Comment by mexxexx** [comment]
I agree. Two alternatives are either to transpose the matrix, but then it would raise the questions as of why, or second to reimplement it. However, then I think that some logic has to be changed and I don't know how consistent it is with the paper (I think you then would actually compute the lower triangle of the distance matrix).

**Comment by seanlaw** [comment]
Okay, I will think about it for a bit. Considering that the `scrump` produces the same output as `stump` for AB-joins, this suggests that the problem may simply be in unit test (which might be an easier fix). I will report back on what I find but I wanted to make sure I wasn’t thinking about `T_A` and `T_B` incorrectly. Thanks for being my [rubber ducky](https://en.m.wikipedia.org/wiki/Rubber_duck_debugging)!

**Comment by mexxexx** [comment]
> Thanks for being my rubber ducky!

You're welcome :smile: 

I also think its only the unit test, and its just ab little bit unintuitive. But it might be a good idea to have a `test_naive_scrump` method where we compare its output to the output of STUMP, to be on the safe side.

**Comment by seanlaw** [comment]
After doing:

```
def naive_scrump(T_A, m, T_B, percentage, exclusion_zone, pre_scrump, s):
    distance_matrix = np.array(
        # [utils.naive_distance_profile(Q, T_B, m) for Q in core.rolling_window(T_A, m)]
        [utils.naive_distance_profile(Q, T_A, m) for Q in core.rolling_window(T_B, m)]
    )

    n_A = T_A.shape[0]
    n_B = T_B.shape[0]
    l = n_B - m + 1

    if exclusion_zone is not None:
        orders = np.random.permutation(range(exclusion_zone + 1, n_B - m + 1))
    else:
        # orders = np.random.permutation(range(-(n_A - m + 1) + 1, n_B - m + 1))
        orders = np.random.permutation(range(-(n_B - m + 1) + 1, n_A - m + 1))

    # orders_ranges = naive_get_orders_ranges(1, m, n_A, n_B, orders, 0, percentage)
    orders_ranges = naive_get_orders_ranges(1, m, n_B, n_A, orders, 0, percentage)
    orders_ranges_start = orders_ranges[0][0]
    orders_ranges_stop = orders_ranges[0][1]

    out = np.full((l, 2), np.inf, dtype=object)
    out[:, 1] = -1

    for order_idx in range(orders_ranges_start, orders_ranges_stop):
        k = orders[order_idx]

        current_diagonal = np.array(
            # [[i - j == k for i in range(n_B - m + 1)] for j in range(n_A - m + 1)]
            [[i - j == k for i in range(n_A - m + 1)] for j in range(n_B - m + 1)]
        )
        current_diagonal_values = distance_matrix[current_diagonal]

        for i in range(current_diagonal_values.size):
            if exclusion_zone is not None and current_diagonal_values[i] < out[i, 0]:
                out[i, 0] = current_diagonal_values[i]
                out[i, 1] = i + k
            if current_diagonal_values[i] < out[i + max(0, k), 0]:
                out[i + max(0, k), 0] = current_diagonal_values[i]
                out[i + max(0, k), 1] = i - min(0, k)

    return out
```

Right now, I am stuck on the pre-processing steps `naive_get_max_order_idx` and `naive_get_orders_ranges`. I'm trying to keep the argument list the same but flip the `n_A` and `n_B` within these two function but I can't see to get the tests to pass.
