### ISSUE TITLE
Create module for motif discovery

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#184]
What do you think of having a separate module called `motifs.py` where we have an implementation of the k-top-motif search?

> Do you think you could provide a checklist on the steps that you think are necessary to get this to work?

I would suggest the following: 
* Leave core.mass as it is, because 8t does exactly what MASS was made for, i.e. finding the distance profile of a query. 
* Rename stump.mass like you proposed
* In motifs.py have a function `find_occurences` (or something different) that does the following:
1. Gets a query Q, time series T and optionally the index of Q in T and an exclusion zone.
2. Replaces nan/inf in a copy of T and computes mean and stddev (basically does all the usual preprocessing)
3. Computes the distance profile of Q and T (the modified version) using core.mass, and if provided applies the exclusion zone.
4. Returns all indices below a threshold
* Then around this function (and by doing some caching, as to not do the preprocessing of T every time) one cans build a k motif search implementation.

_Originally posted by @mexxexx in https://github.com/TDAmeritrade/stumpy/issues/166#issuecomment-631910790_

**Comment by seanlaw** [comment]
@mexxexx Did you happen to see this [recent paper by Keogh's group](https://link.springer.com/article/10.1007/s10618-020-00685-w) on motif/discord discovery? It may be useful for your work

**Comment by mexxexx** [comment]
Hi! I haven't seen it, thank you, I'll look at it.

**Comment by hari-packetai** [comment]
> @mexxexx Did you happen to see this [recent paper by Keogh's group](https://link.springer.com/article/10.1007/s10618-020-00685-w) on motif/discord discovery? It looks like it is building upon their [VALMOD paper](http://helios.mi.parisdescartes.fr/~themisp/publications/sigmod18-valmodsystem.pdf) and it may be useful for your PR

Hi, Are the algorithms for motif and discord discovery described in this paper available in Stumpy?

**Comment by seanlaw** [comment]
> Hi, Are the algorithms for motif and discord discovery described in this paper ("Matrix profile goes MAD") available in STUMPY?

@hari-packetai I do not believe so. The only methods that we currently have are [motifs](https://stumpy.readthedocs.io/en/latest/api.html#stumpy.motifs) and [match](https://stumpy.readthedocs.io/en/latest/api.html#match). Neither account for variable length matrix profiles
