### ISSUE TITLE
Add Support for float32 Inputs for gpu_stump

### ISSUE THREAD

**Issue by thoth291** [TDAmeritrade/stumpy#194]
Reproducer:
```python
import stumpy
import numpy as np
from numba import cuda

your_time_series = np.random.rand(10000).astype(np.float32)
window_size = 50  # Approximately, how many data points might be found in a pattern
all_gpu_devices = [device.id for device in cuda.list_devices()]  # Get a list of all available GPU devices

matrix_profile = stumpy.gpu_stump(your_time_series, m=window_size, device_id=all_gpu_devices)
```

Fails with:
```python
---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
<ipython-input-2-e9517de5931e> in <module>
      7 all_gpu_devices = [device.id for device in cuda.list_devices()]  # Get a list of all available GPU devices
      8
----> 9 matrix_profile = stumpy.gpu_stump(your_time_series, m=window_size, device_id=all_gpu_devices)

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/stumpy/gpu_stump.py in gpu_stump(T_A, m, T_B, ignore_trivial, threads_per_block, device_id)
    583                 start + 1,
    584                 threads_per_block,
--> 585                 device_ids[idx],
    586             )
    587

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/stumpy/gpu_stump.py in _gpu_stump(T_A_fname, T_B_fname, m, range_stop, excl_zone, M_T_fname, Σ_T_fname, QT_fname, QT_first_fname, μ_Q_fname, σ_Q_fname, k, ignore_trivial, range_start, threads_per_block, device_id)
    360                 device_profile,
    361                 device_indices,
--> 362                 True,
    363             )
    364

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/compiler.py in __call__(self, *args, **kwargs)
    534                           blockdim=self.blockdim,
    535                           stream=self.stream,
--> 536                           sharedmem=self.sharedmem)
    537
    538     def bind(self):

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/compiler.py in _kernel_call(self, args, griddim, blockdim, stream, sharedmem)
    608                                    sharedmem=sharedmem)
    609         # Invoke kernel
--> 610         cu_func(*kernelargs)
    611
    612         if self.debug:

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in __call__(self, *args)
   1576
   1577         launch_kernel(self.handle, self.griddim, self.blockdim,
-> 1578                       self.sharedmem, streamhandle, args)
   1579
   1580     @property

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in launch_kernel(cufunc_handle, griddim, blockdim, sharedmem, hstream, args)
   1620                           hstream,
   1621                           params,
-> 1622                           None)
   1623
   1624

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    292             _logger.debug('call driver api: %s', libfn.__name__)
    293             retcode = libfn(*args)
--> 294             self._check_error(fname, retcode)
    295         return safe_cuda_api_call
    296

/conda/ppc64le/envs/powerai-1.7.0/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    327                     _logger.critical(msg, _getpid(), self.pid)
    328                     raise CudaDriverError("CUDA initialized before forking")
--> 329             raise CudaAPIError(retcode, msg)
    330
    331     def get_device(self, devnum=0):

CudaAPIError: [716] Call to cuLaunchKernel results in CUDA_ERROR_MISALIGNED_ADDRESS
```
You could have used this example (http://numba.pydata.org/numba-doc/latest/cuda/ufunc.html#example-basic-example) to see how you can specialize one function for multiple types.

**Comment by seanlaw** [comment]
Or, alternatively, we could simply accept the `float32` input and cast it as `float64` behind the scenes. My last comment was more focused on the fact that the actual computation is performed on the GPU with double precision but there is no reason why the input couldn't be `float32` and still allow the computation  to be performed in `float64`. What are your thoughts?

**Comment by thoth291** [comment]
My data is extremely big: hundreds of millions long. It also comes from sensors which are natively operate in float32. So casting to float64 would double amount of data passed between me and stumpy. And would produce some temporary arrays without any need in them.

Given that numba accepts multiple dispatch, it shouldn't be a problem to compile interfaces for both 32 and 64 bit. I do realize that internal calculations might require 64 bit, but I would hesitate to create any temporary arrays outside or within stumpy simply to pass data appropriately to kernel routines.

Does it makes sense, @seanlaw ?

**Comment by seanlaw** [comment]
@thoth291 I understand and, to be clear, I am not opposed to adding `float32` support as long as you understand that it may significantly reduce the numerical stability of your results. Having said that, depending on what you are trying to accomplish (i.e., looking for motifs), another option might be to downsample the data first in order to isolate regions of the times series to explore further.

If it's true that adding an additional signature could solve the problem, would you consider trying out the documentation that you pointed to and submitting a PR? We'd welcome the help!

P.S. This is the first time that a GPU user has submitted an issue and so I am grateful and appreciate any comments, feedback, and criticism! Are you able to tell us more detail about your sensor use case?

**Comment by thoth291** [comment]
@seanlaw While I do believe that your project backlog is bigger than my personal one, unfortunately I don't have anyone else looking after my one and thus if I'll work on PR - it will be in the deep future. We can't really talk about the research at this point - I can only tell that we are not ready to subsample just yet - this is quite new type of data and we are looking for some patterns with hope to be able to correlate them to real physical phenomena.
Once there will be an article ready - we will make sure to refer to this project and I'll see if I can share it with you.
P.S. I'm personally more of dask user than GPU - but this time GPU seemed to be more relevant.

**Comment by seanlaw** [comment]
Sounds good! I look forward to reading the article

**Comment by seanlaw** [comment]
@thoth291 I'm going to close this for now as we have other higher priority items in the queue but please feel free to re-open or start another issue if you have further questions. Thank you
