### ISSUE TITLE
Redundant Code in `_calculate_squared_distance`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#197]
In `core. _calculate_squared_distance(m, QT, μ_Q, σ_Q, M_T, Σ_T)`, the code shows:

```
threshold = 1e-10
if np.isinf(M_T) or np.isinf(μ_Q):
    D_squared = np.inf
else:
    if σ_Q < threshold or Σ_T < threshold:
        D_squared = m
    else:
        denom = m * σ_Q * Σ_T
        if np.abs(denom) < threshold:  # pragma nocover
            denom = threshold
        D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
    if σ_Q < threshold and Σ_T < threshold:
        D_squared = 0
return D_squared
```

It seems that the final:

```
if σ_Q < threshold and Σ_T < threshold:
    D_squared = 0
```

isn't actually doing anything useful and can be removed.

**Comment by seanlaw** [comment]
@mexxexx Can you confirm that this can be removed?

**Comment by mexxexx** [comment]
I think it is necessary. Otherwise if both sigmas are smaller than the threshold, the distance would be `m`, which is not what one would want for two constant subsequences.

**Comment by seanlaw** [comment]
Ohhhh, I missed that it was `or` (in the first case) versus `and` (in the second case)! Thank you for clarifying
