### ISSUE TITLE
Add Short STUMPI Tutorial

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#200]
It would be helpful to write a short tutorial on STUMPI usage and discuss current limitations

**Comment by seanlaw** [comment]
@hmcoservit Here's the [updated Tutorial notebook](https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html). Let me know if it makes sense or if you have any questions or have anything you want to add!

**Comment by hmcoservit** [comment]
@seanlaw That was fast! Thank you, I will take a look at it asap. I am currently looking at and testing the code. I will update you hopefully by tomorrow

**Comment by seanlaw** [comment]
@hmcoservit I'm a "strike while the iron is hot" kinda person 😄. Your expediency is greatly appreciated!

**Comment by hmcoservit** [comment]
@seanlaw I am sorry for the delay, I had a hectic schedule this week. 

The tutorial looks good, it is detailed enough and easy to follow. Maybe it can be improved a bit by adding visualization with real data similar to [this link](https://stumpy.readthedocs.io/en/latest/Tutorial_Semantic_Segmentation.html). Also another thing to add can be demonstrating the speed gain of using STUMPI. 

For a small test I did, for a time series of size 2000 and m of size 10:
- Treating the data as a batch took 0.2 seconds to compute the matrix profile
- STUMPI took 2.7 seconds (with initialization of 10%)
- Re-training STUMP each time took 177 seconds (with initialization of 10%)

Which demonstrates the speed gain of STUMPI. I will keep you updated regarding more tests I do. Thanks again for the work on STUMPI, it really helps!

**Comment by seanlaw** [comment]
@hmcoservit No worries and I appreciate your feedback!

> Maybe it can be improved a bit by adding visualization with real data similar to this link.

I had considered adding some viz but I questioned the value since, at the end of the day, it produces a matrix profile (which is covered in many of the other tutorials). Usually, I add viz to reproduce the published work and so I will look into reproducing Figures 14 and Figure 15 from Section G of the original [Matrix Profile I](https://www.cs.ucr.edu/~eamonn/PID4481997_extend_Matrix%20Profile_I.pdf) paper that demonstrates and example of STAMPI (but the result should be the same). 

> Also another thing to add can be demonstrating the speed gain of using STUMPI.

I like this idea and I'll work on adding a simple viz that plots the (cumulative?? or each iteration??) computation time on the Y-axis and the time series length on the X-axis and compare `stumpy.stump` vs `stumpy.stumpi`

**Comment by seanlaw** [comment]
@hmcoservit Just one additional thing to note as an aside, STUMPY uses `Numba` JIT compilation to for speed and so it might be "slow" the first time you call a function (since it spends a bit of time compiling the code at first use) but it will likely be faster in subsequent runs. Both `stumpy.stump` and `stumpy.stumpi` both leverage `Numba` JIT compiled code in its core guts. This only matters when performing timing calculations though and less important for production.

**Comment by hmcoservit** [comment]
@seanlaw Yes, indeed reproducing Figures 14 and Figure 15 from the paper would be more useful. 

In the same section the paper also mentions the maximum time needed to process a single data point for a time series sampled at each minute. It is claimed that "STAMPI could continue monitoring for several decades before running out of time or memory...".  According to the [performance tests](https://github.com/TDAmeritrade/stumpy#hardware) retraining using Stump (treating data as a batch each time a new point arrives) would become impractical (in a streaming scenario) from around the 100k - 200k data point mark. That means at one stage, your processing time will be more than your sampling rate and re-calculating STUMP becomes impractical in a streaming scenario. Of course, you can always re-start STUMP when it becomes to slow (ignoring historical MP). It would also be nice to demonstrate this somehow, I think both cumulative time and each iteration time would be interesting. Or a way of saying until which data point streaming becomes impractical using STUMP for time series sampled at different intervals (for example 1 minute). I used a simple for loop for the tests I did using time series of size 2000. What about processing several time series in parallel? Finally, thanks for the heads up regarding calculating the time.

**Comment by seanlaw** [comment]
> Yes, indeed reproducing Figures 14 and Figure 15 from the paper would be more useful.

It looks like that example is a bit convoluted and the data is not easily obtainable (and will be difficult to explain). I will think about this and maybe use the classic "steam-gen" data set. Essentially, we just want to be able to see that as you add more data eventually a global motif will appear. Is that what you had in mind?
 
>In the same section the paper also mentions the maximum time needed to process a single data point for a time series sampled at each minute. It is claimed that "STAMPI could continue monitoring for several decades before running out of time or memory...". According to the performance tests retraining using Stump (treating data as a batch each time a new point arrives) would become impractical (in a streaming scenario) from around the 100k - 200k data point mark. That means at one stage, your processing time will be more than your sampling rate and re-calculating STUMP becomes impractical in a streaming scenario. Of course, you can always re-start STUMP when it becomes to slow (ignoring historical MP). It would also be nice to demonstrate this somehow, I think both cumulative time and each iteration time would be interesting. Or a way of saying until which data point streaming becomes impractical using STUMP for time series sampled at different intervals (for example 1 minute). I used a simple for loop for the tests I did using time series of size 2000. What about processing several time series in parallel? Finally, thanks for the heads up regarding calculating the time.

Prior to your comment, I added this [performance section](https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html#The-Performance). I don't want to be too attached to these numbers since the hardware matters and, at best, these numbers are typically biased. What's important are the relative numbers and getting a rough estimate of the average rate of updating. Take a look and let me know if you think it's sufficient.

**Comment by hmcoservit** [comment]
Thank you, for sure!

I currently work for an IoT company, and we are trying to implement a fast and (almost automated) solution for anomaly detection to monitor our infrastructure (detecting incidents for example). I am new to matrix profiles and STUMPY in general, but so far it seems a promising candidate to solve our problems. I will keep you updated on the progress for sure.

**Comment by seanlaw** [comment]
Awesome and thank you for sharing!

I've added a [new section to the tutorial](https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html#A-Visual-Example). Please take a look when you have some time.

**Comment by hmcoservit** [comment]
@seanlaw Thanks, it seems good for me. Specially talking about the part about any change in the matrix profile can only move downward. Because initially I thought that in the incremental mode, past matrix profile values do not change (because they depend on their past) when new points arrive. 

Since historical matrix profile values also update in the stream I probably need to consider this for my tests. Because I have to decide if each point is an anomaly considering only past values. Evaluating after incremental mode is finished would be biased because historical matrix profile values are updated from future values. What do you think?

**Comment by seanlaw** [comment]
@hmcoservit I think that this gets into a bit of a philosophical debate. STUMPY tries to be faithful to the original paper and the core matrix profile definition refers to z-normalized Euclidean distance to it’s nearest neighbor (can be on the right or on the left). Later, in their time series chains paper, they introduce the idea of a “left matrix profile index” and a “right matrix profile index” and they also discuss something similar in their “semantic segmentation” paper (see “FLUSS”).

So, I see your point. The issue is that “anomaly” is a tricky thing and one must clearly define what they mean when they say it (I don’t even know how to best define it myself). 

Technically, if the new data point arrives (let’s call this single the `ith` point), that corresponding newly created subsequence will only have a nearest neighbor with a historical value. And this will continue to be true until `m/4` more new data point values get appended to the time series. So, you have a bit of “time” to declare if something is an anomaly right on the spot (and until you pass the exclusion zone). Afterward, the `ith` data point (from above) is then allowed to find a new nearest neighbor (assuming it has a smaller distance) with a future subsequence on the right. But, now, if you do update the nearest neighbor for `i` this is basically “hindsight”. You are correcting yourself and saying “oh, before, the subsequence(s) created by the `ith` data point looked anomalous but now that I’ve seen more data I can confirm that it is no longer anomalous”. Basically, if you were sampling, say, from a sine wave and you were looking for anomalies, all of the data points within the first period would look anomalous. That is, until the second period comes back around (and repeats again and again). In your definition, the data points from the new periods would not be “labeled” as anomalous but the data points from the first period would be labeled as anomalous. And now we get into a philosophical debate regarding whether or not one should update the past given that the future has “spoken”. 😊

Ultimately, this depends on “what question are you trying to answer”? 

Having said that, it shouldn’t be too hard to tell it not to update the historical data. It is probably a single `if` statement that needs to get added and you'll need to pass in an argument/parameter to the `stumpi` function to handle it. Now, that very first, say, 10% worth of data will have matrix profile values from both directions but all points after that first “seed” could be made to only look “backwards” and never update forwards. Actually, the easiest thing is to start with a “seed” of `m+1` (up to `m+m/4) data points and everything would only be backwards looking and you can turn on the parameter. Would the addition of this parameter be useful?

**Comment by hmcoservit** [comment]
@seanlaw Thanks for your answer I understand and agree with you, and of course defining what is an anomaly is very tricky and may depend on the context too (contextual anomalies). Indeed by not getting into any philosophical debate, we can assume we can decide if a point is an anomaly or not before any new points arrive. 

For my tests the current implementation would be sufficient of course, I can try to do a work around for it. For production, it would be the same. However it would not hurt to have it as an optional parameter ;)

**Comment by seanlaw** [comment]
> For my tests the current implementation would be sufficient of course, I can try to do a work around for it. For production, it would be the same. However it would not hurt to have it as an optional parameter ;)

Okay, so I was able to quickly make `stumpy.stumpi` object oriented and the code and API is much, much cleaner now. I've updated [the Tutorial](https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html) according to this new implementation and I've also added a [Bonus Section](https://stumpy.readthedocs.io/en/latest/Tutorial_Matrix_Profiles_For_Streaming_Data.html#Bonus-Section---Never-Update-History) just for you 😄 

It was actually super straightforward to add. Hopefully, this solves your problem exactly. Would you mind testing it out and let me know if it is what you'd expect?

**Comment by hmcoservit** [comment]
Great! thank you, it seems good. I will test the code and keep you updated ;)

**Comment by hmcoservit** [comment]
Hi @seanlaw, I hope you are well. Firstly thank you for the bonus section, it was very useful. I have been testing STUMPI  and visualizing the results for anomaly (discord) discovery. I had a question regarding aligning the matrix profile to the time step that the anomaly has occurred. Would it be right to shift the matrix profile forward by (m-1)? or (m-1+4)?   I also realized when m becomes smaller, the matrix profile becomes almost flat and does not reflect large distances for discords. Is there any resources you can point me to regarding choosing the right m for discord discovery (automatically)?


Here is a visual example by using the [data from NAB ](https://github.com/numenta/NAB/tree/master/data/realAWSCloudwatch) (ec2_cpu_utilization_825cc2-labeled.csv), why does it seem like the full MP gives better values than the left MP? (I thought the opposite)

![plot sean](https://user-images.githubusercontent.com/60774604/85039842-6b2cfb00-b188-11ea-8ea8-76c968edd97d.PNG)


`
    import plotly.graph_objs as go
    import pandas as pd
    import stumpy
    import numpy as np

    m = 60
    warm_start = 500

    # confidence values for MP
    sigma = 3
    MA_value = 144

    T_full = df['value'].values
    T_stream = df['value'].values[:warm_start].copy()

    # initialize
    stream = stumpy.stumpi(T_stream, m)

    # incrementally update mp
    for i in range(len(T_stream), len(T_full)):
        t = T_full[i]
        stream.update(t)

    # remove nan and inf values
    profile = stream.left_P_
    profile[profile == -np.inf] = -1
    profile[profile == np.inf] = -1
    profile[profile == np.nan] = -1

    df = df[m-1:]
    df['mp'] = profile
    df['mp_full'] = stream.P_


    # confidence area (3 sigma rule )
    upper = list()
    lower = list()
    mean = list()

    for i in range(MA_value, len(profile)):
        values = profile[:i][-MA_value:]

        mean.append(values.mean())
        upper.append(values.mean() + sigma * values.std())
        lower.append(values.mean() - sigma * values.std())

    df['upper'] = np.append(np.zeros(MA_value) + np.nan, upper)
    df['lower'] = np.append(np.zeros(MA_value) + np.nan, lower)
    df['mean'] = np.append(np.zeros(MA_value) + np.nan, mean)

    # plot
    fig = go.Figure()

    fig.add_trace(
    go.Scattergl(
        x=df.index,
        opacity=0.1,
        y=df['lower'].values,
        yaxis='y2',
        fill='tonexty',
        name='lower',
    ))

    fig.add_trace(
    go.Scattergl(
        x=df.index,
        y=df['upper'].values,
        opacity=0.1,
        yaxis='y2',
        fill='tonexty',
        name='upper',
    ))

    fig.add_trace(
    go.Scattergl(x=df.index,
                 y=df['value'],
                 name='value',
                 mode='lines',
                 yaxis='y1'))
    fig.add_trace(
    go.Scattergl(x=df.index,
                 y=df['mp'],
                 name='left mp',
                 mode='lines',
                 opacity=0.5,
                 yaxis='y2'))
    fig.add_trace(
    go.Scattergl(x=df.index,
                 y=df['mp_full'],
                 name='full mp',
                 opacity=0.5,
                 yaxis='y2'
                 ))


    fig.add_trace(
    go.Scattergl(
        x=df.index,
        opacity=0.1,
        y=df['mean'].values,
        # fill= None,
        yaxis='y2',
        name='mean',
    ))


    fig.update_layout(title="Matrix profile results (mp shifted forward by m-1)",
                  yaxis2=dict(
                      domain=[0, 0.4]
                  ),

                  yaxis=dict(
                      domain=[0.4, 1]
                  ),)

    fig.show()

`

**Comment by seanlaw** [comment]
> Would it be right to shift the matrix profile forward by (m-1)? or (m-1+4)?

No, it would not be right to shift the matrix profile. The `ith` matrix profile value is aligned with the start of its window, `T[i : i + m]` and where the window size is `m`. Unless we've made some mistake in the code, this should not be changed.

> I also realized when m becomes smaller, the matrix profile becomes almost flat and does not reflect large distances for discords. Is there any resources you can point me to regarding choosing the right m for discord discovery (automatically)?

According to the original papers, the matrix profile is not so sensitive to the size of the window. Of course, this is more focused on identifying motifs. Here's a [brief section](https://stumpy.readthedocs.io/en/latest/Tutorial_STUMPY_Basics.html#Different-Window-Sizes) on this regarding motifs. You want to choose something based on your domain expertise. There is also [this paper](https://www.cs.ucr.edu/~eamonn/PAN_SKIMP%20%28Matrix%20Profile%20XX%29.pdf) on visualizing motifs with different window size. Again, the issue is that anomalies are hard!

> why does it seem like the full MP gives better values than the left MP

What do you mean by "better" values? The matrix profile only tells you the Euclidean distance to its nearest neighbor. To find out "where" along the time series this neighbor is, you have to look at the matrix profile indices. For a given subsequence, `T[i : i + m]`, I recommend plotting the nearest neighbor, `T[I[i]: I[i] + m]`, as an overlapping line plot and seeing how different they are.

Additionally, I'm not quite following your plot here. What is the point of the "upper" and "lower"? Since, in this case, you have the full time series, it probably makes sense just to apply `stumpy.stump` to it (instead of `stumpy.stumpi`) just so you get a firm grasp of what is happening with your data. 

It sounds like what you are asking if why the downward spike in the  data is not recognized as having a large matrix profile value. I think it's because of your window size. If you increase the window size to `m=2000` then the drop is seen as an anomaly by matrix profile standards. It is important to keep in mind that matrix profiles are looking at subsequence anomalies and not single point anomalies. If you choose a window size that does not adequately encompass a your anomalous time period then that may be problematic. But, again, anomalies are hard especially when subsequences are z-normalized locally.

**Comment by hmcoservit** [comment]
@seanlaw Thank you for your answer

> No, it would not be right to shift the matrix profile. The `ith` matrix profile value is aligned with the start of its window, `T[i : i + m]` and where the window size is `m`. Unless we've made some mistake in the code, this should not be changed.
> 

Yes you are right, the reason I did this was mainly for visualization purposes. Since the matrix profile is aligned with the start of the window, at each time step `i` we have already seen `i+m` points. For example in an anomaly detection system, m would be considered delay in detection. My main goal was to align the last matrix profile value to the last observed value, so that I can observe the exact timesteps that the matrix profile changes. Do you think this would be wrong? 


> According to the original papers, the matrix profile is not so sensitive to the size of the window. Of course, this is more focused on identifying motifs. Here's a [brief section](https://stumpy.readthedocs.io/en/latest/Tutorial_STUMPY_Basics.html#Different-Window-Sizes) on this regarding motifs. You want to choose something based on your domain expertise. There is also [this paper](https://www.cs.ucr.edu/~eamonn/PAN_SKIMP%20%28Matrix%20Profile%20XX%29.pdf) on visualizing motifs with different window size. Again, the issue is that anomalies are hard!
> 

Thank you, I will check it out. 

> What do you mean by "better" values? The matrix profile only tells you the Euclidean distance to its nearest neighbor. To find out "where" along the time series this neighbor is, you have to look at the matrix profile indices. For a given subsequence, `T[i : i + m]`, I recommend plotting the nearest neighbor, `T[I[i]: I[i] + m]`, as an overlapping line plot and seeing how different they are.
> 

Apologies for the bad wording there. I meant for the downward spikes between April 15 and 16 in the plot the left MP is relatively unchanged (and almost no change) compared to the full MP. Maybe I was missing something here. I will try what you recommended. 

> Additionally, I'm not quite following your plot here. What is the point of the "upper" and "lower"? Since, in this case, you have the full time series, it probably makes sense just to apply `stumpy.stump` to it (instead of `stumpy.stumpi`) just so you get a firm grasp of what is happening with your data.
> 

The goal was to simulate a streaming scenario with STUMPI and generate the MP that is not updated based on future values. The plot is just a static plot of the results. The goal of the upper and lower was based on your recommendation that we discussed previously. To identify anomalies or discords using the 3 sigma rule instead of percentile values. 


> It sounds like what you are asking if why the downward spike in the data is not recognized as having a large matrix profile value. I think it's because of your window size. If you increase the window size to `m=2000` then the drop is seen as an anomaly by matrix profile standards. It is important to keep in mind that matrix profiles are looking at subsequence anomalies and not single point anomalies. If you choose a window size that does not adequately encompass a your anomalous time period then that may be problematic. But, again, anomalies are hard especially when subsequences are z-normalized locally.

Indeed you are right, I will try to experiment on this further.

**Comment by seanlaw** [comment]
Sounds good. Let me know if you have anymore questions. I may not have the answers but I'm happy to talk through these things.

**Comment by seanlaw** [comment]
@hmcoservit These links might be relevant as well for anomaly detection (or discord discover):

https://www.slideshare.net/SupreetOberoi1/timeseries-analytics-using-matrix-profile-and-sax

https://blogs.oracle.com/datascience/sax-and-matrix-profile-techniques-for-root-cause-analysis

**Comment by hmcoservit** [comment]
@seanlaw Thank you! I will check out the links. Actually we came upon matrix profiles while we were checking out SAX based methods for anomaly detection, these two links would be certainly interesting.  Finally, I would be more than happy to share the results as soon as I have something concrete ;)
