### ISSUE TITLE
Add NaN/inf Support to STUMPI

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#201]
Since `stump.stumpi` does not call `core.mass`, we don't benefit from a lot of the NaN/inf infrastructure and currently does not support times series that contains NaN/inf values. Adding it may be a bit tricky.

**Comment by seanlaw** [comment]
Okay, @mexxexx, I'm going to need to borrow your brain as this has gotten a bit more problematic than I had expected. Let's walk through a simple example:

Let's say we have a simple time series where the last value is `np.nan`:

```
T = np.array([0.1, 1.2, 9.5, np.nan])
m = 3
```

We'll perform some pre-processing in order to get the correct inputs for `stumpi`:
```
mp = stumpy.stump(T, m)
P = mp[:, 0]
I = mp[:, 1]

T_stream, M_T, Σ_T = core.preprocess(T, m)  # np.nan = zero, M_T = [3.6, inf]
Q = T_stream[-m:]
QT = core.sliding_dot_product(Q, T_stream)
```

There's nothing out of the ordinary so far but here's where things start to get tricky. If we now append a "new" data point to `T_stream`, create a new `Q`, and try to compute the mean:

```
t = 4.0  # A new data point
T_stream = np.append(T_stream, t)  # [0.1, 1.2, 9.5, 0.0, 4.0]
Q = T_stream[-m:]
QT = ... # Update QT with the typical STOMP approach
μ_Q, σ_Q = core.compute_mean_std(Q, m)
```

Here, `Q` is `[9.5, 0.0, 4.0]` and so `μ_Q` is `4.5`. 
However, `Q` should really be `[9.5, np.nan, 4.0]` and, therefore, `μ_Q` should be `np.inf` (technically, `μ_Q` is `np.nan` but `compute_mean_std` converts the `np.nan` to `np.inf`).

Now, since the locations of the `np.nan` is implicitly captured in `M_T`, my first instinct was to check if there were any `np.inf` in `M_T[-m:]` and, if so, set `μ_Q` to `np.inf`:

```
if np.any(np.isinf(M_T[-m:])):
    μ_Q = np.inf
```

Next, we'll append `μ_Q, σ_Q` to `M_T, Σ_T`, compute the distance profile for the "new" subsequence, and update our matrix profile:

```
M_T = np.append(M_T, μ_Q)  # [3.6, inf, inf]
Σ_T = np.append(Σ_T, σ_Q)
if np.isinf(μ_Q):
    D = np.full(M_T_new.size, np.inf, dtype=float)
else:
    D = core.calculate_distance_profile(m, QT_new, μ_Q, σ_Q, M_T, Σ_T)

# Update matrix profile
```

And when we need to add another new data point we might follow the same process as above:

```
t = 17.9  # Another new data point
T_stream = np.append(T_stream, t)  # [0.1, 1.2, 9.5, 0.0, 4.0, 17.9]
Q = T_stream[-m:]
QT = ... # Update QT with the typical STOMP approach
μ_Q, σ_Q = core.compute_mean_std(Q, m)

if np.any(np.isinf(M_T[-m:])):
    μ_Q = np.inf
```

But the problem is that we can no longer depend on `M_T` to tell us where the "True" `np.nan` are located in our raw time series (i.e., [0.1, 1.2, 9.5, np.nan, 4.0, 17.9])! Right now `M_T` is `[3.6, inf, inf, inf]` and, as we append more and more new data points, this will simply add more and more `np.inf` to the end of `M_T` (i.e., [3.6, inf, inf, inf, inf, inf, inf, ..., inf]`.

Can you see any way to resolve this problem besides having to keep an explicit record of where the `np.nan`/`np.inf` are located in our raw time series?

**Comment by seanlaw** [comment]
@hmcoservit I've been thinking about the current user interface and trying to add NaN/inf support. I think I'm going to have to change the interface (I plan to simplify it) and I will update the tutorial afterward. Hopefully, this change in the interface (I am planning to use OOP) should allow me to add NaN/inf support. 🤞

**Comment by hmcoservit** [comment]
@seanlaw Sure, good luck with that ;)

**Comment by seanlaw** [comment]
Good news. After converting the function over to OOP, the NaN/inf support came pretty naturally and STUMPI now supports NaN/inf!

**Comment by hmcoservit** [comment]
Glad to hear that well done @seanlaw ;)
