### ISSUE TITLE
Convert SCRUMP to OOP

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#205]
Similar to STUMPI and FLUSS, the interface would be simplified

**Comment by seanlaw** [comment]
@mexxexx FYI, that I replaced the generators with a simple object class. I did this because the generators all seemed to need to remember their state. Please see the updated version of the [SCRUMP Tutorial](https://stumpy.readthedocs.io/en/latest/Tutorial_Fast_Approximate_Matrix_Profiles.html) for more details.

**Comment by mexxexx** [comment]
Thank you for letting me know!
