### ISSUE TITLE
Add NaN/inf support to FLOSS

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#206]
Currently, this does not handle NaN/inf for incoming data points

**Comment by JosephTLucas** [comment]
I'm trolling for a potential contribution.  How would you want to handle them?  Fill forward?

**Comment by seanlaw** [comment]
@JosephTLucas Welcome (from Twitter) and thank you for your consideration!

> How would you want to handle them? Fill forward?

IIRC, this is a little bit more complicated but is worth expounding upon. So, unlike typical missing data, we're not simply trying to impute data. If a new data is streamed in and it is a floating point number, then the distance profile computed (using MASS) for the new subsequence that is formed (as a result adding a new data point), and we're all good. However, if that new incoming data point (the literature calls this "ingress" of a new data point) is a `np.nan`/`np.inf` then any subsequence that contains this bad data point should only be allowed to have a distance of `np.inf` (i.e., any subsequence with an `np.nan`/`np.inf` should be "illegal").  However, in practice, to prevent MASS from failing to compute a distance profile, we simply set the value of the new data point to zero after the mean and stddev for the subsequence is computed (which keeps track of the fact that it is an illegal subsequence). This is usually fine for batch jobs but this is a problem for streaming data as we now need to keep track of the long-term presence of this bad/illegal data point and to make sure that we always account for it in our MASS calculation.

To solve this, we should just add a boolean 1D array that is the same length as `self._T` and that gets updated and cross referenced and then we can update the distance profile computed by MASS and the distances of all illegal subsequences to `np.inf` and that should be it. 

I'd be happy to work with you on this!

**Comment by JosephTLucas** [comment]
Thanks for the thorough rundown, Sean.  Let me take a couple days to poke through the code, but I should be able to do that!

**Comment by seanlaw** [comment]
@JosephTLucas Please do not hesitate to share intermediate work through a temporary PR and feel free to ask me anything! I am here to help

**Comment by seanlaw** [comment]
@JosephTLucas I found some time to take a crack at it and there were some additional parts that were needed to make it work. Thank you again for helping us push this one forward and I look forward to seeing other contributions from you!

**Comment by josephlucas-arc** [comment]
Nice work, Sean!

**Comment by JosephTLucas** [comment]
Nice work, Sean!

**Comment by seanlaw** [comment]
It was a team effort!
