### ISSUE TITLE
Specifying package version

### ISSUE THREAD

**Issue by bdice** [TDAmeritrade/stumpy#21]
I was looking into adding support for ReadTheDocs when I realized that there isn't a great way to find the stumpy version programmatically. I would like to know the package version via `stumpy.__version__`, as defined in PEP396. For example:

```python
>>> import stumpy
>>> stumpy.__version__
'1.0.0'
```

https://www.python.org/dev/peps/pep-0396/

This could be accomplished by simply defining a version identifier with the line `__version__ = '1.0'` in the `__init__.py` file.

Also, the `setup.py` file currently defines the version as 1.0. Does this package adhere to some defined version schema like [semantic versioning](https://semver.org/)? If so, it would be good to add a "patch version" (`major.minor.patch`, like 1.0.0) for future releases of the package.

**Comment by seanlaw** [comment]
Yes, you are right. It should’ve been semantic versioning and needs to get fixed. It would be preferable to not have to update `__version__` each time there is a release and, instead, change it in once place and have it propagate everywhere.

**Comment by bdice** [comment]
@seanlaw Right - some packages solve this by writing `from package import __version__` in their `setup.py` script. You may also want to do something similar in the documentation (#22), which needs package version strings. I use the tool `bumpversion` for this task (the [original bumpversion](https://github.com/peritus/bumpversion) is not actively maintained but I find it suffices for my needs - there are also other tools like [versionbump](https://github.com/vortec/versionbump) and an active fork [bump2version](https://github.com/c4urself/bump2version)).

**Comment by seanlaw** [comment]
@bdice I am considering [these options](https://packaging.python.org/guides/single-sourcing-package-version/) right now. I am leaning toward the options that:

1. Require no external dependencies/installations
2. Only need to update the `__version__` in one and only one **obvious** place (I think this should be in `setup.py`
