### ISSUE TITLE
Non-zero Distance Is Returned When Subsequences Are Identical

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#216]
Referenced in [this issue](https://github.com/TDAmeritrade/stumpy/issues/215#issuecomment-658780832)

> A = [4.97e-06, 5.06e-06, 5.17e-06, 5.3e-06, 5.57e-06, 5.14e-06, 5.02e-06]
B = [4.45e-06, 4.48e-06, 4.58e-06, 4.62e-06, 4.97e-06, 5.06e-06, 5.17e-06, 5.3e-06, 5.57e-06, 5.14e-06, 5.02e-06, 4.99e-06, 4.82e-06, 4.82e-06, 4.76e-06, 4.68e-06, 4.55e-06, 4.53e-06, 4.82e-06, 4.95e-06, 5.06e-06]
distance_profile = mass(A, B)
Gives the following output:

> 3.740009893
3.739320259
3.739682072
3.738315396
3.736936713
3.739914170
3.742017905
3.743443068
3.744686636
3.742891930
3.742357546
3.742458550
3.743773765
3.744656994
3.742554742

Even though from index 4 the two arrays will have the exact same values

@mexxexx Any thoughts on what might be causing this? Indeed, the subsequence at `B[4:4+len(A)]` is identical to `A` and it should produce a distance of zero but, instead, it is significantly nonzero. I also tried running this through `stumpy.stump` and it was also giving a non-zero distance.

Ultimately, I computed the mean and stddev by hand and plugged it directly into the standard distance formula:

```
D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
```

Here is when I was able to compute the correct result. Somewhere between `core.mass` and `core._calculate_squared_distance` we are losing information. This seems like a bug

**Comment by mexxexx** [comment]
All values are really small, so I guess that the standard deviation is very small to (smaller than 1e-10), so I suppose the subsequences get treated as if they were constant.Could you multiply both subsequences with 1e6 before calling `core.mass` and see if this produces the expected output?-------- Ursprüngliche Nachricht --------Von: "Sean M. Law" <notifications@github.com>Datum: Mi., 15. Juli 2020, 16:54An: TDAmeritrade/stumpy <stumpy@noreply.github.com>Cc: mexxexx <mihailescu.m@gmx.de>, Mention <mention@noreply.github.com>Betreff: [TDAmeritrade/stumpy] Non-zero Distance Is Returned When Subsequences Are Identical (#216)

Referenced in this issue



A = [4.97e-06, 5.06e-06, 5.17e-06, 5.3e-06, 5.57e-06, 5.14e-06, 5.02e-06]

B = [4.45e-06, 4.48e-06, 4.58e-06, 4.62e-06, 4.97e-06, 5.06e-06, 5.17e-06, 5.3e-06, 5.57e-06, 5.14e-06, 5.02e-06, 4.99e-06, 4.82e-06, 4.82e-06, 4.76e-06, 4.68e-06, 4.55e-06, 4.53e-06, 4.82e-06, 4.95e-06, 5.06e-06]

distance_profile = mass(A, B)

Gives the following output:





3.740009893

3.739320259

3.739682072

3.738315396

3.736936713

3.739914170

3.742017905

3.743443068

3.744686636

3.742891930

3.742357546

3.742458550

3.743773765

3.744656994

3.742554742



Even though from index 4 the two arrays will have the exact same values

@mexxexx Any thoughts on what might be causing this? Indeed, the subsequence at B[4:4+len(A)] is identical to A and it should produce a distance of zero but, instead, it is significantly nonzero. I also tried running this through stumpy.stump and it was also giving a non-zero distance.

Ultimately, I computed the mean and stddev by hand and plugged it directly into the standard distance formula:

D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))



Here is when I was able to compute the correct result. Somewhere between core.mass and core._calculate_squared_distance we are losing information. This seems like a bug

**Comment by seanlaw** [comment]
> All values are really small, so I guess that the standard deviation is very small to (smaller than 1e-10), so I suppose the subsequences get treated as if they were constant.Could you multiply both subsequences with 1e6 before calling `core.mass` and see if this produces the expected output?

Yes, this seems to solve the problem. Since the input values are small, then `σ_Q` and `Σ_T` are small as well and it looks like the `denom = m * σ_Q * Σ_T` in `core._calculate_squared_distance` is below the threshold, which then means that the `denom` gets set to `1e-10`:

```
denom = m * σ_Q * Σ_T
if np.abs(denom) < threshold:  # pragma nocover
    denom = threshold
D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))
```

If I recall correctly, the whole point of doing this was initially to account for cases where the `denom` was zero so that we could avoid a `divide-by-zero` error. Do you have any thoughts on how we might handle this?

**Comment by seanlaw** [comment]
@Jacks349 It appears that you've helped us uncover a unique edge case (so thank you!) that we'll need to fix.

**Comment by mexxexx** [comment]
Actually I'm a bit confused, because in the case of one constant subsequence the squared distance should be set to `m`, or if both are constant (i.e. stddev very small) to `0`.
However, it appears that the resulting squared distance in this case is `2m` (3.74=sqrt(14))

**Comment by seanlaw** [comment]
> okay my guess is the following: the standard deviations are actually greater that the threshold, so the subsequences are not considered constant, otherwise the distance should have been sqrt 7. But denom is smaller than 1e-10, so by setting denom to 1e-10 we actually falsify the result

Exactly!

**Comment by mexxexx** [comment]
```
(QT - m * μ_Q * M_T) / denom)
```
This quantity seems to evaluate to zero when it shouldn't

**Comment by mexxexx** [comment]
One way to solve it would be to say that a subsequence is constant if it's stddev is less than 1e-5. This way, if the denominator is less then 1e-10 at least on of the subsequences is considered constant resulting to a squared distance of either `m` or `0`

**Comment by seanlaw** [comment]
So, if I compute `core.mass(A, A)` then I get the following values:

```
σ_Q = 1.898011849170557e-07
Σ_T = 1.898011849170557e-07
QT = 1.8776829999999996e-10 
μ_Q = 5.175714285714286e-06
M_T = 5.175714285714286e-06
```

**Comment by seanlaw** [comment]
> One way to solve it would be to say that a subsequence is constant if it's stddev is less than 1e-5. This way, if the denominator is less then 1e-10 at least on of the subsequences is considered constant resulting to a squared distance of either m or 0

So, maybe `core._calculate_squared_distance` would look like:

```
    denom_threshold = 1e-10
    stddev_threshold = 1e-5
    if np.isinf(M_T) or np.isinf(μ_Q):
        D_squared = np.inf
    else:
        if σ_Q < stddev_threshold or Σ_T < stddev_threshold:
            D_squared = m
        else:
            denom = m * σ_Q * Σ_T
            if np.abs(denom) < denom_threshold:  # pragma nocover
                denom = denom_threshold
            D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

        if σ_Q < stddev_threshold and Σ_T < stddev_threshold:
            D_squared = 0

    return D_squared
```

**Comment by seanlaw** [comment]
Hmm, using the original data as input `core.mass(A, B)` now produces `[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]`

**Comment by seanlaw** [comment]
Perhaps, it's better just to directly solve the `divide-by-zero` problem with:

```
    threshold = 1e-10
    if np.isinf(M_T) or np.isinf(μ_Q):
        D_squared = np.inf
    else:
        if σ_Q < threshold or Σ_T < threshold:
            D_squared = m
        else:
            denom = m * σ_Q * Σ_T
            if np.abs(denom) == 0:  # pragma nocover
                D_squared = np.inf
            else:
                D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

        if σ_Q < threshold and Σ_T < threshold:
            D_squared = 0

    return D_squared
```

So, compared to the original `core._calculate_squared_distance` we simply check if `denom == 0` and set `D_squared` to `np.inf` if it is. Otherwise, just compute the distance directly. What do you think?

**Comment by seanlaw** [comment]
Or maybe even remove the `threshold` altogether and just compare everything to zero directly:

```
    if np.isinf(M_T) or np.isinf(μ_Q):
        D_squared = np.inf
    else:
        if σ_Q == 0 or Σ_T == 0:
            D_squared = m
        else:
            denom = m * σ_Q * Σ_T
            if np.abs(denom) == 0:  # pragma nocover
                D_squared = np.inf
            else:
                D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

        if σ_Q == 0 and Σ_T == 0:
            D_squared = 0

    return D_squared
```

**Comment by mexxexx** [comment]
Maybe I'm paranoid, by I don't like testing for equality with floats. Under some circumstances the standard deviations might be zero for example.

I would go for this: jvery similar to the first proposal)

```
If sigmaQ and sigmaT < 1e-6:
    D2 = 0
Elif sigmaQ or sigmaT < 1e-6:
    D2 = m
Else
   Normal computation
```

I'm interested how this interested with the new version that uses Pearson correlation

**Comment by seanlaw** [comment]
I'm currently using this:

```
    denom_threshold = 1e-14
    stddev_threshold = 1e-7
    D_squared_threshold = 1e-7
    if np.isinf(M_T) or np.isinf(μ_Q):
        D_squared = np.inf
    else:
        if σ_Q < stddev_threshold or Σ_T < stddev_threshold:
            D_squared = m
        else:
            denom = m * σ_Q * Σ_T
            if np.abs(denom) < denom_threshold:  # pragma nocover
                denom = denom_threshold
            D_squared = np.abs(2 * m * (1.0 - (QT - m * μ_Q * M_T) / denom))

        if (
            σ_Q < stddev_threshold and Σ_T < stddev_threshold
        ) or D_squared < D_squared_threshold:
            D_squared = 0

    return D_squared
```
