### ISSUE TITLE
Add Tutorial on Using MASS to Compute a Distance Profile

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#222]
One of the most common things that a user may want to do is to take a known pattern and to search for it in their time series. Currently, the best way to accomplish this is to use the `mass` function. We should add a tutorial demonstrating this. 

Note that this is fundamentally different/independent from a matrix profile. Looking for a known pattern is far easier than when you don't know of any pattern and it's a completely blind, brute force search.

Here's an [example](https://stackoverflow.com/a/63368206/2955541)

**Comment by seanlaw** [comment]
@Attol8 Would you be interested in helping with this? Of course, I would use a different example than above. I wonder if we could do one with sports data (i.e., can you detect a specific play that a team always likes to execute by tracking the x, y coordinates)?

**Comment by Attol8** [comment]
@seanlaw yeah for sure! I will start digging into this and keep you updated on what I find.

**Comment by Attol8** [comment]
Hi @seanlaw . I had a look around on football ('soccer' if you live in the US, I will never understand why you call it like that :man_facepalming:) as I am a big fan of the sort. I found an amazing [dataset](https://www.nature.com/articles/s41597-019-0247-7) but I couldn't figure how out how to use it with time-series patterns. I will need a bit more time to find a use-case. If you have an idea in mind, please let me know.

On another side, I am making a notebook to explain `mass` with sales data. My idea is to: look at one product's sales data, find a noticeable pattern (e.g. weekend's sales) and look for it in other products' sales data. Although definitely more boring I think it still is a great example.

**Comment by seanlaw** [comment]
That sounds great! I haven't looked at the data so I could be making the wrong assumption here. The only potential issue with something like weekend sales data may be that there might not be enough data points if the data were collected at a daily level (so there would only be two points, one for each fay of the weekend). On the other extreme, we probably don't want a data set where the pattern happens very frequently. The steamgen data set that we use is a good example where the pattern repeats one time (somewhat rare). In the example above, the user is interested in looking for a rare pattern in stock market trading data. Many people would be interested in that! 

I am excited to see what you find.

**Comment by seanlaw** [comment]
There is [this resource](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/) too

**Comment by seanlaw** [comment]
@Attol8 I've updated the tutorial and it is now live! Thank you again for contributing this
