### ISSUE TITLE
FOSSA Deprecation

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#225]
> Hello there!

> On August 15th, 2020 at 08:23 (UTC) your application (FOSSA On-Prem) used its `client_id` and `client_secret` (with the User-Agent NodeJS HTTP Client) as part of a set of query parameters to access an endpoint through the GitHub API:

> https://api.github.com/repositories/2051226

> Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.

> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

>Thanks,
The GitHub Team

@bfattori I am receiving this email again. Should we just remove/comment out FOSSA from STUMPY's continuous integration process and add it back once it has been resolved by FOSSA?

**Comment by bfattori-TDA** [comment]
I am asking FOSSA about this and will let you know when I get a response.

**Comment by seanlaw** [comment]
@bfattori Just following up on this. Have you heard back from the FOSSA team?

**Comment by bfattori-TDA** [comment]
I did hear back from them... their response is: "...the call should be succeeding, it appears to be an error only. PM are aware and will be working to resolve it in line with the GH schedule". I have asked for a resolution approximation from them and expect an answer shortly.

**Comment by seanlaw** [comment]
Perfect. Looking forward to the ETA

**Comment by seanlaw** [comment]
@bfattori Just checking in to see if there were any updates on this

**Comment by bfattori-TDA** [comment]
I was told my FOSSA that this is NOT an error effecting the build, and is only a warning. They say it’s nothing to worry about, and that it will be corrected in future releases so the warning doesn’t display for API messages unless they are true errors.

Thanks,
Brett
