### ISSUE TITLE
Shapelet discovery in boolean time series

### ISSUE THREAD

**Issue by Elpiro** [TDAmeritrade/stumpy#23]
Is the matrix profile a tool that can be used for motif discovery in boolean time series ? I am asking because the only data type accepted in stumpy.mstump() is float (no int or bool). We can workaround it by using float datatype on the 0/1 data.
But is it mathematically correct to compute the matrix profile on this kind of data ?

Usecase example : There are 4 buttons on a webpage that can be clicked in any order and as many times as you want. We could represent the actions of clicking by a multidimensional time series (4 dimensions). The patterns we're looking for are the order in which the buttons are clicked, how they are spaced in time, etc..

**Comment by seanlaw** [comment]
@Elpiro This is a great question and not something that I had considered until now. Based on what I understand from the original publications, I don’t think that this would work mathematically. Essentially, a boolean time series is the same as a time series with categorical values but only with two classes (True and False). The matrix profile needs to calculate a z-normalized Euclidean distance between two subsequences and, for a boolean time series (or categorical time series) it isn’t at all clear what the meaning of the resulting distance would be. So, my instinct would be to advise against it but I am open to discussing it further if you like.

**Comment by seanlaw** [comment]
Perhaps, @mcyeh or @zpzim have thought about this more. I am also curious as to how matrix profile calculations would work for categorical variables (where there are more than two categories). My intuition tells me that it wouldn’t be useful for categorical cases where there isn’t a way to compare the categories but I have also been known to be wrong.

**Comment by Elpiro** [comment]
Maybe the start of an answer, the course about matrix profil here : https://www.youtube.com/watch?v=1ZHW977t070&t=1464s talks about computing the matrix profile on DNA data (at 24:24).

The way they do it is that they convert the categorical data to a real valued time series, by using this set of rules : 
>T1 = 0;
>for i = 1 to length(chromosome) 
>    if chromosomei = A, then Ti+1 = Ti + 2 
>    if chromosomei = G, then Ti+1 = Ti + 1
>    if chromosomei = C, then Ti+1 = Ti  - 1 
>    if chromosomei = T, then Ti+1 = Ti  - 2 
>end

But I feel like it is very case-specific and wouldn't work for a set of 100+ features to create a time series from.

**Comment by seanlaw** [comment]
@Elpiro I don't think I follow the rules (and I'm a trained biochemist... whatever that is worth). It's not clear why one should add/subtract 2 or 1 and why they are mapped to specific values. Any numbers that are assigned in this way necessarily implies a quantifiable relationship between the categories.

To your point, I agree that these types of mappings are very case-specific and I wouldn't feel comfortable providing a universal approach to map categoricals to real valued time series.

**Comment by miktoki** [comment]
A comment:
I have found several use cases where using the matrix profile on arrays with very few available values, eg down to 4 integers yielded very good results, provided large window sizes(*m*), and would also like to see that it would be *possible* to do this without converting the input data to floats.

I agree with @seanlaw that it might be stretching the underlying statistical assumptions a bit far, but I personally think I would leave that decision to the user.

**Comment by seanlaw** [comment]
@miktoki There are several strong concerns here that I don't quite know how to overcome. When computing the matrix profile one needs to correctly compute:

1. The mean for each sliding window. It isn't clear what the mean would be for a window full of integers.
2. The standard deviation for each sliding window. It isn't clear what the stddev would be for window full of integers.
3. The Euclidean distance. It isn't clear how to compute the "distance" for integers, which requires taking a square root.

Also, the speed gain by STOMP/STUMP comes from computing the Euclidean distance and not other forms of distances (i.e., cosine, mahalanobis, manhattan). 

> it might be stretching the underlying statistical assumptions a bit far, but I personally think I would leave that decision to the user.

I don't mean to sound argumentative (so please don't take this as such) but I feel very confident in that the statistical assumptions are completely wrong (binary) if we use integers. As much as I would like to "leave the decision to the user", as a maintainer, we will be left with the repercussions of what API we choose to support. I respect your opinion so thank you for bringing this up. I want for all of us to have continued and thoughtful discussions as we prioritize new features.  So, let's keep this in mind and it would be great to collect a dozen examples (with data) where this application would be warranted.

How does that sound?

**Comment by seanlaw** [comment]
@Elpiro @miktoki Closing this issue for now but feel free to reopen if you think that it would make sense to continue the discussion.
