### ISSUE TITLE
Stumpi with custom metric

### ISSUE THREAD

**Issue by arainboldt** [TDAmeritrade/stumpy#233]
Hi. Awesome library! Really enjoying reading through it! I would like to use the online stumpi method with a unique metric like dynamic time warping. Is this possible given Stump's implementation? If so, what would be the recommended approach?

Thanks

Andrew

**Comment by seanlaw** [comment]
@arainboldt If you don't mind, I'll go ahead and close this issue for now but please feel free to re-open this issue or start a new one if you have any further questions. Thank you
