### ISSUE TITLE
Replace `left`, `right` with `ref` in Unit Tests

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#235]
Currently, when we perform unit test assertions we do something like:

```
left = naive.stump(T, m)
right = stumpy.stump(T, m)

np.assert_almost_equal(left, right)
```

However,`left` and `right` are also overloaded since we have left and right matrix profiles and indices. It has been proposed that we replace `left` with `ref` instead and either replace `right` or just name it appropriately (maybe `comp` for "computed"/"comparison"):

```
ref_mp = naive.stump(T, m)
mp = stumpy.stump(T, m)

np.assert_almost_equal(ref_mp, mp)
```

or

```
ref_mp = naive.stump(T, m)
comp_mp = stumpy.stump(T, m)

np.assert_almost_equal(ref_mp, comp_mp)
```

**Comment by sergiobuj** [comment]
Hello @seanlaw, I would like to help with this issue.

Just by looking briefly at the project, I see 37 files that need to be updated. Here's the list:


![Screen Shot 2020-10-03 at 4 26 55 PM](https://user-images.githubusercontent.com/11920/95002027-4c1a7380-0595-11eb-81b7-a3fdefdebd53.png)

I think the `ref_mp/comp_mp` reads better than `ref_mp/mp`.

How would you prefer I opened the pull requests? I'm not too fond of big PRs, but I can accommodate based on the maintainer's preferences.

I was able to install and run tests fine, so I think I'm ready to start (and the documentation was fine.)

PS: I was looking for issues tagged with "good first issue", and that's how I got to the project.

**Comment by seanlaw** [comment]
@sergiobuj Thank you for your interest in contributing to our project! We can certainly use the help and I am here to assist.

> Just by looking briefly at the project, I see 37 files that need to be updated. Here's the list:

In addition to the 37 files listed above, I think you are missing 3 additional tests (40 in total):

```
tests/mstumped.py
tests/test_mstumped_one_subsequence_inf_self_join.py
tests/test_mstumped_one_subsequence_nan_self_join.py
```

> I think the ref_mp/comp_mp reads better than ref_mp/mp.

Perfect! I agree with your proposal so please go ahead with ref_mp/comp_mp

> How would you prefer I opened the pull requests? I'm not too fond of big PRs, but I can accommodate based on the maintainer's preferences.

I really appreciate your consideration! I've taken a look at whether or not it makes sense but I think that this will be a small enough change (even though it is touching 40 files) so I'm not too concerned as long as the tests pass. However, I wouldn't be opposed to it if you wanted to submit, say, 8 separate PRs that updated 5 test files each and it may make it easier to review. Again, this is only a suggestion and I trust your judgement.

> I was able to install and run tests fine, so I think I'm ready to start (and the documentation was fine.)

Wonderful! Please proceed and know that I am here to help. Thank you again.

**Comment by seanlaw** [comment]
@sergiobuj Just a heads up that I made some minor changes to some of the tests in PR #261 . It shouldn't really affect what you're doing but it may result in some merge conflicts that I can resolve. However, if you haven't gotten started yet then I recommend pulling the newest commit and starting there.

**Comment by sergiobuj** [comment]
@seanlaw thanks for the heads up. I did start with the changes. I will rebase and let you know if I have issues with any conflicts.

**Comment by seanlaw** [comment]
To save you time from trying to figure out what changed, in the `test_gpu_aamp.py` and `test_gpu_stump.py`, I simply swapped the positions of the variables `T_A` and `T_B`.

**Comment by sergiobuj** [comment]
Hey @seanlaw I was able to include only 31 files in that first #263 PR.
I was still thinking about modifying the following files:
![Screen Shot 2020-10-06 at 12 50 03 PM](https://user-images.githubusercontent.com/11920/95241095-eb787a00-07d2-11eb-9785-dcb3662a1083.png)

In those, I'm thinking about changes like this:
```diff
- left = naive.stamp(stream.T_, m, exclusion_zone=zone)
- left_P = left[:, 0]
- left_I = left[:, 1]
- left_left_P = np.empty(left_P.shape)
- left_left_P[:] = np.inf
- left_left_I = left[:, 2]
+ ref_mp = naive.stamp(stream.T_, m, exclusion_zone=zone)
+ ref_P = ref_mp[:, 0]
+ ref_I = ref_mp[:, 1]
+ ref_left_P = np.empty(ref_P.shape)
+ ref_left_P[:] = np.inf
+ left_left_I = ref_mp[:, 2]
```

I don't know if you want to consider the issue complete without changes in those files. Let me know!

**Comment by seanlaw** [comment]
@sergiobuj Ooops! I knew it wasn't all of the files but forgot to re-open so thank you for the reminder.

I think all of your changes look good except for the last line:

```
+ left_left_I = ref_mp[:, 2]
```

I think it should read:

```
+ ref_left_I = ref_mp[:, 2]
```

Otherwise,

**Comment by sergiobuj** [comment]
Thank you! good eye!
