### ISSUE TITLE
Add SKIMP Feature

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#237]
With both GPU and CPU code being fast, it is now reasonable to start tackling how best to choose the window size, `m`. This is a common question amongst users and skimp would be a nice addition. We'll likely want the following functions:

- [ ] `stumpy.stimp`
- [ ] `stumpy.gpu_stimp`

and, maybe, `stumpy.stimped` 

However, one needs to take care that skimp is an anytime algorithm and can be computationally intensive. Having said that, it almost feels like it's a no brainer to combine SKIMP and SCRIMP++

Here is the [skimp site](https://sites.google.com/view/pan-matrix-profile/home?authuser=0)

Here is the [skimp paper](https://www.cs.ucr.edu/~eamonn/PAN_SKIMP%20%28Matrix%20Profile%20XX%29.pdf)

Here is the [skimp data](https://sites.google.com/view/pan-matrix-profile/datasets?authuser=0). Note that this [dishwasher electricity use data set](https://www.dropbox.com/sh/jryalthg0zo4mov/AAD6sJqr5wK1BPyMnU2WAPF6a?dl=0) from the [HIME paper](https://cs.gmu.edu/~jessica/publications/HIME_ICDM17.pdf) may be a better candidate (if we truncate it)

**Comment by MokaPot** [comment]
@seanlaw just reading the paper, what was your rough plan of implementation for this. 

If I'm not mistaken there is no difference between brute force calculation of the PMP and 100% completion of SKIMP, the only benefit comes at early stopping the algorithm. The control of early stopping appears to be from the matlab a visualisation process, which would introduce dependencies and presumably computational overhead to the process.

The binary search tree seems really useful in this visualisation process because it recursively refines the PMP and the user gets a useful feeling for when to stop and they can gauge by increasing time step when to stop.  

Does it however add complexity for the user in stumpy case because presumably there would be a parameter such as tree depth in the implementation? Which to me would make it difficult to calculate the number of runs. Whereas if percentage or number of runs was specified and split evenly over the range of lower - upper values it would achieve a similar concept but more interpretably?

**Comment by seanlaw** [comment]
> what was your rough plan of implementation for this.

I've really only skimmed the paper and I haven't put a lot of thought into it but here are some first impressions (totally up for discussion):
 
1. On the surface, it's a matter of calling the `stumpy.stump` function (or it's GPU/distributed CPU variant) many, many times. I wonder if it's sufficient to write a tutorial that demonstrates how to do scan through different window sizes and call it a day (without adding any new functions)?
2. With the early stopping, it makes sense to wrap this into a light class (see `stumpy/scrump.py` or `stumpy/stumpi.py` or `stumpy/floss.py` for some examples) as this will allow the user to keep track of state (i.e., percent complete) and be able to continue on in an incremental fashion
3. I am not interested in adding more dependencies to STUMPY and, more specifically, I am not interested in adding built-in plotting capabilities.

> If I'm not mistaken there is no difference between brute force calculation of the PMP and 100% completion of SKIMP, the only benefit comes at early stopping the algorithm. The control of early stopping appears to be from the matlab a visualisation process, which would introduce dependencies and presumably computational overhead to the process.

I think this is correct. 

> The binary search tree seems really useful in this visualisation process because it recursively refines the PMP and the user gets a useful feeling for when to stop and they can gauge by increasing time step when to stop.

There is a lot of value in approximating the PMP

> Does it however add complexity for the user in stumpy case because presumably there would be a parameter such as tree depth in the implementation? Which to me would make it difficult to calculate the number of runs. Whereas if percentage or number of runs was specified and split evenly over the range of lower - upper values it would achieve a similar concept but more interpretably?

I agree with you. I'd prefer something interpretable like percent complete and then the option to incrementally `update`. Again, I'd like to see a working notebook example first as it may be "enough" :) 

Of course, I'd like to know what you think as you've probably gone through the paper in more detail than I have (or at least read through it more recently)

**Comment by seanlaw** [comment]
In case it matters #252 might be related to this

**Comment by MokaPot** [comment]
@seanlaw sorry Sean, not forgotten about this just been a bit busy! 

I've started pulling together a notebook, might be able to get something done this weekend fingers crossed.

**Comment by seanlaw** [comment]
Thanks for the note. I know that everyone is busy so there is absolutely no rush at all! My general philosophy is quality over quantity (i.e., speed) so let's get it done right the first time around even if it takes a while. Users will appreciate it (as will I)!

**Comment by seanlaw** [comment]
So, considering that we rarely every want to compute the full pan matrix profile, then we should probably only compute a percentage (maybe 1%) of it. I noticed in [Section III-B](https://www.cs.ucr.edu/~eamonn/PAN_SKIMP%20%28Matrix%20Profile%20XX%29.pdf) that they had referred to using either `STOMP` or `SCRIMP` (which correspond to `stumpy.stump` and `stumpy.scrump`, respectively) for computing the matrix profiles. With `SCRIMP`, we can compute an approximate matrix profile a lot faster and if we pair that up with an approximate pan matrix profile then this could be really great!

**Comment by seanlaw** [comment]
> So, considering that we rarely ever want to compute the full pan matrix profile, then we should probably only compute a percentage (maybe 1%) of it. I noticed in Section III-B that they had referred to using either STOMP or SCRIMP (which correspond to stumpy.stump and stumpy.scrump, respectively) for computing the matrix profiles. With SCRIMP, we can compute an approximate matrix profile a lot faster and if we pair that up with an approximate pan matrix profile then this could be really great! Essentially, we compute each matrix profile to 1% completion using stumpy.scrump and then repeat that for different window sizes in order to populate the pan matrix profile.

Okay, I just realized that I already had this thought before:

> it almost feels like it's a no brainer to combine SKIMP and SCRIMP++
