### ISSUE TITLE
Replace `np.roll` with slice indexing in `stumpy.floss`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#239]
When `np.roll` is used, a copy of the original array is made. This is a problem if `np.roll` is called repeatedly. Instead, it is faster to do:

```
x[:-1] = x[1:]
x[-1] = 14
```

**Comment by manikTharaka** [comment]
Made a [PR](https://github.com/TDAmeritrade/stumpy/pull/241) for this.

**Comment by seanlaw** [comment]
Awesome! Thank you for contributing to our community, @manikTharaka.
