### ISSUE TITLE
Optimize `aampi` and `stumpi` Performance

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#240]
There are several places where the performance of `aampi` and `stumpi` can be improved via NumPy vectorized functions. Currently, we follow pseudocode from the published work which formulates the algorithm via inefficient for-loops. This isn't wrong but there are some speed enhancements that can be had by using NumPy instead.

**Comment by seanlaw** [comment]
@hmcoservit Please look out for this in our upcoming v1.5.1 release. The current v1.5.0 release is quite a bit slower

**Comment by hmcoservit** [comment]
@seanlaw Great thanks looking forward to it
