### ISSUE TITLE
First Time Contributor Guide

### ISSUE THREAD

**Issue by JosephTLucas** [TDAmeritrade/stumpy#246]
In preparation for #Hacktoberfest, I want to put together a post detailing how a new contributor could get involved with stumpy. This will be targeted to new open source contributors or python developers. It'll cover things like setting up a virtual environment, installing dependencies, git flow, tests, and CI/CD. In many ways, it extends [CONTRIBUTING.md](https://github.com/TDAmeritrade/stumpy/blob/master/CONTRIBUTING.md), but makes sure to cover the minutiae that a newcomer may trip on. The idea is to increase publicity and lower any barrier to entry for Hacktoberfest.

As I see it, there are three ways to do this:
1) Extend [CONTRIBUTING.md](https://github.com/TDAmeritrade/stumpy/blob/master/CONTRIBUTING.md) with this detailed post.
2) Write the post in the documentation/tutorial section (Sphinx) and link to it in [CONTRIBUTING.md](https://github.com/TDAmeritrade/stumpy/blob/master/CONTRIBUTING.md).
3) I host it on my own website.

I think the best solution is 2. It doesn't needlessly clutter [CONTRIBUTING.md](https://github.com/TDAmeritrade/stumpy/blob/master/CONTRIBUTING.md) for more experienced contributors, but is available native to the rest of the stumpy content/documentation. Any thoughts or other recommendations (Medium/towards data science, etc)?

Ideally, I'd target a publication date between September 28th and October 2nd.

**Comment by seanlaw** [comment]
> In preparation for #Hacktoberfest, I want to put together a post detailing how a new contributor could get involved with stumpy. This will be targeted to new open source contributors or python developers. It'll cover things like setting up a virtual environment, installing dependencies, git flow, tests, and CI/CD.

@JosephTLucas I really like what you've outlined here! And I agree that option 2 is probably the best option. To keep things a bit simpler, what do you think about throwing all of the information into a single Jupyter notebook (just like our existing tutorials) and then we can add a "Contributing" line item in the docs that points to the notebook. This way, we don't have to deal with formatting and Sphinx nuance.

I'm a bit bandwidth constrained but can at least help socialize it on social media. Even in the absence of #Hacktoberfest, this is probably a good thing to have. Thanks for taking this initiative!

**Comment by JosephTLucas** [comment]
Great, I'll move forward that way. Hopefully this one requires a lighter touch on your part than my other PR!

**Comment by seanlaw** [comment]
@JosephTLucas I made some tweaks but it looks great: https://stumpy.readthedocs.io/en/latest/Contribute.html#

Thank you for posing and completing this issue!
