### ISSUE TITLE
Extend `aamp` Algorithms to `p-norm`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#251]
According to Section 3.4 of the [aamp paper](https://arxiv.org/pdf/1901.05708.pdf), the non-normalized Euclidean distance (i.e., L2-norm) can be extended to `p-norm` which includes Manhattan distance (`p=1`). We can follow the `numpy.linalg.norm` syntax and add an `order` parameter (`ord` is a reserved keyword) that accepts a positive integer for computing the `p-norm`.

**Comment by seanlaw** [comment]
@BBischof Your comment was well taken and it shouldn't be too hard to extend our Euclidean distance implementation to handle L1-norm/Manhattan distance as well. 😄  Thank you for your question!

**Comment by BBischof** [comment]
Great! I might be able to pick this one up myself after my PTO in a few weeks if nobody else has in the mean time. Thanks for the reference, and suggestion.

**Comment by seanlaw** [comment]
@BBischof I've been playing with this today and I was wondering if it makes any sense to allow anything other than Manhattan distance (p=1) and Euclidean distance (p=2)?

**Comment by DanBenHa** [comment]
> @BBischof I've been playing with this today and I was wondering if it makes any sense to allow anything other than Manhattan distance (p=1) and Euclidean distance (p=2)?

I currently have a use case in which it does make sense. I computed the pan matrix profile with non-normalised distances to find conserved patterns at different window sizes. But of course the distance increases the bigger the window size. If I had the p-norm distance set to p=m, I could look at the conservation of patterns irrespective of window size.

**Comment by seanlaw** [comment]
> I currently have a use case in which it does make sense. I computed the pan matrix profile with non-normalised distances to find conserved patterns at different window sizes. But of course the distance increases the bigger the window size. If I had the p-norm distance set to p=m, I could look at the conservation of patterns irrespective of window size.

Very interesting! I briefly looked at implementing this a few months ago but realized that it wasn't as straightforward as the performance degraded when `p != 2` (since the NumPy algorithms seemed to be optimized for `p=2`). I didn't see any obvious way of adding this without reducing performance and adding more complexity to the code base. Note that this would need to be extended to all of the API functions (including `gpu_aamp`).

@DanBenHa would you be interested in exploring this? I can help out where possible. Minimally, we can discuss and learn together if you are up to the challenge?

**Comment by DanBenHa** [comment]
Interested? Yes. But I'd be in favour of first reducing my WIP, i.e. first finishing the other PR. If someone else wants to take a stab at it in the meanwhile, feel free to do so!

It shouldn't be too difficult to modify `aamp.py`. I guess that would involve generalising from Euclidean to Minkowski distance. That would be switching from `np.linalg.norm` to `scipy.spatial.distance.minkowski` and defaulting to `p=2` for Euclidean distance. BTW, Euclidean distance computed using `scipy.spatial.distance.minkowski/euclidean` is faster than `np.linalg.norm` in a quick test that I did. But that's without accounting for Numba's compilation.
Unsurprisingly, if `p` is set to higher values than `2` it's slower, but not infeasibly slow.

I don't have experience with coding for Numba or GPUs, so I don't know how well that translates to those frameworks.

**Comment by vaish-muk** [comment]
take

**Comment by vaish-muk** [comment]
Can I please work on this? is this still open?

**Comment by DanBenHa** [comment]
@vaish-muk 
Sure, go for it!
I'd love to contribute more to this project but am currently busy with other stuff...

**Comment by vaish-muk** [comment]
Created pull request https://github.com/TDAmeritrade/stumpy/pull/532 , please review

**Comment by seanlaw** [comment]
@vaish-muk Welcome to the STUMPY community and thank you for taking the time to contribute!
