### ISSUE TITLE
Add Tutorial on AB-Joins

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#257]
It would be useful to demonstrate the concept of an AB-join and how one should interpret the results.

See page 23-27 in [this presentation](http://poloclub.gatech.edu/idea2016/slides/keynote-keogh-kdd-idea16.pdf)

**Comment by seanlaw** [comment]
@mcyeh By any chance would you happen to have the MFCC data for the "Under Pressure" and "Ice Ice Baby" songs? I would like to reproduce the figure from your paper.

**Comment by mcyeh** [comment]
@seanlaw 
https://sites.google.com/site/icdmstamp

Figure 9 and 10: [code](https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fybzkw5v6h46bv22%2Ffigure9_10.zip%3Fdl%3D1&sa=D&sntz=1&usg=AFQjCNEDp3G8OKGC-Zj5yucpSSCz7WRpRg)

**Comment by MokaPot** [comment]
Hi Sean, 

I've just come across Stumpy after seeing it on Reddit/r/datascience. Looks like a really cool project, I'm working in mechanical engineering and can already think of loads of applications. 

I'm really keen to start giving back to open source, and this is my first foray into contributing. 

I'd like to start with this problem?  Is it best to begin sticking a notebook together with code and markdown which presumably can be replicated into the docs?

Cheers
Ross

**Comment by seanlaw** [comment]
@MokaPot Welcome to the STUMPY community and thank you for taking the time to contribute!

> I'd like to start with this problem? Is it best to begin sticking a notebook together with code and markdown which presumably can be replicated into the docs?

The first thing I would recommend doing is to [read through our existing set of tutorials](https://stumpy.readthedocs.io/en/latest/tutorials.html). Hopefully, this will give you a sense of the overall format and style that we are aiming for. My goal for this tutorial is to keep it reasonably short and to quickly demonstrate that you can find a conserved pattern between two time series. In the notebook, I would like to reproduce Figure 9 and Figure 10 from the [Matrix Profile I paper](https://www.cs.ucr.edu/~eamonn/PID4481997_extend_Matrix%20Profile_I.pdf). After cloning the STUMPY repo, If you take a look at [`docs/Tutorial_AB_Joins.ipynb`](https://github.com/TDAmeritrade/stumpy/blob/master/docs/Tutorial_AB_Joins.ipynb), I've initiated a notebook that retrieves the data and the next steps would be to plot each time series, compute the AB-join using `stumpy.stump`, and then plot the top motif that is identified in the matrix profile.

As a first pass, don't worry so much about getting everything right and, instead, just focus on writing simple minimalistic code to reproduce the plots and then submit a pull request. This way, you can get quick feedback. Let me know what you think and know that I am here to help!

**Comment by MokaPot** [comment]
@seanlaw Done! see pull request #281
