### ISSUE TITLE
Correct AB-Join Definition

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#258]
Currently, for

```
stumpy.stump(T_A, m=m, T_B=T_B)
```

This takes `T_B` and annotates it with `T_A`. While this is clearly documented, it is somewhat counterintuitive given that `T_A` is the required argument and, additionally, the published definition states that an AB-join is:

> for every subsequence in a time series A, record information about its nearest neighbor in time series B. Note that
A and B can be of different lengths, and that in general, AB-join ≠ BA-join.

and

> For every subsequence in A, find its closest subsequence in B

Of course, the user could simply swap the inputs and end up with the the AB-join that they were looking for?

So, I think it would be worth while fixing this in STUMPY so that the definitions are aligned with the code. This will require 
- [ ] swapping the `T_A`/`T_B` where ever there is an AB-join
- [ ] updating the naive implementation when testing AB-joins
- [ ] update the Shapelet and Time Series Chains tutorials (the latter has documentation pulled up that needs to be re-run)
- [ ] update docstrings so that the definition matches the above literature

**Comment by seanlaw** [comment]
@codyschank I know that you were performing AB-joins before and I just wanted to let you know that this change will affect you

**Comment by seanlaw** [comment]
@hmcoversit FYI, that I will be doing this to all of the `aamp`-related functions too. I'm guessing that you are only performing self-joins and may not be affected but wanted you to be aware that this is coming.

**Comment by hmcoservit** [comment]
@seanlaw Thanks for the head up
