### ISSUE TITLE
Add Tutorial Data to Zenodo

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#270]
All of our tutorials reproduce published work by downloading them from the original source. These sources are typically on Google sites and may eventually become stale or unsupported. It would be best to back them up on Zenodo and have one consistent place to download the data from. Then, we can update our tutorials to point to Zenodo instead.

**Comment by seanlaw** [comment]
In issue #107 @MokaPot said:

> You mentioned Zenodo in another issue? That seems like a good way to do this? Could preprocess the data into clean pandas friendly csvs, upload and the just call url from read_csv? Guess it would be good to establish some structure upfront?

Moving this part of the conversation here 😄 

This Zenodo idea is still swimming around in my head and isn't well formed yet. What I'm trying to avoid is storing data in a Github repository but I am also concerned that the original data sources from the published papers may one day disappear. I tend to be a purist when it comes to "raw data" and I prefer retrieving them from the source and showing the pre-processing in code (there are tradeoffs to this but I prefer to be transparent where possible). 

I've actually tried creating rough CSVs of only the un-processed data that we need in our [Github Wiki](https://github.com/TDAmeritrade/stumpy/wiki) (see the list on the right of this page). I was hoping that we could point our Tutorials there. However, I found that Github was actually limiting the number of times of text and truncating/deleting some of the data so this turned out to be a bad choice. So, we'll need a better alternative.

As you are aware, in our available Tutorial notebooks, we are currently retrieving data from the original data source and reading it into a Pandas DataFrame. I would like to store the un-processed data as a CSV into Zenodo. What's unclear to me is the rights to maintain that data (not ownership of the data) can be managed. Essentially, if you or somebody else uploads the data, how can I maintain it (from an authorization perspective)? Perhaps, there is a way for me to create a "community" and then give other people read/write access? This part is still unclear to me.

Until we figure it out, I don't mind having the Tutorial notebooks download the data from its original source. Perhaps, you had some ideas or thoughts?

**Comment by MokaPot** [comment]
Yep looks like you can be the community curator you then accept/reject data or other media. However there is currently a long standing issue on co-curating or transfering  (https://github.com/zenodo/zenodo/issues/810) which doesn't seem to have gained much traction. 

The only other alternative I know of off the top of my head is kaggle, but I'm sure there are plenty of other options. I'll keep an eye out.

I guess the only garenteed method is something like hosting on AWS publicly available s3 buckets (or equivalent) but that has cost and management implications. For now I'll at least keep a local copy of the 100q zip and run the tutorials up to ingestion. I'll try and do that over the next few days.

**Comment by seanlaw** [comment]
@MokaPot Thank you for looking into this and pushing me in the right direction! I don't mind being the curator. Here is a link for [uploading data](https://zenodo.org/communities/stumpy/). For now, I think what we'd want to do is to only upload data that is currently being used in our [public tutorials](https://stumpy.readthedocs.io/en/latest/tutorials.html) (i.e., not any tutorials that are still a work-in-progress). Again, this is meant to serve as a backup in case the other sources disappear. For example, if a tutorial retrieves data like this:

```
colnames = ['drum pressure',
            'excess oxygen',
            'water level',
            'steam flow'
           ]

context = ssl.SSLContext()  # Ignore SSL certificate verification for simplicity
url = 'https://www.cs.ucr.edu/~eamonn/iSAX/steamgen.dat'
raw_bytes = urllib.request.urlopen(url, context=context).read()
data = io.BytesIO(raw_bytes)
steam_df = pd.read_csv(data, header=None, sep="\\s+")
steam_df.columns = colnames
steam_df.head()
```

Then, we'd want to write the mostly unprocessed `steam_df` as a csv file with obvious/appropriate headers.

**Comment by MokaPot** [comment]
@seanlaw I've added the first for approval at https://zenodo.org/record/4273921#.X6_YO3X7TNw . I'll wait for feedback before sticking the rest in. 

They've been generated with https://github.com/MokaPot/stumpy_help/blob/main/stumpy_zenodo_dataset_generator.ipynb 

I've attributed the data to the original authors, referencing the UCR authors too, you end down a bit of a rabbit hole with some trying to find the original author :smile:.

I guess for future tutorial contributors a contributor guide on this would be useful because there are alot of fields.

**Comment by seanlaw** [comment]
Thanks, @MokaPot! I am currently at a conference but I will take a look as soon as I find some time

**Comment by seanlaw** [comment]
> @seanlaw I've added the first for approval at https://zenodo.org/record/4273921#.X6_YO3X7TNw . I'll wait for feedback before sticking the rest in.

Everything looks good to me! Thank you again for contributing this. I think it will greatly add to our long-term stability. For the steamgen dataset, I downloaded the data and compared it with the original and they match! Yay!

> They've been generated with https://github.com/MokaPot/stumpy_help/blob/main/stumpy_zenodo_dataset_generator.ipynb

These look great. I especially like/appreciate the `index=False` when writing the CSV

> I've attributed the data to the original authors, referencing the UCR authors too, you end down a bit of a rabbit hole with some trying to find the original author 😄.

It is always nice to attribute the primary authors and I'm sure others will appreciate it too.

> I guess for future tutorial contributors a contributor guide on this would be useful because there are alot of fields.

Yes, perhaps we should create a new issue for this? It is a "nice to have" so there is no rush.

**Comment by seanlaw** [comment]
@MokaPot Can you please add this [additional dataset](https://stumpy.readthedocs.io/en/latest/Tutorial_Pattern_Searching.html#Have-You-Seen-This-Pattern?):

```
Q_url = 'https://www.cs.unm.edu/~mueen/carpet_query.txt'
Q_raw_bytes = urllib.request.urlopen(Q_url, context=context).read()
Q_data = io.BytesIO(Q_raw_bytes)
Q_df = pd.read_csv(Q_data, header=None, sep='\s+', names=['Acceleration'])
```

**Comment by MokaPot** [comment]
@seanlaw Sorry, missed that one! They are all on now.

**Comment by seanlaw** [comment]
No worries! Would you mind renaming your data generator notebook (above) to `Zenodo.ipynb`, move `context = ssl.SSLContext()  # Ignore SSL certificate verification for simplicity` to the initial import section/cell so it is only called once, put the file in the `stumpy/docs/` directory, and submitting a PR? I think that will be a good reference resource to include in STUMPY
