### ISSUE TITLE
Add Time Series Snippets

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#283]
> Perhaps the most basic query made by a data analyst confronting a new data source is “Show me some representative/typical data.” Answering this question is trivial in many domains, but surprisingly, it is very difficult in large time series datasets. The major difficulty is not time or space complexity, but defining what it means to be representative data in this domain. In this work, we show that the obvious candidate definitions: motifs, shapelets, cluster centers, random samples etc., are all poor choices. Thus motivated, we introduce time series snippets, a novel representation of typical time series subsequences. Beyond their utility for visualizing and summarizing massive time series collections, we show that time series snippets have utility for high-level comparison of large time series collections.

The original published paper is [here](https://www.cs.ucr.edu/~eamonn/Time_Series_Snippets_10pages.pdf)

The supporting website is [here](https://sites.google.com/site/snippetfinderinfo/)

Snippets require `MPdist_vect` which has now been implemented in `stumpy.mpdist._mpdist_vect` and `stumpy.aampdist._aampdist_vect`

**Comment by keua** [comment]
Hello, thanks for the awesome work you've done. I have a question, Is the time series snippet functionality already implemented how can I use it if it is implemented, is there any documentation about it?

Thanks in advance for your answer.

**Comment by seanlaw** [comment]
> Hello, thanks for the awesome work you've done. I have a question, Is the time series snippet functionality already implemented how can I use it if it is implemented, is there any documentation about it?
> 
> Thanks in advance for your answer.

Thank you for your interest. This has not been implemented but we certainly welcome community contributions!

**Comment by keua** [comment]
> > Hello, thanks for the awesome work you've done. I have a question, Is the time series snippet functionality already implemented how can I use it if it is implemented, is there any documentation about it?
> > Thanks in advance for your answer.
> 
> Thank you for your interest. This has not been implemented but we certainly welcome community contributions if you are interested in submitting a pull request!

Thanks for your answer and sorry for the delay,
I don't really have deep knowledge of the matrix profile so I don't feel yet confident about implementing this functionality, but thanks again for your answer and If I get more involved with the MP in the future I will try to come back and contribute.

**Comment by seanlaw** [comment]
> Thanks for your answer and sorry for the delay,
> 
> I don't really have deep knowledge of the matrix profile so I don't feel yet confident about implementing this functionality, but thanks again for your answer and If I get more involved with the MP in the future I will try to come back and contribute.

@keua I was wondering if you could describe your particular use case and how you think snippets would be helpful?

**Comment by keua** [comment]
> > Thanks for your answer and sorry for the delay,
> > I don't really have deep knowledge of the matrix profile so I don't feel yet confident about implementing this functionality, but thanks again for your answer and If I get more involved with the MP in the future I will try to come back and contribute.
> 
> @keua I was wondering if you could describe your particular use case and how you think snippets would be helpful?

Hello @seanlaw ,
Basically I work with vehicle traffic data, and I need to interpolate a road network, for that I use a spatial interpolator. so I'm looking for trends in long time series of vehicle traffic data to better characterize the road network. One of the methods was just averaging (i.e. day of the week) the historical data of the available sensors, but I research a little bit and the matrix profile snippets seems to be a nice alternative to identify such trends. I performed some experiments and when you compare the historical average against the snippets there isn't a big difference, maybe because of the nature of the data, moreover the snippets seemed a little bit noisy since my data has a lot of gaps and I don't really yet know how to handle them.

Thanks for your answers
