### ISSUE TITLE
Refactor `ostinato._get_central_motif`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#285]
Currently, `ostinato._get_central_motif` contains quite a fair amount of branching logic. It would be good to try and simplify this

**Comment by seanlaw** [comment]
@DanBenHa I spent some time re-defining all of the variables so that they were a little bit more verbose and also consistent with the rest of the code base. Additionally, I refactored the various functions and adjusted the unit tests. They appear to be a bit cleaner now and I am pretty happy with the result. Finally, I updated the tutorial and, unfortunately, had to remove the Japanese characters from the plot since it required installing a font. I think it'll be fine.

Thanks again for this contribution!

**Comment by DanBenHa** [comment]
@seanlaw Thanks for taking the time! I agree, it looks nicer now. I also like the new wording in the tutorial where you changed it. Much clearer! Don't worry about the Japanese characters - I had already expected CJK fonts to be problematic and perceived this more as a fun exercise for myself ;)
