### ISSUE TITLE
Add MPdist Tutorial

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#290]
Now that `mpdist` has been implemented, it would be useful to have an `mpdist` tutorial

The paper is [here](https://ueaeprints.uea.ac.uk/id/eprint/69244/1/ICDM_2018_Shaghayegh.pdf)

The supporting website is [here](https://sites.google.com/site/mpdistinfo/)

The goal of this tutorial would be to reproduce Figure 5 from the paper - An [initial tutorial has been started here](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_MPdist.ipynb)

**Comment by seanlaw** [comment]
Here is the code for retrieving the data for Figure 5

```
%matplotlib inline

from scipy.io import loadmat
import pandas as pd
import matplotlib.pyplot as plt
from zipfile import ZipFile
from urllib.request import urlopen
import io
import ssl

context = ssl.SSLContext()  # Ignore SSL certificate verification for simplicity

plt.rcParams["figure.figsize"] = [20, 6]  # width, height
plt.rcParams['xtick.direction'] = 'out'

fzip = ZipFile(io.BytesIO(urlopen("https://sites.google.com/site/mpdistinfo/home/words_dendrogram.zip?attredirects=0&d=1").read()))
mat = fzip.extract("words_dendrogram/LisaBeth/MaryBethAnhLisa_data.mat")
data = loadmat(mat)

dfs = {}
for i in range(data['XSsY4'][0].shape[0]):
    name = data['XSsY4'][1][i][0]
    df = pd.DataFrame(data['XSsY4'][0][i].flatten(), columns=[name])
    dfs[name] = df
```

and then to plot the data:

```
fig, axs = plt.subplots(len(dfs), sharex=True, gridspec_kw={'hspace': 0})
plt.suptitle('Names', fontsize='30')

for i, (k, v) in enumerate(dfs.items()):
    ymax = v.max()
    axs[i].set_xlim(0, 300)
    axs[i].plot(v)
    axs[i].text(250, 0.99 * ymax, k, color="black", fontsize=20)
```

**Comment by seanlaw** [comment]
It may also be useful to demonstrate how to combine `mpdist` with clustering (maybe hdbscan?)

**Comment by davidrhallartificialeducation** [comment]
@seanlaw going to start taking a look at this today!

**Comment by seanlaw** [comment]
@davidrhallartificialeducation I'd first recommend going over all of the existing [STUMPY tutorials](https://stumpy.readthedocs.io/en/latest/tutorials.html). For consistency, we try to use the same headings and writing style where possible (I can help with this). Let me know if you have any questions, comments, or concerns

**Comment by asifmallik** [comment]
@seanlaw I think the wrong paper is linked here, it should be [this](https://ueaeprints.uea.ac.uk/id/eprint/69244/1/ICDM_2018_Shaghayegh.pdf).

**Comment by seanlaw** [comment]
> I think the wrong paper is linked here, it should be this.

Updated. Thank you @asifmallik!

**Comment by asifmallik** [comment]
Hi @seanlaw , I would like to work on this issue

**Comment by ksetdekov** [comment]
> Now that `mpdist` has been implemented, it would be useful to have an `mpdist` tutorial
> 
> The paper is [here](https://ueaeprints.uea.ac.uk/id/eprint/69244/1/ICDM_2018_Shaghayegh.pdf)
> 
> The supporting website is [here](https://sites.google.com/site/mpdistinfo/)
> 
> The goal of this tutorial would be to reproduce Figure 5 from the paper - An [initial tutorial has been started here](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_MPdist.ipynb)

Hi! is it possible to share the words_dendrogram.zip file somewhere? This website is down and the tutorial no longer works.

**Comment by seanlaw** [comment]
> > Now that `mpdist` has been implemented, it would be useful to have an `mpdist` tutorial
> > The paper is [here](https://ueaeprints.uea.ac.uk/id/eprint/69244/1/ICDM_2018_Shaghayegh.pdf)
> > The supporting website is [here](https://sites.google.com/site/mpdistinfo/)
> > The goal of this tutorial would be to reproduce Figure 5 from the paper - An [initial tutorial has been started here](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_MPdist.ipynb)
> 
> Hi! is it possible to share the words_dendrogram.zip file somewhere? This website is down and the tutorial no longer works.

Please see response [here](https://github.com/TDAmeritrade/stumpy/discussions/835#discussioncomment-5661483)
