### ISSUE TITLE
Replace `scipy.signal.convolve` with `scipy.signal.oaconvolve`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#304]
It was brought to my attention that, in some scenarios, `scipy.signal.oaconvolve` may perform better than `scipy.signal.convolve` and so it may be worth investigating this and replaced the FFT call in `stumpy.core.py`

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.oaconvolve.html

A series of past FFT performance tests can be found in [this PR](https://github.com/TDAmeritrade/stumpy/pull/279#issuecomment-722478323)

**Comment by seanlaw** [comment]
@DanBenHa Are you familiar with `oaconvolve`?

**Comment by drorspei** [comment]
Related:
https://github.com/scipy/scipy/issues/12993

**Comment by DanBenHa** [comment]
@seanlaw Nope, I wasn't aware of `oaconvolve`. Seems like a good addition/replacement. I wonder why `choose_conv_method` doesn't consider it 🤔 Maybe too new?

**Comment by seanlaw** [comment]
@drorspei I understand that`oaconvolve` may be faster in different scenarios and the SciPy PR that you referenced is to have `oacconvolve` be automatically selected for those scenarios. Is that correct?

If so, then I am thinking that it make sense for us to just wait for it to land in `scipy.signal.convolve` naturally and this ends up being a no-op. Basically, it is okay for STUMPY to be "fast enough" for the majority of cases and FFT is only called once at the beginning of a run to initialize the matrix profile calculation and then FFT is not used for the core, fast computation. @drorspei  Your guidance on this would be appreciated!

**Comment by seanlaw** [comment]
I will keep an eye on this as I don't think there is anything to do aside from waiting for `scipy` to adopt this so closing this for now
