### ISSUE TITLE
How can one handle tuple values?

### ISSUE THREAD

**Issue by Darveesh** [TDAmeritrade/stumpy#305]
If my time series has more than 1 value, say a geolocation - i.e. lat and long - over time, can you provide an example or how to use STUMPY to analyze the the time series signal?

**Comment by seanlaw** [comment]
It depends on what you are trying to accomplish. The first thing you could try is to compute the matrix profile for each variable independently from the other using `stumpy.stump`. Chances are, if no motifs exists in a single dimension then they are not likely to exist in multiple dimensions.

Alternatively, one could compute what is called a "multi-dimensional matrix profile" using `stumpy.mstump` but we do not currently have a tutorial for this (it is still a work in progress and a lot more complex than you'd think and so support may be limited). We recommend going through [this paper](https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf) before venturing down this path as it can be rather nuanced.

What have you tried already? What are you trying to accomplish?

**Comment by seanlaw** [comment]
Additionally, if you haven't had a chance to look through then, you may find some useful ideas in our [tutorials](https://stumpy.readthedocs.io/en/latest/tutorials.html).

**Comment by Darveesh** [comment]
An example for what I am trying to accomplish is analyzing a bus route.  A bus takes the same route daily so there is periodicity to the data (lat/lon of the bus tracked over time every day).  I'd like to identify when the bus "deviated" from its route.  This could be getting stuck (say in traffic) or perhaps even taking an alternate route (due to detour).  The data I have is a time series data of lat/lon over a whole year.  Hope that helps explain what I am trying to accomplish.  

In this vein, maybe each variable could be treated independently?  I would think a delay does affect both variables, same with taking a detour.  So ideally perhaps this is multi-variate analysis and really suited for ```stump.mstump```,  but I can fake it with single variable analysis due to the dependency between the two variables.  

Eventually though I suspect I need ```stumpy.mstump```.  Only because I imagine I will introduce other (related) signals, for example the causes for the diversion. So if you get to polishing up ```stumpy.mstump``` you got a customer here.  :)

Thank you again for the guidance.

**Comment by seanlaw** [comment]
> An example for what I am trying to accomplish is analyzing a bus route. A bus takes the same route daily so there is periodicity to the data (lat/lon of the bus tracked over time every day). I'd like to identify when the bus "deviated" from its route. This could be getting stuck (say in traffic) or perhaps even taking an alternate route (due to detour). The data I have is a time series data of lat/lon over a whole year. Hope that helps explain what I am trying to accomplish.
> In this vein, maybe each variable could be treated independently? I would think a delay does affect both variables, same with taking a detour. So ideally perhaps this is multi-variate analysis and really suited for stump.mstump, but I can fake it with single variable analysis due to the dependency between the two variables.
> Eventually though I suspect I need stumpy.mstump. Only because I imagine I will introduce other (related) signals, for example the causes for the diversion. So if you get to polishing up stumpy.mstump you got a customer here. :)
> Thank you again for the guidance.

This is a pretty interesting example! So, technically, `stumpy.mstump` does compute the multi-dimensional matrix profile correctly (note that it isn't simply stacking individual 1-d matrix profiles on top of each other!!). In your case, you feed in a 2D time series (`lat`/`lon`) and then compute the multi-dimensional matrix profile and assess the profile in the second dimension (i.e., it must consider both `lat` and `lon`). Then, if they take a detour then you might get a "high" value in your matrix profile. What's important to keep in mind is that STUMPY is comparing all "trips" with all other trips. So, if your bus had taken the same detour in the past then any upcoming detours that follow the same (past) detour path will "match" and therefore result in a small matrix profile value. So, if you want to detect deviations then you'd want to first start with a clean dataset where the bus NEVER took a detour and use that as your "normal" (one week worth of normal data should be enough). Then, you might append (or concatenate) new data to the normal data and assess from the matrix profile for the "new" part of the data has low values. If the newly appended data is a "never-seen-before" in the normal data then it will result in a higher matrix profile value. Then, each day, you remove yesterday's "new" data and replace it with today's "new" data (while never changing your "normal" data).

I hope that helps.

**Comment by seanlaw** [comment]
Btw, is this bus data publicly available? If so, I'd like to take a look at it to see if it could serve as an example in our tutorial.

**Comment by Darveesh** [comment]
Ok I'll take a look at mstump.   Is there a tutorial for out I can use as guidance?  

Ps: The bus data I have access to seems to come from a few sources and not a single public source.  If I can share any of my data will let you know.

**Comment by seanlaw** [comment]
There is [this tutorial](https://github.com/TDAmeritrade/stumpy/blob/master/docs/Tutorial_Multidimensional_Motif_Discovery.ipynb) that is incomplete and still evolving and so it might generate more questions than answers. I still recommend reading the original paper mentioned above.
