### ISSUE TITLE
Incorrect `mstump`/`mstumped` Matrix Profile Orientation

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#308]
While `mstump`/`mstumped` correctly compute the matrix profile, the dimensions should be swapped. Currently, the first dimension corresponds to the subsequence length while the second dimension corresponds to the dimensions of the matrix profile. This is inconsistent with the [original Matrix Profile VI paper](https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf), which has the dimensions as rows and subsequence length as the columns. Essentially, the current matrix profile and the matrix profile indices being output need to be transposed!  This should be corrected in the tutorial as well so that everything is consistent with the paper.

**Comment by seanlaw** [comment]
@darveesh @geoheil @mexxexx 

I just wanted to warn you of this upcoming (breaking) change!

**Comment by geoHeil** [comment]
@seanlaw many thanks
