### ISSUE TITLE
Please cite and acknowledge the matrixprofile-ts and matrixprofile library

### ISSUE THREAD

**Issue by tylerwmarrs** [TDAmeritrade/stumpy#310]
First off, I want to state that capabilities you provide in STUMPY is great and I do not want you to take offense to the following statements. We at MPF have noticed a trend of some derivative works within your library without ever providing credit to us. This started happening early on when the "matrixprofile" Python library was originally hosted at Target as "matrixprofile-ts". The papers released by the Keogh lab provide the fundamental algorithms to get an answer and we at MPF spent a lot of time translating the paper to be useful to the community. While you may claim that your work is original, there are several instances of which you quickly follow our release date with an implementation VERY similar to ours.

Since our licenses for code are Apache 2, you **MUST** cite/acknowledge our work. There are enough cases of plagiarism in academia and open-source already, please do not become the majority and do the right thing here.

All that we ask at MPF is that you:

**Please add the following to your acknowledgements section in your README:**

The work of STUMPY was inspired by [matrixprofile-ts](https://github.com/target/matrixprofile-ts) and [matrixprofile](https://github.com/matrix-profile-foundation/matrixprofile).

Note that we will gladly direct the community to your package when it makes sense (out of core computations and other features we do not offer).

**Comment by vanbenschoten** [comment]
@seanlaw Another reason we're asking for acknowledgement is that your original JOSS paper did not cite the 'matrixprofile-ts' library as it should have. The [JOSS paper criteria](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) clearly states that each paper must contain _"A list of key references, including to other software addressing related needs."_

matrixprofile-ts was released to the public in [November 2018](https://tech.target.com/2018/12/11/matrix-profile.html), while your JOSS paper publication (and original STUMPY launch) happened in late spring/early summer of 2019. At the time, matrixprofile-ts had over 20,000 downloads and 300+ GitHub stars, so it definitely met the qualification of "addressing related needs". We even cited STUMPY in our later MPA JOSS publication; all we're asking is that you do the same.

**Comment by bfattori-TDA** [comment]
As the manager of the Open Source Program Office at TD Ameritrade, I am responsible to investigate claims about our open source software releases. We take authorship very seriously and at this time have no reason to question the origins of this work. For this reason, we will be closing this issue and the corresponding PR.
