### ISSUE TITLE
Update Fast Pattern Searching Tutorial with `motifs.py` Function

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#358]
After the `motifs.py` module is merged, it would be useful to update our [Fast Pattern Searching Tutorial](https://stumpy.readthedocs.io/en/latest/Tutorial_Pattern_Searching.html) to demonstrate the new capability. 

Depending on the name of the function that we settle on, we might rename the title of the tutorial to be consistent.

**Comment by mexxexx** [comment]
I noticed that there are two notebooks (one under /notebooks one under /docs). Which one do I have to edit?

**Comment by seanlaw** [comment]
> I noticed that there are two notebooks (one under /notebooks one under /docs). Which one do I have to edit? Edit: Nevermind, I realized that the ones under /notebooks are just links.

Good observation! The `notebooks` directory is for MyBinder to render interactive Jupyter notebooks and they need to be in that directory. I didn't want to have to copy over files from `docs` every time and update them in both places so I created a symbolic link instead

**Comment by seanlaw** [comment]
@mexxexx I just wanted to see if you've been able to make any progress on this? It'd be great to include this in our upcoming v1.9.0 release!

**Comment by seanlaw** [comment]
I am hoping to get it out some time in the beginning of June if that would be okay with you?

**Comment by mexxexx** [comment]
Yes, I guess until then I can get it done :) I'll create a pull request as soon as possible
