### ISSUE TITLE
examples notebooks are empty?

### ISSUE THREAD

**Issue by Sandy4321** [TDAmeritrade/stumpy#39]
examples notebooks are empty?

https://github.com/TDAmeritrade/stumpy/tree/master/notebooks

**Comment by seanlaw** [comment]
The contents are actually symbolic links to the Tutorials in the docs directory. To see the tutorials, please go to [https://stumpy.readthedocs.io/en/latest/tutorials.html](https://stumpy.readthedocs.io/en/latest/tutorials.html)
