### ISSUE TITLE
Improve Snippet function

### ISSUE THREAD

**Issue by Ninimama** [TDAmeritrade/stumpy#399]
As I was working with snippets, I noticed the three following issues:

1- Apparently the indices of the snippet start exactly at the multiplies of m, which may not be the case for some data. 

2- The function provides only one profile per snippet. However, that snippet repeats throughout the whole time series as higher fraction means it has been repeated more. So, it should be useful to have that information in the output, where I can see all the profiles (the starting index) of each snippet.

3- The fraction output is not sorted. I think it is better to sort it in descending order and accordingly provide the other outputs for the same order.

**Comment by Ninimama** [comment]
@seanlaw 
What do you think? I can start working on this in parallel to working on the snippet tutorial.

**Comment by seanlaw** [comment]
@Ninimama If it's okay with you, I'd like to move this over to the discussion section as I think it would be healthy/useful to discuss/debate each of the points above.

**Comment by Ninimama** [comment]
@seanlaw 

Sure. I think it is good to move 1 & 3 to discussion. However, if you would like to reproduce the results of the paper, I think the snippet function should produce the indices of a set of subsequences similar to each snippet (e.g: check out Fig 24 of the paper or Fig 19).

**Comment by seanlaw** [comment]
@Ninimama I haven't looked into this part much so maybe you can help me understand how the indices are calculated? It appears that it has do with finding cross-over points.

**Comment by Ninimama** [comment]
This is part of the snippet code. If I understand correctly, mask contains the indices of distance profile corresponds to the snippet. (And, by summing over that, we calculate the fraction).

![image](https://user-images.githubusercontent.com/38519522/120752671-5051b480-c4c7-11eb-8d66-a30ec5274817.png)

So, all we need to do is to return those indices. (Am I missing something?)

Of course there might be some overlaps between one subsequence to the next, but we don't care about that. We just need to return those indices. So, coloring them should give us the Fig. 24 of  the paper.

Please feel free to close this one and move the questions to the discussion.
