### ISSUE TITLE
Add syntax highlighting for tutorial code blocks

### ISSUE THREAD

**Issue by alvii147** [TDAmeritrade/stumpy#409]
Tutorials currently don't support syntax highlighting for code blocks. Adding this will significantly improve readability for tutorials.

Tutorials are generated using [Jupyter Notebook Tools for Sphinx](https://nbsphinx.readthedocs.io/en/0.8.6/), which does seem to support [syntax highlighting options](https://nbsphinx.readthedocs.io/en/0.6.0/installation.html#Pygments-Lexer-for-Syntax-Highlighting).

**Comment by seanlaw** [comment]
@alvii147 Assuming that you have the correct environment setup (see `environment.yml` in root STUMPY directory), then you should be able to make the docs by executing the `docs/setup.sh` script and then see the documentation in your browser.

Based on the syntax highlighting notes above, I wonder if it is sufficient to simply add `IPython` to the `docs/requirements.txt`?

**Comment by alvii147** [comment]
Yepp it looks like that might be all we'd need to do. I'm going to give that a shot and let you know.

Unfortunately I'm using a windows machine so I can't run make. I'm gonna try doing it in a virtual machine. I'll keep you updated.

**Comment by seanlaw** [comment]
Thank you for your work! The PR is merged.
