### ISSUE TITLE
Stumpy settings not imported correctly

### ISSUE THREAD

**Issue by mexxexx** [TDAmeritrade/stumpy#411]
I noticed in `motifs.py` that the `STUMPY_EXCL_ZONE_DENOM` is not imported correctly. Namely, if the user changes it, it is not recognized in the function.

Steps to reproduce: In `test_motifs.py::test_match` add the following lines before computing `right`:
```
from stumpy import config
config.STUMPY_EXCL_ZONE_DENOM = np.inf
```
and step with a debugger into the function `match` and inspect the value of `STUMPY_EXCL_ZONE_DENOM`. It will be `4` and not `np.inf` (or `excl_zone` which should be `0` but is `1`).

The problem lies in how the variables are imported: (in `motifs.py`)
``` 
from .config import STUMPY_EXCL_ZONE_DENOM
...
excl_zone = int(np.ceil(m / STUMPY_EXCL_ZONE_DENOM))
``` 
should be changed to
``` 
from . import config
...
excl_zone = int(np.ceil(m / config.STUMPY_EXCL_ZONE_DENOM))
``` 

Then the user changes persist. I suppose this is python behavior and when importing constants they are imported as a copy, so overwriting the original values does not change what is visible to the module.

I suppose the same issue applies to other modules and user settings too.

**Comment by seanlaw** [comment]
Oooh, thanks for catching that! This means that it needs to be `config.STUMPY_EXCL_ZONE_DENOM` everywhere

I can fix this

**Comment by seanlaw** [comment]
I wrote a quick unit test:

```
import numpy as np
from stumpy import config


def test_change_excl_zone_denom():
    assert config.STUMPY_EXCL_ZONE_DENOM == 4

    config.STUMPY_EXCL_ZONE_DENOM = np.inf
    assert config.STUMPY_EXCL_ZONE_DENOM == np.inf

    config.STUMPY_EXCL_ZONE_DENOM = 4
    assert config.STUMPY_EXCL_ZONE_DENOM == 4
```

Do you see any reasons why this might not be sufficient? Anything else you might add?

**Comment by seanlaw** [comment]
@mexxexx I've pushed a fix. Would you mind pulling it into your branch and testing it out?

**Comment by mexxexx** [comment]
I'll check it out, the code looks fine. However, I don't think that the unit test is actually checking the behavior we saw... But I don't think there is any way to test it...

**Comment by seanlaw** [comment]
Oh, what about this?

```
from stumpy import core, config

def test_change_excl_zone_denom():
    assert core.get_max_window_size(10) == 7

    config.STUMPY_EXCL_ZONE_DENOM = 2
    assert core.get_max_window_size(10) == 6

    config.STUMPY_EXCL_ZONE_DENOM = 2
    assert core.get_max_window_size(10) == 7
````

So, by calling the `core.get_max_window_size` function, which depends on `config.STUMPY_EXCL_ZONE_DENOM` internally, then I think this is testing the correct behavior?

**Comment by mexxexx** [comment]
Hi! Yes this tests the behaviour correctly, at least in the `core` module.

**Comment by hmcoservit** [comment]
@mexxexx @seanlaw I was having the same issue, but thanks to this discussion it is solved, Thanks!

**Comment by seanlaw** [comment]
@hmcoservit In what version of STUMPY are you seeing this problem? This should be fixed in all versions v1.9.x+

**Comment by hmcoservit** [comment]
@seanlaw I was checking on V1.9.1 

Previously I was doing:

from stumpy.config import STUMPY_EXCL_ZONE_DENOM 
STUMPY_EXCL_ZONE_DENOM = m 

Which wasn't working

**Comment by seanlaw** [comment]
Note that you should also be able to do:

```
import stumpy
stumpy.config.STUMPY_EXCL_ZONE_DENOM = 4
```

**Comment by seanlaw** [comment]
> @seanlaw I was checking on V1.9.1
> 
> Previously I was doing:
> 
> ```
> from stumpy.config import STUMPY_EXCL_ZONE_DENOM 
> STUMPY_EXCL_ZONE_DENOM = m 
> ```
> 
> Which wasn't working

It really bothers me that this doesn't work! Intuitively, this is what I would've done too so I'm going to see if I can find a way to get both methods to work

**Comment by mexxexx** [comment]
One way I see to make it more intuitive is to have some sort of getter/setter functions. Maybe in the same way as you set the plot params in `matplotlib`?

**Comment by hmcoservit** [comment]
@mexxexx  [Perhaps something like this](https://stackoverflow.com/a/43941592/7398288)?

**Comment by mexxexx** [comment]
That could be interesting... But I don't know if we could access it from within numba compiled code

**Comment by seanlaw** [comment]
It looks like the original form is the only option for now. @hmcoservit what was proposed in the example that you provided, while standardized, seems heavy handed for trying to accomplish something simple. Having said that, I'll certainly consider it in the future if the demand arises. Hopefully, what we currently have isn't too tedious.

I've also added a note in the [Tutorials/documentation](https://stumpy.readthedocs.io/en/latest/Tutorial_The_Matrix_Profile.html#Additional-Notes)
