### ISSUE TITLE
Update Contributing Guide to Sync Fork

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#414]
Currently, the [Contributing Guide](https://stumpy.readthedocs.io/en/latest/Contribute.html) only discusses forking and submitting a PR. However, during the development process, changes can occur in the upstream/parent repository and so, before submitting a PR, it is important to:

1. Sync your fork with the upstream/parent repo (see image below for a button to sync with upstream)
2. Pull your changes into your cloned fork
3. Merge the upstream changes in your local fork with your development branch (i.e., the branch where you are developing the PR)
4. Run the unit tests

Here is some relevant documentation on the above. Note that STUMPY uses `main` and not `master`:

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

![E4M-4IYXoAwDUUA](https://user-images.githubusercontent.com/7473521/122640856-93b74000-d0cf-11eb-998a-6bf8571e43ad.jpeg)

This should be added as a "Bonus Section" at the very end of the [Contributing Guide](https://stumpy.readthedocs.io/en/latest/Contribute.html)

**Comment by alvii147** [comment]
@seanlaw I can take this issue if that's okay.
