### ISSUE TITLE
Add FOSSA dependency scanning

### ISSUE THREAD

**Issue by bfattori-TDA** [TDAmeritrade/stumpy#42]
FOSSA provides a way to determine the open source dependencies used in the application and surface those, especially deep dependencies. 

https://app.fossa.com/account/github_login

Use this link to set up STUMPY.

**Comment by seanlaw** [comment]
@bfattori-TDA I went through some of the initial steps but I am seeing this now:

<img width="1440" alt="Screen Shot 2019-06-21 at 12 41 18 PM" src="https://user-images.githubusercontent.com/7473521/59938084-08443f00-9422-11e9-8a71-dd7f9b6dddf3.png">

Do you mind taking a look?

**Comment by bfattori-TDA** [comment]
Thanks for reminding me... Someone (probably me way back in the day) registered TD Ameritrade and has the credentials in _their mind_ :) I'm getting the FOSSA team to fix it for me. Once that is complete I'll let you know and you should be able to continue.

**Comment by seanlaw** [comment]
@bfattori-TDA It isn't entirely clear what else there is left to do? It seems like FOSSA automatically scans the code after every PR and I don't need to add anything in the Azure Pipelines CI.

What's left is to add the "license scan" badge to the list of badges. Is that correct or am I missing something?

**Comment by bfattori-TDA** [comment]
That's really it. Now that the project has been added, FOSSA will keep track of the OSS in the project as you add and remove dependencies. It will compare the licenses against a set of rules we've adopted for OSS projects and alerts you if there is anything that might be in conflict with your project's license before it gets too deeply integrated. The BSD doesn't typically conflict with anything, but that shouldn't exclude it from being scanned.

From the outside developer's perspective, OSS projects with a permissive license are more acceptable as a possibility over projects with more restrictive licenses, especially if they are selecting it for use in a corporate setting. Having the deep dependency scan allows outside developers (without their own software composition analysis (SCA) tools) to see what licenses are "hidden" in the software.

**Comment by bfattori-TDA** [comment]
I changed the applicable policy to the "Standard Bundle Distribution" which applies more appropriately than "Website/Hosted Service" and it flagged the font file in the docs directory as GPL-3.0-only. Further digging shows that about 3/4 of the way into the binary file, the characters "GPL-3" exist. I suspect that this is just characters emitted during "assembly" of the file and not a true indication of the font being GPL-3.0 licensed. As such, I have labeled this a **false positive**. Furthermore, @seanlaw sent me a link to the font description and it is licensed with the SIL Open Fonts license: http://www.latofonts.com/lato-free-fonts/

Speaking with @seanlaw, it became apparent that we should exclude the `/docs` folder from scanning which will require us to use FOSSA's "provided builds" mechanism. A bit of background so others understand the change:

FOSSA scans in one of two ways: automated builds or provided builds. An "automated build" is where FOSSA checks the code out of GitHub and does a best-guess naive build of the code. It will include everything in the project so it won't miss anything. This will include the `/docs` folder improperly, leading to this false positive.

The alternative is to use their "provided build" mechanism where the software is scanned after a successful "build", performed by the CI system. When using this method, we can provide a configuration telling FOSSA what to include and exclude from scanning. I'm doing some digging to figure out how I can get FOSSA implemented into the Azure Pipeline you're using right now.

**Comment by seanlaw** [comment]
I wonder if we could still do an "automated build" **and** provide a configuration file to ignore the `docs/` directory. I've seen other automated builds where they clone the repo and checks for a config file and then processes it accordingly.

**Comment by bfattori-TDA** [comment]
I will ask if the automated builds will pick up the `.fossa.yml` file, but it's my understanding it doesn't. I could be wrong and if so, this'll be even easier. I'll get back to you when I find out.

**Comment by bfattori-TDA** [comment]
The automated builds do not use the `.fossa.yml` file - that was the word from FOSSA. As such, I'll look into getting this set up in Azure pipelines.

**Comment by seanlaw** [comment]
Closing this for now. Feel free to reopen if things change.

**Comment by bfattori-TDA** [comment]
Preparing to add the updates for the Azure Pipeline to analyze code with FOSSA.
