### ISSUE TITLE
Broken links in tutorial

### ISSUE THREAD

**Issue by asifmallik** [TDAmeritrade/stumpy#423]
There are two broken links in [Tutorial_Time_Series_Chains.ipynb](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_Time_Series_Chains.ipynb)

-  [time series motifs](https://github.com/TDAmeritrade/stumpy/blob/4c05d54d68963d898c854c388779d4727f19f5a8/docs/Tutorial_1.ipynb) which should point to [this file](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_STUMPY_Basics.ipynb)
- [Web Query Volume case study](http://www.www2015.it/documents/proceedings/proceedings/p721.pdf) which seems to have had its [domain migrated](http://www2015.thewebconf.org/documents/proceedings/proceedings/p721.pdf).

**Comment by seanlaw** [comment]
@asifmallik Would you like to submit a PR for this?

**Comment by asifmallik** [comment]
@seanlaw Yes!

**Comment by seanlaw** [comment]
@asifmallik Just checking in. Any updates on this?

**Comment by asifmallik** [comment]
Sorry! Didn't realize I forgot to make the pull request for this.
