### ISSUE TITLE
Missing instruction on building and contributing to documentation

### ISSUE THREAD

**Issue by asifmallik** [TDAmeritrade/stumpy#424]
Ideally, README.md should have a line or two under the [documentation section](https://github.com/TDAmeritrade/stumpy#documentation) on how to build the documentation.

**Comment by seanlaw** [comment]
I think this should be in the [Contributing Guide](https://stumpy.readthedocs.io/en/latest/Contribute.html) and not in the `README.md`.

**Comment by seanlaw** [comment]
@asifmallik Are you able to submit a PR for this?

**Comment by asifmallik** [comment]
@seanlaw yes, sorry, I had forgotten about this

**Comment by seanlaw** [comment]
@asifmallik Closing this for now. Feel free to reopen when you are able to find some time
