### ISSUE TITLE
`cutoff` Parameter Not Used in `motifs`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#439]
`stumpy.motifs` accepts a `cutoff` input parameter that isn't actually being used anywhere. I believe that this value should be passed into `_motifs` in order to assess whether the "next" candidate subsequence should be considered.

**Comment by seanlaw** [comment]
@mexxexx Would you mind taking a quick look at this?

**Comment by mexxexx** [comment]
@seanlaw Hi! I had a look. I think you are right, the `cutoff` parameter should be passed on to `_motifs`. I think replacing lines 96-97

``
        if np.isinf(profile_value):  # pragma: no cover
            break
````

with

``
        if profile_value > cutoff:  # pragma: no cover
            break
````
should yield the right behavior.

**Comment by seanlaw** [comment]
Great! I made the changes and am running the tests now

**Comment by seanlaw** [comment]
Done! Thanks, @mexxexx

**Comment by mexxexx** [comment]
Great! You're welcome! Sorry for the delayed response
