### ISSUE TITLE
Add `normalize` Parameter to `stumpy.stimp`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#441]
Currently, the `stumpy.stimp` function (as well as `stumpy.stimped` and `stumpy.gpu_stimp`) only work with z-normalized matrix profiles. The "pan matrix profile" is generated by computing matrix profiles with different subsequence window sizes and then each individual matrix profile is then normalized by their corresponding subsequence length according to:

```
m = 25
norm = 1.0 / (2.0 * np.sqrt(m))
mp = mp * norm
```

However, if the subsequence is not z-normalized first then this equation does not apply and we need to derive a different relationship for length normalizing the matrix profiles. Alternatively, one may simply normalize each matrix profile by the maximum value (i.e., `np.max(mp)`).

**Update**

We should normalize by:
```
norm = 1.0 / np.abs(T_max - T_min) * np.sqrt(m)
```

- [ ] Add `normalize` to `stimp`, `stimped`, and `gpu_stimped`
- [ ] Add `p-norm` to `stimp`, `stimped`, and `gpu_stimped`
- [ ] Add unit test to `tests/test_non_normalized_decorator`
- [ ] Add `aamp_stimp`, `aamp_stimped`, and `gpu_aamp_stimped` functions
- [ ] Add unit tests for `tests/test_aamp_stimp`, `tests/test_aamp_stimped`, and `tests/test_gpu_aamp_stimped`

**Comment by Ninimama** [comment]
@seanlaw 
Do you know the idea behind `np.sqrt(2*m)` ? I don't know but I think it is related to the highest possible value for z-normalized Euclidean distance, which is `2*np.sqrt(m)`, because the only difference here is the constant ratio. Furthermore, it makes sense that to normalize each MP based on the highest possible distance.

For non-normalized Euclidean distance, we can say the `ED_max = |T_max - T_min|*np.sqrt(m)`. Therefore, I think we can use `|T_max - T_min|*np.sqrt(m)` or even the same `np.sqrt(2 * m)` as they both share the same variable part, i.e. `np.sqrt(m)`. 

What do you think? Do you think using `np.sqrt(m)` or `np.sqrt(2 * m)` or `2*np.sqrt(m)` make any different in the conclusion one can make based on the outcome of z-normalized pan matrix profile?

**Comment by seanlaw** [comment]
> Do you know the idea behind np.sqrt(2*m) ? I don't know but I think it is related to the highest possible value for z-normalized Euclidean distance, which is 2*np.sqrt(m), because the only difference here is the constant ratio.

@Ninimama If you look at the Pearson notebook, you'll see that there are three scenarios relating to correlation (uncorrelated - `r=0`, perfectly correlated - `r=1.0`, and anti-correlated - `r=-1.0`). Technically, it is possible for two subsequences to be perfectly anti-correlated and have a distance that is `2 * sqrt(m)`. However, in practice, it is (nearly) impossible for a matrix profile distance to be anti-correlated since matrix profiles always returns the smallest distance to your one nearest neighbor. In other words, given a sufficiently long time series, you will always find another subsequence that is "closer" than the anti-correlated subsequence. This "closer" subsequence is bounded by "perfectly correlated" which corresponds to a maximum matrix profile distance of `sqrt(2 * m)`. If I recall correctly, this is also consistent with what is stated in the MERLIN paper.

> For non-normalized Euclidean distance, we can say the ED_max = |T_max - T_min|*np.sqrt(m). Therefore, I think we can use |T_max - T_min|*np.sqrt(m) or even the same np.sqrt(2 * m) as they both share the same variable part, i.e. np.sqrt(m).

Thanks to your MERLIN derivation (again, fantastic work!), I think you are right regarding the use of `|T_max - T_min|*np.sqrt(m)` for non-normalized Euclidean distance. `|T_max - T_min|*np.sqrt(m)` seems correct and we should test it out with some data (that maybe we generate).

**Comment by seanlaw** [comment]
@Ninimama Based on the discussion above, I investigated how much the pan matrix profile would be changed if we normalized using `2 * sqrt(m)` (anti-correlated) instead of `sqrt(2 * m)` (correlated) and saw no visual difference. Thus, I have now updated `stumpy.stimp` to normalize using `2 * sqrt(m)` (anti-correlated)!

I think `2 * sqrt(m)` is much more obvious and intuitive and `2 * sqrt(m)` causes too much confusion.

**Comment by Ninimama** [comment]
@seanlaw 
Thanks for the investigation!! I checked the commit. Nice explanation! 
---

**Btw, based on my understanding, I think:**

> This "closer" subsequence is bounded by "perfectly correlated" which corresponds to a maximum matrix profile distance of `sqrt(2 * m)`

 `sqrt(2 * m)` is for uncorrelated case (please note that `perfectly correlated` gives distance of `0`. Just think about two exactly similar subsequences!).
If you think that is correct, you may want to revise the pearson notebook as well.

I provided the page 3 of [this paper](https://arxiv.org/pdf/1601.02213.pdf) below:
![image](https://user-images.githubusercontent.com/38519522/148666342-fa0cd410-b71e-4ccf-bf56-e56b7d5088cd.png)

I think there is a typo in the last sentence. I think the correct sentence is: 
Therefore the Euclidean distance of two normalized series is exactly equal to **the Pearson Distance**, bare a constant factor of 2T.

---


> I think `2 * sqrt(m)` is much more obvious and intuitive and `2 * sqrt(m)` causes too much confusion.

I think there is a typo. I think you meant: 

.... and `sqrt(2 * m)` causes too much confusion

---

Btw, I got your point. I just mentioned the above items to help you (and others) to not get confused later.

**Comment by seanlaw** [comment]
@Ninimama Yes, you're right! I misspoke. I'll update the Pearson notebook accordingly.
