### ISSUE TITLE
Replace Matplotlib Style Sheet With URL

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#452]
Currently, all of our [tutorials](https://github.com/TDAmeritrade/stumpy/tree/main/docs) refer to a matplotlib style sheet:

```
plt.style.use('stumpy.mplstyle')
```

However, this may confuse users who are cutting and pasting code from the tutorial and they will find that the above line doesn't work. Instead we can replace this line with:

```
plt.style.use('https://github.com/TDAmeritrade/stumpy/blob/main/notebooks/stumpy.mplstyle')
```

**Comment by saurabh-1-1** [comment]
hey seanlaw i can try it, i will update you in an hour with the work

**Comment by seanlaw** [comment]
Sounds good. Thanks, @saurabh-1-1 !
