### ISSUE TITLE
[Refactor] Sliding Window function is implemented in both numpy and in stumpy

### ISSUE THREAD

**Issue by JaKasb** [TDAmeritrade/stumpy#461]
Since Numpy version 1.20, numpy implements a sliding window function.
https://numpy.org/devdocs/release/1.20.0-notes.html?highlight=sliding%20window#sliding-window-view-provides-a-sliding-window-view-for-numpy-arrays

Therefore the custom version in stumpy could be removed.
https://github.com/TDAmeritrade/stumpy/blob/f8ad3cff1628d3d4b31dfee7609337986afb70f3/stumpy/core.py#L208

As an alternative, keep the function rolling_window(a, window) but replace the manual strides with the numpy implementation. Thereby creating a thin wrapper, without the need for renaming/refactoring the rest of the codebase.

**Comment by seanlaw** [comment]
@JaKasb Thank you for pointing this out as I was not aware of this. Do you happen to know what the benefit is? Is stride tricks somehow significantly slower or is it being deprecated? I ask because we'll need to maintain (some) backwards as STUMPY's minimum supported version is `numpy=1.5`

**Comment by JaKasb** [comment]
In the numpy version of sliding_window, most of the code deals with error handling and fail safe mechanisms.
I don't expect a speed difference, but I don't have any data to back this assumption.
If numpy 1.5 is a requirement, then the convenience function is out of reach anyway.

**Comment by seanlaw** [comment]
In case it matters, over time we plan to bump up the minimum NumPy and SciPy versions and so this may be relevant when that happens.
