### ISSUE TITLE
 AttributeError: Undefined symbol "LLVMPY_AddRefPrunePass"

### ISSUE THREAD

**Issue by ManPython** [TDAmeritrade/stumpy#468]
The issue that can recognize the real source of problem
https://github.com/numba/llvmlite/issues/773

**Comment by seanlaw** [comment]
Thank you. This definitely sounds like a Numba issue. It's hard to tell from numba/llvmlite#773 but it looks like you are trying to run STUMPY using AMD CPUs? I'm not sure this is supported (we're basically at the mercy of what Numba supports).

**Comment by seanlaw** [comment]
Closing this for now but feel free to re-open if this is a STUMPY problem. I will continue to monitor the other Numba issue(s) that you created
