### ISSUE TITLE
Failures with single-precision float32 data

### ISSUE THREAD

**Issue by bdice** [TDAmeritrade/stumpy#5]
Hi @seanlaw! I was experimenting with `stumpy` today and had some unexpected failures when using single-precision `float32` data (the NumPy default is double-precision `float64`).

## Script to reproduce
```python
import stumpy
import numpy as np

your_time_series = np.random.rand(10000).astype(np.float32)
window_size = 50  # Approximately, how many data points might be found in a pattern

matrix_profile = stumpy.stump(your_time_series, m=window_size)
```

## Error output
```python
Traceback (most recent call last):
  File "stumpy_float32_bug.py", line 7, in <module>
    matrix_profile = stumpy.stump(your_time_series, m=window_size)
  File "/redacted/lib/python3.6/site-packages/stumpy/stump.py", line 354, in stump
    core.check_dtype(T_A)
  File "/redacted/lib/python3.6/site-packages/stumpy/core.py", line 74, in check_dtype
    raise TypeError(msg)
TypeError: <class 'float'> type expected but found <class 'numpy.float32'>
```

**Comment by seanlaw** [comment]
@bdice This is really strange as this is coming from the `stumpy/core.py` module:

    def check_dtype(a, dtype=np.float):  

        if not issubclass(a.dtype.type, dtype):
            msg = '{} type expected but found {}'.format(dtype, a.dtype.type)
            raise TypeError(msg)

We are simply checking to make sure that the input numpy array is of type `np.float`. I would've expected both `np.float32` and `np.float64` to subclass `np.float`. Apparently, that was a wrong assumption. The simple fix would be to update `dtype=np.float` in the function parameter to whatever would encompass both `np.float32` and `np.float64` but I actually don't know what that would be without some research.

Optionally, we could just be very explicit and do:

    def check_dtype(a, dtype=(np.float32, np.float64, np.float)):  

        if not issubclass(a.dtype.type, dtype):
            msg = '{} type expected but found {}'.format(dtype, a.dtype.type)
            raise TypeError(msg)

**Comment by seanlaw** [comment]
Another alternative is to use `issubdtype`:

    def check_dtype(a, dtype=np.floating):
        if not np.issubdtype(a.dtype, dtype):
            msg = f'{dtype} type expected but found {a.dtype}'
            raise TypeError(msg)

**Comment by bdice** [comment]
@seanlaw I like the `issubdtype` approach. I did some reading and that seems safest.
