### ISSUE TITLE
misleading error message raised by stumpy.motifs

### ISSUE THREAD

**Issue by Ninimama** [TDAmeritrade/stumpy#500]
**Problem Description**
 
 `stumpy.motifs` raises the following error message when the argument `T` is one dimensional (correct format) but the argument `P` is NOT one dimensional (incorrect format). I got this error when I, by mistake, used `mp` (output of `stumpy.stump`) as the input `p` 

**Error Message:** 
`ValueError: T is 2-dimensional and must be 1-dimensional. Multidimensional motif discovery is not yet supported.`

---

Is it possible to have separate error messages, one for P and one for T? Because, as you can see below, the dimension of T is determined by `P.ndim`. 

>  218     if P.ndim != 1:  # pragma: no cover
    219         raise ValueError(
--> 220             f"T is {P.ndim}-dimensional and must be 1-dimensional. "
    221             "Multidimensional motif discovery is not yet supported."
    222         )

**Comment by seanlaw** [comment]
@Ninimama This appears to be a typo. Due to copy/pasting, it should've said `ValueError: P is...` rather than `ValueError: T is...`

**Comment by seanlaw** [comment]
Should be fixed in https://github.com/TDAmeritrade/stumpy/commit/80e1899fde2d2d2ed857194dc290f62e5f8ad1a4
