### ISSUE TITLE
Add Python 3.10 to Github Actions Workflow

### ISSUE THREAD

**Issue by alvii147** [TDAmeritrade/stumpy#504]
@seanlaw not sure if this is something to be focused on right now, I'll leave it to your judgement, I thought it might be useful to add 3.10 to the github workflow?

**Comment by seanlaw** [comment]
@alvii147 I actually tried to do this [last week](https://github.com/TDAmeritrade/stumpy/pull/496) but we are still waiting for other packages to catch up in their Python 3.10 support. I'll revisit this occasionally as things becomes available

**Comment by alvii147** [comment]
Ahh my bad, that makes sense!

**Comment by seanlaw** [comment]
> Ahh my bad, that makes sense!

No worries. Thanks for looking out! I'll keep this issue open until it gets resolved in the future
