### ISSUE TITLE
stumpy snippets: mistake in plotting the regimes in the tutorial notebook

### ISSUE THREAD

**Issue by Ninimama** [TDAmeritrade/stumpy#509]
I think there might be a small issue in plotting the regimes in the [Snippets Tutorial Notebook](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_Time_Series_Snippets.ipynb). 

---

I took a look at the paper [Matrix Profile XIII: Snippets](https://www.cs.ucr.edu/~eamonn/Time_Series_Snippets_10pages.pdf), and I checked the implementation of snippet in STUMPY. It is all good! However, The problem is when the regimes are being plotted (section: `plotting the regimes of snippets`)

```
for i in range(k):
    slices_of_indices = regimes[np.where(regimes[:,0]==i)][:,1:]
    print(f'indices slice for the regime of the snippets #{i} is: {slices_of_indices}')
    
    for per_slice in slices_of_indices:
        start_idx = per_slice[0]
        stop_idx = per_slice[1]+m-1
        plt.plot(range(start_idx,stop_idx),T[start_idx:stop_idx], lw=5, label='snippt #{}'.format(i))

plt.legend(loc='upper right',fontsize=15)
plt.show()
``` 

As you can see, it is assumed that the indices included in the regimes are just the beginning of a subsequence. 
(please notice:  **stop_idx = per_slice[1]+m-1**)

I think we should do **stop_idx = per_slice[1]+m** (that `-1` was also wrong) ONLY for the most-right regime as the last index returned by the regime is `len(T) - m` in that particular case.

**Comment by seanlaw** [comment]
@Ninimama Yes, that sounds right. Would you mind submitting a PR to correct this?

**Comment by Ninimama** [comment]
@seanlaw 
Thanks for the confirmation. I will submit a PR regarding this issue.

**Comment by Ninimama** [comment]
I submitted a PR. But, before you accept the changes, you may want to take a look at this:

I tried to use `stumpy,snippets` on electricity demand data (with length 8760). For `m=7*24`, one of the slices in a regime was `[3832 3833]` which doesn't make sense unless we add `m-1` to each index included in that range. Then, I think more about it. Please correct me if I am wrong. Since snippets is based on the matrix profile and the matrix profile values correspond to the starting index of each subsequence, we should add `m-1` to the indices returned in the regimes. (Maybe, overlap is inevitable in snippets)

**Comment by seanlaw** [comment]
@Ninimama Sorry but I'm not sure I am following what you mean. Can you please elaborate?

**Comment by Ninimama** [comment]
@seanlaw 
I have a time series data `T`, where `len(T) = 8760`. In one of my experiments, I chose `m=168`. I took a look at the output `regimes`, which is a ndarray and its first column represents the index of a regime. In one of the slices (of one of  the regimes) I noticed this: `[regime_index 3832 3833]`. However, the length of this slice is `1`, which is less than `m=168`. So, I think we should think of each index included in each slide of the output `regimes` as just the STARTING index of the subsequence with length `m`. So, I believe `stop_idx = per_slice[1]+m-1`  was correct and there is no need to change it !!! (So, no need to revise the notebook!) 

---

**Also:**
**Another** regime (different than `regime_index`) has this slice: `[3833 something]`. Now, we can see there is a (partial) overlap when we want to plot the snippets of these two regimes together. I do not know if this is an issue that we should be worried about, or this is a usual thing when we want to use snippets.

**Comment by seanlaw** [comment]
> I have a time series data T, where len(T) = 8760. In one of my experiments, I chose m=168. I took a look at the output regimes, which is a ndarray and its first column represents the index of a regime. In one of the slices (of one of the regimes) I noticed this: [regime_index 3832 3833]. However, the length of this slice is 1, which is less than m=168. So, I think we should think of each index included in each slide of the output regimes as just the STARTING index of the subsequence with length m. So, I believe stop_idx = per_slice[1]+m-1 was correct and there is no need to change it !!! (So, no need to revise the notebook!)

I disagree. While it's been a while since we've looked at this and I do not remember the details, `regimes` should already be giving you the start and stop indices for that regime. Now that I've looked at it a bit closer, it's not clear to me why you'd set `stop_idx = per_slice[1]+m-1`. In fact, I believe that it should be:

```
for start, stop in slices_of_indices:
    plt.plot(range(start, stop),T[start:stop], lw=5, label='snippt #{}'.format(i))
```

Though, I cannot explain why you are getting `[regime_index 3832 3833]` and a slice of length `1` sounds wrong. This sounds like we should investigate this further. 

> Another regime (different than regime_index) has this slice: [3833 something]

This sounds questionable too. I don't believe that there should be overlap.

@Ninimama  Are you able to share this data and a minimum reproducible example? I think we need to get to the bottom of this.

**Comment by Ninimama** [comment]
> I disagree. While it's been a while since we've looked at this and I do not remember the details, `regimes` should already be giving you the start and stop indices for that regime.

I didn't go through the paper recently so I am not sure what I am about to say is completely correct or not. If you take a look at the section `Plotting the MPdist profile of snippets` in the notebook, you can see the profiles of two snippets intersect somewhere in the middle (probably at index `880` as can be seen in the output `regimes`). The lower part of the profile of a snippet is where all snippets of its corresponding regime located. 

Let us think about the index `879` and `881`. What is `879`? I believe that is an index in the MPdist matrix profile that **represents** the subsequence `[879: 879+m]`. Is that correct? (because, for instance, in `mp=stumpy.stump(...)`, the `mp[i,0]` shows the distance of subsequence `T[i:i+m]` to its NN.) If that is correct, we can say the same thing for `881`. So, I don't think we cannot get rid of overlap for indices of two regimes that are close to the intersection. 

---

> Are you able to share this data and a minimum reproducible example?

To reproduce the example:
T:  [Data](https://drive.google.com/file/d/1SCIQDA-aACLI9F1Fc1CjmjCWooTQ68GS/view?usp=sharing)
`m = 30*24` 
`k  = 3`

**Comment by seanlaw** [comment]
@Ninimama Thank you. Please give me some time to take a look

**Comment by seanlaw** [comment]
@Ninimama I wasn't able to find anything out of the ordinary but I have some observations based on your example data:

1. I don't know how much `normalize=False` affects the snippets
2. The three snippets simply overlap too much and there doesn't seem to be any snippets that would represent the data better than the others:

![download-9](https://user-images.githubusercontent.com/7473521/148666254-5f3c9e92-076f-4ef6-ba44-f4847d0713b2.png)

3. I would plot the "regime bars" from the paper like this:

```
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

plt.style.use('https://raw.githubusercontent.com/TDAmeritrade/stumpy/main/docs/stumpy.mplstyle')

color_vec = ['orange','green', 'black']
plt.plot(df["data"])
ax = plt.gca()

for i in range(k):
    slices_of_indices = regimes[np.where(regimes[:,0]==i)][:,1:]
    # print(f'indices slice for the regime of the snippets #{i} is: {slices_of_indices}')
    
    for per_slice in slices_of_indices:
        start_idx = per_slice[0]
        stop_idx = per_slice[1]
        rect = Rectangle((start_idx, 0), stop_idx-start_idx, 0.2, facecolor=color_vec[i])
        ax.add_patch(rect)

plt.show()
```
![download-10](https://user-images.githubusercontent.com/7473521/148666275-f4edf977-8077-4de3-acf1-e3ee38dab95f.png)

**Comment by Ninimama** [comment]
> 2. The three snippets simply overlap too much and there doesn't seem to be any snippets that would represent the data better than the others:

Thanks a lot for your effort! As you mentioned, maybe the root of this issue is coming from my data. Because, in the paper, they showed the effectiveness of snippets in discovering summer and winter of electricity demand, and the data they showed had two clear segments. However, visually speaking, we cannot say such thing for my data. 

(Just to confirm, did you plot each snippet for the whole length of data? I mean, did you repeat a single snippet again and again to create a time series with length the same(?) as the original time series?)

---

> 3. I would plot the "regime bars" from the paper like this:

That is a nice visualization (If you don't mind, I can add such visualization to the tutorial notebook as well) 

Also I will revise the plots of snippets in the notebook (as you explained before. please see below).

> In fact, I believe that it should be:
> 
> ```
> for start, stop in slices_of_indices:
>     plt.plot(range(start, stop),T[start:stop], lw=5, label='snippt #{}'.format(i))
> ```

---

Btw, we can still feel the overlaps of snippets in the regime bars. I tried to see if I can find any particular discussion on this in the paper, but I couldn't. So, for now, I think that is how snippets might behave in some cases. 

So, should we close this issue?

**Comment by seanlaw** [comment]
> maybe the root of this issue is coming from my data.

Possibly the data but there might also be an (small?) effect of using `normalize=False` 

 > did you plot each snippet for the whole length of data? I mean, did you repeat a single snippet again and again to create a time series with length the same(?) as the original time series?

No. I'm not sure what that does? I don't think that the entire length of a snippet must be used

> I can add such visualization to the tutorial notebook as well

Please do but also feel free to choose better colors :)

> Also I will revise the plots of snippets in the notebook (as you explained before. please see below).

Great! I updated my regime bar code above to follow the same approach

> I think that is how snippets might behave in some cases.

I agree

> So, should we close this issue?

Yes, please.

**Comment by Ninimama** [comment]
> > did you plot each snippet for the whole length of data? I mean, did you repeat a single snippet again and again to create a time series with length the same(?) as the original time series?
> 
> No. I'm not sure what that does? I don't think that the entire length of a snippet must be used

I meant I didn't understand how you got three different patterns (as you showed in the figure above), all with length 8000? 
Because each regime contains a particular-shape snippet at different locations (time stamps). Would you mind help me figure out what that three patterns are?

**Comment by seanlaw** [comment]
> Are those profile distances of three snippets?

Yes! Exactly

```
color_vec = ['orange','green', 'black']
for i in range(k):
    plt.plot(profiles[i],c=color_vec[i])

plt.show()
```

According to the paper, a snippet is representative of the region if the  area under the profile is close to zero. So, by plotting the profile, I wanted to see if there were any clear/unambiguous "winners" that would be representative. However, all three snippets are basically overlapping, which suggests that there aren't any obvious representatives.

At least, that is my interpretation but I could be wrong.

**Comment by Ninimama** [comment]
I see what you meant now! I think your observation makes sense. 

Thanks a lot for your effort on this! Appreciate it! I am going to close this issue now.
