### ISSUE TITLE
Modernize AAMP Functions

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#533]
Currently, there are several `aamp`-related functions/modules:

- [x] aamp.py
- [x] aamped.py
- [x] gpu_aamp.py
- [x] maamp.py
- [ ] maamped.py
- [x] aampi.py
- [x] aamp_motifs.py
- [x] aamp_ostinato.py
- [x] aampdist_snippets.py
- [x] gpu_aamp_ostinato.py
- [x] aampdist.py
- [x] aampdisted.py
- [x] gpu_aampdist.py
- [x] scraamp.py
- [x] Add `exclude=["normalize", "p"]` to all complementary normalized functions
- [x] Check where `core.mass_absolute` is being used, add `p` parameter to `core.mass_absolute`
- [x] In original versions `core.mass_absolute`/`core._mass_absolute` can be passed `T_subseq_isfinite` and clears bad distances. We need to do the same for distances computed from `np.linalg.norm`

In some or all of these modules, they may be using the sliding dot product, `QT`, to compute the non-normalized Euclidean distance. However, this prevents us from generalizing this to computing the p-norm distance. The goal of this issue is to modernize all `aamp` functions to replace the `QT`-dependent parts.

**Comment by seanlaw** [comment]
@vaish-muk I will need to put some time into thinking about how we'd replace `QT`. It appears that what we need is to keep track of `D_squared` (i.e., if I understand correctly, in general, this is the part of the Minkowski "distance" without the `p`th root applied) computed in the previous iteration (and without any exclusion zone applied). The good thing is that all of our unit tests should stay the same for this modernization attempt and so we can change whatever we need as long as the tests pass accordingly.

Do you happen to have access to an NVIDIA GPU by any chance for testing? It is not a requirement but it is likely the best place to make changes first. If not, I can take a look at that part and see if I can find a good path.

**Comment by vaish-muk** [comment]
> @vaish-muk I will need to put some time into thinking about how we'd replace `QT`. It appears that what we need is to keep track of `D_squared` (i.e., if I understand correctly, in general, this is the part of the Minkowski "distance" without the `p`th root applied) computed in the previous iteration (and without any exclusion zone applied). The good thing is that all of our unit tests should stay the same for this modernization attempt and so we can change whatever we need as long as the tests pass accordingly.
> 
> Do you happen to have access to an NVIDIA GPU by any chance for testing? It is not a requirement but it is likely the best place to make changes first. If not, I can take a look at that part and see if I can find a good path.

@seanlaw , I don't have access to an NVIDIA GPU

**Comment by seanlaw** [comment]
>  I don't have access to an NVIDIA GPU

@vaish-muk No worries. I will try to find some time to take a look and will report back once I make progress.

**Comment by seanlaw** [comment]
Fixed in d3b68b4daf0fa76697c7b6aa17adb02591a75388
