### ISSUE TITLE
Replace `while` Loops

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#545]
Currently, `aamp_motifs.py` and `motifs.py` both utilize a `while` loop but it would be safer to change this to a `for` loop

**Comment by rteja1113** [comment]
forgive my ignorance but why would it be safer ?

**Comment by seanlaw** [comment]
@rteja1113 In my experience, `while` loops are a nice way to express certain pieces of code. However, I've come across many instances where a `while` loop can get stuck and never exits due to the stop condition never being reached. In contrast, a properly written `for` loop doesn't (rarely?) exhibit this behavior and enforces that you start somewhere and end somewhere. Of course, some concepts things are easier to express as a `while` loop and it certainly has its place.

In this particular case, we've seen our `while` loops run indefinitely due to some rare edge cases and so we should take the time to think about our design. Again, there aren't any hard rules to this but maybe boils down to a personal preference. I just prefer to guarantee that the code will stop. Does that make sense?

**Comment by rteja1113** [comment]
while loops if written properly, can do everything a for loop can do but the opposite is not True. In some cases, you have no choice but to use while loops(when you have to conditionally update the scanning variable). My personal opinion is that if it's not broken, don't fix it. That being said, if there are any edge cases that make the while loop run indefinitely,  code should be added before the while loops to check for edge cases.
