### ISSUE TITLE
scipy.ndimage.filters is deprecated

### ISSUE THREAD

**Issue by vbersier** [TDAmeritrade/stumpy#546]
With `scipy 1.8.0`:

> .venv/lib/python3.8/site-packages/stumpy/core.py:12: DeprecationWarning: Please use `maximum_filter1d` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.

https://github.com/TDAmeritrade/stumpy/blob/3b29e622bd789736f15405abae2ec7acbc970135/stumpy/core.py#L12

**Comment by vbersier** [comment]
`stumpy` is a second-level dependency of my project (first level being `tsfresh`) so no promises but if I get some time.

**Comment by seanlaw** [comment]
Looks like it was an easy fix. Thanks again for bringing it to our attention @vbersier!
