### ISSUE TITLE
Add Unit Tests for `mmotifs` and `aamp_mmotifs`

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#552]
The `mmotifs` and `aamp_mmotifs` features were recently added but they need unit tests to accompany them:

- [ ] <s>Add naive implementation for `mmotifs` and `aamp_motifs` in `tests/naive.py`</s>
- [ ] Add `pytest -x -W ignore::RuntimeWarning -W ignore::DeprecationWarning tests/test_motifs.py` to the `test_unit` function in `test.sh`
- [ ] Add `pytest -x -W ignore::RuntimeWarning -W ignore::DeprecationWarning tests/test_aamp_motifs.py` to the `test_unit` function in `test.sh`
- [ ] Add unit tests for `mmotifs` in `tests/test_mmotifs.py`
- [ ] Add unit tests for `aamp_motifs` in `tests/test_aamp_mmotifs.py` 
- [ ] Add `mmotifs` and `aamp_motifs` to `stumpy/__init__.py` 
- [ ] Add `mmotifs` to `docs/api.rst`
- [ ] Add Example section to `mmotifs()` docstring:

```
    Examples
    --------
    >>> mp = stumpy.stump(np.array([584., -11., 23., 79., 1001., 0., -19.]), m=3)
    >>> stumpy.motifs(
    ...     np.array([584., -11., 23., 79., 1001., 0., -19.]),
    ...     mp[:, 0],
    ...     max_distance=2.0)
    (array([[0.        , 0.11633857]]), array([[0, 4]]))
```

**Comment by seanlaw** [comment]
@SaVoAMP [had asked](https://github.com/TDAmeritrade/stumpy/pull/544#issuecomment-1052243504):

> Unfortunately, I have never worked with unit tests, which means that I am a complete beginner. Are there any resources available since I have absolutely no clue how to start?

**Comment by SaVoAMP** [comment]
All right, so how to implement functions naivly? 🤔 
Can I then also start with the tutorial in parallel?

**Comment by seanlaw** [comment]
> I will need to investigate why mmotifs and aamp_motifs aren't triggering missing coverage.

@SaVoAMP I fixed this. Can you please pull and merge the latest commit to your branch?

**Comment by SaVoAMP** [comment]
> Btw, did you have to add any additional steps that may have been omitted in my description above?

No, I reforked the repo, added a branch, cloned it inside my linux vm, activated a virtual environment for python and ran `pip.sh` as you described.

**Comment by SaVoAMP** [comment]
tests/test_stamp.py ....................                                 [ 86%]
tests/test_stimp.py ...........                                          [ 87%]
tests/test_stomp.py ........................                             [ 89%]
tests/test_stump.py .......................                              [ 90%]
tests/test_stumped.py .................................................. [ 94%]
................................................                         [ 98%]
tests/test_stumpi.py ................                                    [100%]

====================== 1254 passed in 2003.87s (0:33:23) =======================
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
stumpy/aamp.py              80     10    88%   227-238
stumpy/aamp_mmotifs.py      51     51     0%   5-195
stumpy/mmotifs.py           51     51     0%   5-203
stumpy/stump.py            107     10    91%   408-419
------------------------------------------------------
TOTAL                    10637    122    99%

70 files skipped due to complete coverage.
Cleaning Up


Hmm strange. I still have got something different 🤔

**Comment by seanlaw** [comment]
> Hmm strange. I still have got something different

So, I looked at those lines in `stumpy.stump` and `stumpy.aamp` and that only happens if you somehow are limited to a single thread. You had briefly mentioned:

> cloned it inside my linux vm, activated a virtual environment for python

Can you tell me how many threads are available to the vm? If the answer is `1` then that would explain why `stumpy.stump` and `stumpy.aamp` are coming up.

**Comment by SaVoAMP** [comment]
Indeed, I only allocated 1 virtual processor.

It is a Hyper-V virtual machine, as I couldn't figure out how to get the GUI output for plots working on WSL2.

I will allocate more cores and try again.

**Comment by SaVoAMP** [comment]
```
====================== 1254 passed in 1937.07s (0:32:17) =======================
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
stumpy/aamp_mmotifs.py      51     51     0%   5-195
stumpy/mmotifs.py           51     51     0%   5-216
------------------------------------------------------
TOTAL                    10637    102    99%

72 files skipped due to complete coverage.
Cleaning Up

```
That's the new result!

**Comment by seanlaw** [comment]
> That's the new result!

Perfect! That is the expected result. Once you complete the unit tests then the `stumpy.aamp_motifs.py` and `stumpy/mmotifs.py` lines will also disappear (i.e., all lines are "covered"). 

Did you have any questions about my unit test example above?

**Comment by SaVoAMP** [comment]
```
These are tests for multidimensional motif discovery, to be ignored for the moment

def test_motifs_multidimensional_one_motif_all_dimensions():
    T = np.array(
        [
            [0.0, 1.0, 0.0, -1.0, -1.0, 0.0, 1.0, 0.0, -0.5],
            [0.0, 1.0, 0.0, -1.0, -1.0, 0.0, 1.0, 0.0, -0.5],
        ]
    )
    m = 3
    k = 1

    left_indices = [[0, 5]]
    left_profile_values = [0]

    P, I = mstump(T, m)
    S = np.array([[0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1]], dtype=float)
    right_indices, right_profile_values = search.motifs_multidimensional(
        T, P, S, num_dimensions=2, k=k, atol=0.001
    )

    npt.assert_array_equal(left_indices, right_indices)
    npt.assert_almost_equal(left_profile_values, right_profile_values, decimal=4)


def test_motifs_multidimensional_two_motifs_all_dimensions():
    n = 200
    T = np.random.normal(size=(2, n))
    m = 20

    T[:, 10:30] = 1
    T[:, 12:28] = 2
    T[:, 110:130] = 1
    T[:, 112:128] = 2
    T[:, 129] = 1.1

    T[:, 70:90] = np.arange(m) * 0.1
    T[:, 170:190] = np.arange(m) * 0.1

    k = 2

    P, I = mstump(T, m)
    S = np.zeros((2, n - m + 1), dtype=float)
    S[1, :] = 1

    left_indices = [[70, 170], [10, 110]]
    left_profile_values = [P[70, 0], P[10, 0]]

    right_indices, right_profile_values = search.motifs_multidimensional(
        T, P, S, num_dimensions=2, k=k
    )
    right_indices = np.sort(right_indices, axis=1)

    npt.assert_array_equal(left_indices, right_indices)
    npt.assert_almost_equal(left_profile_values, right_profile_values, decimal=4)
```

I saw this lines in `test_motifs.py`. Am I supposed to use them? Should they be used in `test_motifs.py` or in `test_mmotifs.py`?

> Add pytest -x -W ignore::RuntimeWarning -W ignore::DeprecationWarning tests/test_motifs.py to the test_unit function in test.sh

> Add unit tests for mmotifs in tests/test_mmotifs.py

I think that these python files should be the same, am I right? Therefore it shouldn't matter whether I use one or the other.

**Comment by seanlaw** [comment]
> I saw this lines in test_motifs.py. Am I supposed to use them? Should they be used in test_motifs.py or in test_mmotifs.py?

You may use this if you think they are useful and then delete them from `tests/test_motifs.py` (i.e., migrate them over to `tests/test_mmotifs.py`

> I think that these python files should be the same, am I right? Therefore it shouldn't matter whether I use one or the other.

I'm not sure I understand your question. Please add a new line to `test.sh` after the `tests/test_motifs.py` lines but for `tests/test_mmotifs`:

```
pytest -x -W ignore::RuntimeWarning -W ignore::DeprecationWarning tests/test_mmotifs.py
check_errs $?
```

and also for `tests/test_aamp_mmotifs.py`:

```
pytest -x -W ignore::RuntimeWarning -W ignore::DeprecationWarning tests/test_aamp_mmotifs.py
check_errs $?
```

This should be in the `test_unit` function.
