### ISSUE TITLE
Missing Parameter in `motifs` Docstring

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#562]
`motifs` docstring is missing the `atol` parameter description:

https://stumpy.readthedocs.io/en/latest/api.html#motifs

**Comment by seanlaw** [comment]
@NimaSarajpoor Would you mind fixing this? I think it can be copied over from `stumpy.match`. `aamp_motifs.py` seems fine but please double check.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
There should be no problem. I will  take a look and submit a PR.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I think we should also add `atol` when we call `_motifs()` inside the `motifs` function. Right?

**Comment by seanlaw** [comment]
@NimaSarajpoor Yes, I missed this and thought that you had done that already previously.

**Comment by NimaSarajpoor** [comment]
Yeah.... I think I did not work on `atol` before (I think I opened an issue before). I will submit a PR shortly.

**Comment by seanlaw** [comment]
@NimaSarajpoor Thank you!
