### ISSUE TITLE
Issue in re-routing to non-normalized class aamp_stimp

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#576]
I was trying to do some experiment with pan matrix profile and I noticed there is a problem in re-routing from class `stimp` to `aamp_stimp` when `normalize=False`.

**Error:**
```
Excluding `['normalize', 'p']` parameters, 
`<class 'stumpy.stimp.stimp'>`: (['T', 'min_m', 'max_m', 'step', 'percentage', 'pre_scrump']) and 
`<class 'stumpy.aamp_stimp.aamp_stimp'>`: (['T', 'min_m', 'max_m', 'step', 'percentage', 'pre_scraamp']) 
have different parameters.
```

**Solution:** 
Modifying the decorator as follows:
```
# in stimp.py
@core.non_normalized(aamp_stimp,
                    exclude=["pre_scrump", "normalize", "pre_scraamp"],
                    replace={"pre_scrump": "pre_scraamp"}
                    )
class stimp(_stimp):
    ....
```

(I checked it on my end and I think it works)

**Comment by seanlaw** [comment]
@NimaSarajpoor Thank you for discovering this! Somehow, the unit tests wasn't firing properly (my fault) and I will need to correct it. You're also pointing out another potential issue that I will need to fortify in our testing.

**Comment by seanlaw** [comment]
@NimaSarajpoor I believe that this should be fixed now. Would you mind testing it out?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
It is working now. I noticed your commit had `p` in list `exclude`. 

----

I was trying to understand why excluding `p` (?), and I noticed there is typo in docstring (please notice `A` and `B`):

```
# in core.non_normalized(...)
    ```
    def non_norm_func(Q, T, A_non_norm):
        ...
        return
    @non_normalized(
        non_norm_func,
        exclude=["normalize", "p", "A", "B"],
        replace={"A_norm": "A_non_norm", "other_norm": None},
    )
    def norm_func(Q, T, A_norm=None, other_norm=None, normalize=True, p=2.0):
        ...
        return
    ```
```

**Comment by seanlaw** [comment]
Oh yes! In trying to make the docs better, I forgot about A and B
