### ISSUE TITLE
inconsistent data type in Tutorial_DiscordMERLIN.ipynb

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#589]
I was reviewing the [MERLIN NOTEBOOK](https://github.com/TDAmeritrade/stumpy/blob/main/docs/Tutorial_DiscordMERLIN.ipynb) and I noticed that the output of function `_discords` doesn't show consistent data type when it is appended by `[-1, np.inf, -1]` with `dtype=object` .

Apparently I should have defined `dtype` of each column separately and then concatenate them with `dtype=object`. 

If you think we can ignore this minor(?) issue at this stage, please let me know. If you think we should take care of it, I can try to fix it; however I am not sure if there is any clean way to  do this.

**Comment by seanlaw** [comment]
@NimaSarajpoor I think we should fix it. Since at the end we will return something of length `k` then we should just create three 1D arrays with length `k` (filled with dummy values) and then put them in `out` like we do elsewhere in STUMPY

**Comment by NimaSarajpoor** [comment]
I will submit a PR.
