### ISSUE TITLE
Time series chain: allc unanchored chain result contains only one of the longest chains - and not all equally-longest unanchored chains

### ISSUE THREAD

**Issue by lcoulet** [TDAmeritrade/stumpy#593]
Hello,
in allc() function unanchored chain result contains only one of the longest chains - and not all equally-longest unanchored chains.

This is different from what is explained here - https://stumpy.readthedocs.io/en/latest/Tutorial_Time_Series_Chains.html

The line of code related to this is this one: 
https://github.com/TDAmeritrade/stumpy/blob/2d6f7873796ba0d9dd752b064a114c48c6c6a8b6/stumpy/chains.py#L131

Is this on-purpose ? 
I believe that either the documentation or the code is wrong :-)

**Comment by seanlaw** [comment]
@lcoulet Welcome to the STUMPY community and thank you for your question. So, first-and-foremost, STUMPY tries its best to faithfully reproduce the original published work and, in this case, it is the [Matrix Profile VII](https://www.cs.ucr.edu/~eamonn/chains_ICDM.pdf) paper. You will see that the `allc` function follows Table 2 of the paper and in accordance with it `stumpy.allc` also [returns two things](https://stumpy.readthedocs.io/en/latest/api.html#allc):

1. S (list(numpy.ndarray)) – All-chain set
2. C (numpy.ndarray) – Anchored time series chain for the longest chain (also known as the unanchored chain)

So, in the tutorial, if you want the all-chain set then you should use `S` (returned from `allc`). However, if you want the anchored time series chain (i.e., the longest chain) then you should use `C` (also returned from `allc`). Now, as you had hinted, it is certainly possible that there exists multiple longest chains with the same length as `C` and `C` only returns one of them. In that case, you'll need to iterate over `S` and check that there are no other longest chains with the same length:

```
for chain in all_chain_set:
    if len(chain) == len(unanchored_chain):
    print(chain)
```
> I believe that either the documentation or the code is wrong :-)

Based on my understanding, I don't think either is wrong. Perhaps you can help me understand where the tutorial may be ambiguous or misleading? I would be happy to edit it to make it more clear.

**Comment by lcoulet** [comment]
@NimaSarajpoor  - This is correct thanks for clarifying what I meant.

It is  a very minor thing - but as we played with the `allc()` and did not get all the expected results in the unanchored time series chain as second result...  But just one of them. It was a bit misleading. 

Indeed we can iterate over all chains and we get all "equally-longest" chains from there.

**Comment by seanlaw** [comment]
Thank you @lcoulet and @NimaSarajpoor. I see your point now and will edit the tutorial!
