### ISSUE TITLE
Rename functions `naive.mass` and `naive.distance_profile`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#596]
It seems that the function `naive.mass` is actually the naive version of function `stumpy.stamp._mass_PI` (NOT the `stumpy.core.mass`) Therefore, it might be a good idea to do the following things:

(1) Rename function `naive.mass` to `naive.mass_PI`
(2) Rename function `naive.distance_profile` to `naive.mass`

So... `naive.stamp` calls function `naive.mass_PI`, and the function `naive.mass_PI` calls function `naive.mass`.

**Comment by seanlaw** [comment]
Sure. That sounds good. If that's the case, would it make sense to have the new `naive.mass_PI` call the new `naive.mass`? To some extent, it wouldn't make sense for `naive.mass_PI` to be computing `mass` using its own algorithm if `naive.mass` exists?

**Comment by NimaSarajpoor** [comment]
Would you please elaborate, and let me know what you suggest? Did you mean I should not change the name of `naive.distance_profile`?

**Comment by seanlaw** [comment]
No, please ignore that part and do as you had planned
