### ISSUE TITLE
Replace `naive.stamp` with `naive.stump`, with new parameter `row_traversal`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#598]
As discussed in PR #595, we would like to replace `naive.stamp` with `naive.stump(...., row_traversal=True)`. It seems that the function `naive.stamp` is used in several unit test files. To avoid pushing all these files, I created this issue so that we can address it first before moving forward in the PR, and make sure it passes all unit tests.

**Comment by seanlaw** [comment]
Sounds good
