### ISSUE TITLE
Enhancing docstrings in `stumpy/scrump.py`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#611]
I have been studying the `scrump.py` and I think it might be a good idea to enhance its docstrings:

* information about returned values in function  `_prescrump` is not provided in its docstring.
* clarifying the structure of output in both the method `.update()` and the docstring of `prescrump` . In contrast to `stumpy.stump`, the `I` in `P, I = prescrump()` does not contain left and right matrix profile indices. Also, the `P` (`I`), being updated via `.update()` contains the left and right matrix profile (indices).

**Comment by seanlaw** [comment]
@NimaSarajpoor Would you like me to assign this to you?  Or did you have questions?

**Comment by NimaSarajpoor** [comment]
I just provided this issue here so it can be addressed regardless of the progress in top-k PR #595. So, if the PR doesn't merge, we do not forget about this issue. 

Sure. I am working on (naive version of) `scrump`, and I can take care of this issue in a couple of days,

**Comment by seanlaw** [comment]
@NimaSarajpoor Is there a need to update this for `scraamp.py` as well?

**Comment by NimaSarajpoor** [comment]
Yes. I will update prescraamp in push in the recently-created PR.
