### ISSUE TITLE
Add (Optional) Missing Line to Prescrimp Algorithm

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#612]
I think one line from algorithm is missing from both `naive.prescrump`. 

In the line 6 in the Algorithm 2 of the [Scrimp++ paper](https://www.cs.ucr.edu/~eamonn/SCRIMP_ICDM_camera_ready_updated.pdf), we can see:
```
P, I ← ElementWiseMin (D, P, i) 
```

And, in the MATLAB code of the [supporting webpage](https://sites.google.com/site/scrimpplusplus/), we can see that line is implemented:
![image](https://user-images.githubusercontent.com/38519522/171304011-25e76c45-faa9-49fa-aa5e-b45cfb1dd0e7.png)

However, I think this line is missing in `tests/naive.prescrump`:

```
def prescrump(T_A, m, T_B, s, exclusion_zone=None, k=1):
    dist_matrix = distance_matrix(T_A, T_B, m)

    n_A = T_A.shape[0]
    l = n_A - m + 1

    P = np.full((l, k), np.inf, dtype=np.float64)
    I = np.full((l, k), -1, dtype=np.int64)

    for i in np.random.permutation(range(0, l, s)):
        distance_profile = dist_matrix[i]
        if exclusion_zone is not None:
            apply_exclusion_zone(distance_profile, i, exclusion_zone, np.inf)
        
        # MISSING LINE
        
        I[i] = np.argmin(distance_profile)
        P[i] = distance_profile[I[i]]
```

And, I think it is also missing from `_compute_PI` in the performant version. I think adding that line should make the matrix profile (indices) more accurate.

**Comment by seanlaw** [comment]
> I think it is also missing from _compute_PI in the performant version. I think adding that line should make the matrix profile (indices) more accurate.

Isn't this accounted for in:

https://github.com/TDAmeritrade/stumpy/blob/998e5d2017ed3d01d1a3993ce01e96de3dfd5254/stumpy/scrump.py#L109-L110

**Comment by seanlaw** [comment]
@NimaSarajpoor I don't remember the details but I vaguely remember disagreeing with something in their Matlab implementation and decided to omit some of their code. Unfortunately, it's been so long that I can no longer recall what it was that I found objectionable.

If you can confirm that it is "correct" and want to add it then please do so for `prescraamp` as well

**Comment by NimaSarajpoor** [comment]
> I don't remember the details but I vaguely remember disagreeing with something in their Matlab implementation and decided to omit some of their code. Unfortunately, it's been so long that I can no longer recall what it was that I found objectionable.

Ah, I see.

> If you can confirm that it is "correct"

Well, I think it makes sense to include that line. I believe the idea is that the following two lines
```
I[i] = np.argmin(distance_profile)
P[i] = distance_profile[I[i]]
```
update the `i-th` element in the profile and we are not using the other elements of `distance_profile` to update other elements of matrix profile if possible. 

So, if you do not mind, I will work on this and then, I will work on its top-k version.

**Comment by seanlaw** [comment]
Yes, I understand. Please go for it
