### ISSUE TITLE
Refactor Self-join Check

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#624]
At the end of many functions that compute the matrix profile (`stump`, `stumped`, `gpu_stumped`, etc), we perform a final check of the matrix profile distances:

https://github.com/TDAmeritrade/stumpy/blob/576de379994896063be71d264e48a08ae17476cf/stumpy/stump.py#L618-L621

Due to the fact that these lines are repeated in many places, it would be best to refactor this into a function called `_check_P(P, threshold=10e-6)` (placed in `core.py`) and to call this function where ever it is needed.

Additionally, this distance check is missing in many of the equivalent non-normalized functions (i.e., `aamp`, `aamped`, `gpu_aamp`, etc) and needs to get added.

**Comment by seanlaw** [comment]
@SaVoAMP Would you be interested in tackling this one? If so, I can assign it to you. Please feel free to ask questions if the issue isn't clear.

**Comment by SaVoAMP** [comment]
Sure, I think I should be able to do this. 

In which .py file should this function be defined? 
To make sure I understand everything: I should wrap this four lines of code into a function and call it / replace it where appropriate?

**Comment by seanlaw** [comment]
> To make sure I understand everything: I should wrap this four lines of code into a function and call it / replace it where appropriate?

Yes, exactly! And add appropriate unit tests where applicable. I think that it would be great to identify other opportunities like this in the code that we could refactor (as additional new issues). This way, we can make a change in a single place rather than repeating the change multiple times in different files.

**Comment by SaVoAMP** [comment]
All right :)

I will start with it on Tuesday, I think.
