### ISSUE TITLE
aampi update function returns nans for constant intervals

### ISSUE THREAD

**Issue by MostafaShahin1** [TDAmeritrade/stumpy#626]
I am facing a problem while trying to calculate the non-normalized matrix profile for a time series that contains a constant interval.
that is getting nans where it should be zero (for the subsequences that lie within the constant level). I tracked some numbers and most probably that's because of small negative numbers under the square root. 

here is some code to check this behavior
```
import stumpy
import numpy as np

np.random.seed(0)
T_full = np.random.rand(64,)     # generate random data
T_full[40:55] = 3                # add constant level interval

m = 8

T_stream = T_full[:10].copy()
stream = stumpy.stumpi(T_stream, m, egress=False, normalize=False)  # Don't remove/egress the oldest data point when streaming

# Incrementally add one new data point at a time and update the matrix profile
for i in range(len(T_stream), len(T_full)):
    t = T_full[i]
    stream.update(t)
    
print(stream.P_)
```
I even tried running this on different machines with different random seeds and the same behavior persists with getting this warning
```
/usr/local/lib/python3.8/site-packages/stumpy/aampi.py:241: RuntimeWarning: invalid value encountered in power
  D = np.power(p_norm_new, 1.0 / self._p)
```

**Comment by NimaSarajpoor** [comment]
@MostafaShahin1 
I was just wandering and saw your post. Since I was working on another issue, I got curious about this one. So, I think this would fix it:

Adding line:
```

p_norm_new[:] = np.where(
            p_norm_new < config.STUMPY_P_NORM_THRESHOLD, 0, p_norm_new
        )
```
before line 
https://github.com/TDAmeritrade/stumpy/blob/576de379994896063be71d264e48a08ae17476cf/stumpy/aampi.py#L241

----

And, probably before
https://github.com/TDAmeritrade/stumpy/blob/576de379994896063be71d264e48a08ae17476cf/stumpy/aampi.py#L183
as well.

----

But, please wait to hear back from @seanlaw.

**Comment by seanlaw** [comment]
@NimaSarajpoor Your proposal looks reasonable. Would you care to add the case above as a new unit test and submit a PR?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I would love to; however, my plate is a little bit full as I am working on another PR.

@MostafaShahin1 
- Would you like to handle this issue and fix the bug? You can count on my help and Sean's. If you have any questions, please feel free to ask.

**Comment by MostafaShahin1** [comment]
@NimaSarajpoor 
of course no problem, I will work on this. Thanks for your help.

**Comment by NimaSarajpoor** [comment]
@MostafaShahin1 
Cool.

**Comment by seanlaw** [comment]
Thanks @MostafaShahin1! Feel free to ask any questions

**Comment by MostafaShahin1** [comment]
@seanlaw  
I just noticed there is a unit test for constant subsequence in `test_aampi.py` which is `test_aampi_constant_subsequence_self_join`
but i believe this test covers the case in which we have the constant subsequence in the first window, where mp is calculated during the `aampi` object initialization.
on the other side, the new unit test should cover the case where we have the constant subsequence in the incremental(online) updating region, where mp is calculated using `.update()`.
is that correct?
and if so, should it be replaced with a new function covering the two cases or just adding a new one.
I just wanted to make sure I am not making something redundant.

**Comment by seanlaw** [comment]
@MostafaShahin1 Great question! Can you please add a new test function **after** `test_aampi_constant_subsequence_self_join` called, maybe, `test_aampi_update_constant_subsequence_self_join`? So, the former is what exists and the latter is when the `update` introduces a constant subsequence to appear.  Is that clear?
