### ISSUE TITLE
Pattern matching for multidimensional time series

### ISSUE THREAD

**Issue by huberl** [TDAmeritrade/stumpy#629]
I'm currently working with IMU and other sensor data obtained by a car, which gives we hours of 10-dimensional (i.e. 10 sensors) time series data. I have a target sequence (e.g. driving through a s-curve) and need to find similar occurrences in my data.

I tried the `stumpy.match(target, ts)` function, but apparently it is not suitable for multidimensional time series. Is there any way to solve this problem with stumpy? 

Any help is appreciated!

**Comment by seanlaw** [comment]
@huberl Thank you for your question. Let's continue this conversation in the open [Discussions](https://github.com/TDAmeritrade/stumpy/discussions/630)
