### ISSUE TITLE
A few issues in `scrump`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#648]
So, I have been reading the module `stumpy/scrump.py` and I think we should revise the code to address the following issues:
(I can address them in the current PR #595 or new PR)

(1) 
https://github.com/TDAmeritrade/stumpy/blob/2ec04e1723204c81b34ebccdde642917f1271c12/tests/naive.py#L1418

I think it should be changed to:
```
w = T_B.shape[0] - m + 1
for k in range(1, min(s, l - i, w-j)):   
```
So, we can make sure it works properly in AB-join. We need to revise this in the performant version as well.

(2) I think there is conflict in the name of variables and their description in the docstring:

https://github.com/TDAmeritrade/stumpy/blob/2ec04e1723204c81b34ebccdde642917f1271c12/stumpy/scrump.py#L337
https://github.com/TDAmeritrade/stumpy/blob/2ec04e1723204c81b34ebccdde642917f1271c12/stumpy/scrump.py#L338

And, then, the docstring of `_prescrump` says:
```
 M_T : numpy.ndarray
        Sliding window mean for T_A
    Σ_T : numpy.ndarray
        Sliding window standard deviation for T_A
    μ_Q : numpy.ndarray
        Mean of the query sequence, `Q`, relative to the current sliding window in `T_B`
    σ_Q : numpy.ndarray
        Standard deviation of the query sequence, `Q`, relative to the current
        sliding window in `T_B`
```

The same description is in the docstring of function `_compute_PI`. 

Also, I think the part that says "relative to the current sliding window in T_B" might be misleading here since `μ_Q` / `σ_Q` are the "Sliding window mean/std of whole `T`"

(3) In function `_compute_PI`, we can see the following for-loop:
```
# branch main
# stumpy/scrump.py
# function _compute_PI (line 103) 
for i in indices[start:stop]:
        Q = T_A[i : i + m]
        QT[:] = core._sliding_dot_product(Q, T_B)
        
        squared_distance_profile[:] = core._mass(Q, T_B, QT, μ_Q[i], σ_Q[i], M_T, Σ_T)  
       
        # NOTE: μ_Q/σ_Q corresponds to T_A, and M_T / Σ_T corresponds to T_B
```

So, if I understand correctly, `i` is the start index of subseq in `T_A` and we calculate its distance profile by calculating its distance to all subseqs in `T_B`. So, I think `i` should be used whenever we want to talk about subseqs in `T_A`.  However, we can see this is not the case in the other part of this function (please see my comments in the code below):

```
# branch main
# stumpy/scrump.py
# function _compute_PI (line 125) 

            QT_j = (m - P_squared[thread_idx, i] / 2.0) * (Σ_T[j] * σ_Q[i]) + (
                m * M_T[j] * μ_Q[i]
            )
            # NOTE: QT_j calculation is correct since we use `i` in μ_Q[i] and σ_Q[i]. 
       
            QT_j_prime = QT_j
            for k in range(1, min(s, l - max(i, j))): # SHOULD BE REVISED ACCORDING TO issue(1)
                QT_j = (
                    QT_j
                    - T_B[i + k - 1] * T_A[j + k - 1]                   # SHOULD BE CHANGED TO: T_B[j + k - 1] * T_A[i + k - 1] ??
                    + T_B[i + k + m - 1] * T_A[j + k + m - 1]   # SHOULD BE CHANGED TO: T_B[j + k + m - 1] * T_A[i + k + m - 1] ??
                )
                D_squared = core._calculate_squared_distance(
                    m,
                    QT_j,
                    M_T[i + k],   # SHOULD BE CHANGED TO: M_T[j + k] ??
                    Σ_T[i + k],    # SHOULD BE CHANGED TO: Σ_T[j + k] ??
                    μ_Q[j + k],   # SHOULD BE CHANGED TO: μ_Q[i + k] ??
                    σ_Q[j + k],    # SHOULD BE CHANGED TO: σ_Q[i + k] ??
                )
```

Although this last part makes sense to me and I think we should change `i` to `j` AND `j` to `i` as mentioned above, I am confused as to how the tests are passing... Because the naive version uses a distance matrix and it seems it has no miscalculation. So, maybe I missed something above...

**Comment by NimaSarajpoor** [comment]
UPDATE:
So, I think the reason that we did not catch issue (3) is because of the fact that we never entered those loops. Except one test function ` test_prescrump_self_join_larger_window` that only tests self-join in which swapping `i` and `j` does not change the result.

**Comment by seanlaw** [comment]
1. Please submit a new PR to address this issue (instead of using #595)
2. I think this is a good opportunity to use test-driven development. Write the new unit test first that tests `test_prescrump_AB_join_larger_window` and then make sure all tests pass except for this new one. Then modify the code to ensure that all tests pass (but without changing the other tests).

> So, I think i should be used whenever we want to talk about subseqs in T_A.

I agree with this. Consistency is important so let's try to make this right. It's been a long time since I looked at it and, certainly, I had no paid too much attention to AB-joins at the time.
