### ISSUE TITLE
Incorrect descriptions in Docstrings

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#652]
I have been reading the module `mpdist` and I noticed:

* The description of the output of `_mpdist_vect` is missing from its docstring
* The description of `μ_Q` and `σ_Q` (in `_mpdist_vect`) are not correct. I think they should be `numpy.ndarrays` not `float`.
* The description of `μ_Q` and `σ_Q` (in `core. _mass_distance_matrix`) are not correct. I think they should be `numpy.ndarrays` not `float`.

**Comment by seanlaw** [comment]
Thanks for identifying this @NimaSarajpoor. I just took a look and I think you are correct. Would you mind submitting a PR to address this?

**Comment by NimaSarajpoor** [comment]
Sure, I will do so in a few days.
