### ISSUE TITLE
A few minor issues in stumpy.motifs

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#673]
I investigated `stumpy.motifs` for the data provided in Discussion #670 (also attached here: [your_time_seriesa.csv](https://github.com/TDAmeritrade/stumpy/files/9546933/your_time_series.csv)) and, throughout my investigation, I noticed there are a few things that could/should be taken care of.

(1) The default value of `cutoff` can be set to `0`. While this is not a problem, it is an extreme condition that only results in finding perfect motif (i.e. `distance-to-nn = 0`). So, I think the following change might be good:
```
if cutoff is None:  # pragma: no cover
        P_copy = P.copy().astype(np.float64)
        P_copy[np.isinf(P_copy)] = np.nan
        
        cutoff = np.nanmax(
            [np.nanmean(P_copy) - 2.0 * np.nanstd(P_copy), A]
        )
       
        if cutoff == 0:
              cutoff = np.sort(np.unique(P_copy))[1]  # np.partition is a better choice 
```
In fact `cutoff=0` is the main reason behind the problem discussed in Discussion #670 .

(2) `query_matches` in:

```
# in stumpy/motifs.py

# in function _motifs(...)

query_matches = match(  
            Q,
            T,
            M_T=M_T,
            Σ_T=Σ_T,
            max_matches=None,
            max_distance=max_distance,
            atol=atol,
            query_idx=candidate_idx,
        )

if len(query_matches) > min_neighbors:
        motif_distances.append(query_matches[:max_matches, 0])
        motif_indices.append(query_matches[:max_matches, 1])

      
for idx in query_matches[:, 1]:
    core.apply_exclusion_zone(P, int(idx), excl_zone, np.inf)
```
might be empty. In such case, `for idx in query_matches[:, 1]:` can result in error. Hence, we should do:

```
if len(query_matches) > 0:
      for idx in query_matches[:, 1]:
          core.apply_exclusion_zone(P, int(idx), excl_zone, np.inf)
else:
    core.apply_exclusion_zone(P, candidate_idx, excl_zone, np.inf) 
```

(3) Let's say a motif at index `idx` has matrix profile value of `v`. So, we expect to see `match_distances=[v, ..]` and `match_indices=[idx, ...]`. However, if we use the attached data, we can see that:

```
m = 5
normalize = True

mp = stumpy.stump(T, m, normalize=normalize)
P = mp[:, 0].astype(np.float64)

motif_dist, motif_indices = stumpy.motifs(
    T, 
    P, 
    min_neighbors=1,
    max_distance=None,
    cutoff=None,
    max_motifs=2,
)
```
And,
```
>>> motif_dist[1]
[1.10509969e-07, ...]

>>> motif_indices[1]
[151, ...]
```

However, `mp[151, 0]` is `0.0`. So, we should have seen `0.0` instead of `1.10509969e-07`. I am not sure if I missed anything here or not. Note that the `cutoff` is set  to `0` in this case. This means that the result might sound strange because when `cutoff` is `zero`, we should expect `0` as the first element in `motif_dist[1]`

**Comment by seanlaw** [comment]
> (1) The default value of cutoff can be set to 0. While this is not a problem, it is an extreme condition that only results in finding perfect motif (i.e. distance-to-nn = 0).

I understand but `stumpy.motifs` isn't meant to apply out-of-the-box to extreme cases. We should avoid solving for rare situations. In this case, we should do:

```
if cutoff == 0:
    suggested_cutoff = np.partition(P, 1)[1]
    logger.warn("The `cutoff` has been set to 0.0 and may result in little/no motifs being returned.")
    logger.warn(f"You may consider increasing the cutoff for more results (e.g., {suggested_cutoff})") 
```

So, we don't make this decision for the user and force them to think through what this means. What do you think?

> (2) In such case, for idx in query_matches[:, 1]: can result in error.

Can you provide an example that triggers the error? In that case, wouldn't it be cleaner to do something like this instead:

```
        if len(query_matches) > min_neighbors:
            motif_distances.append(query_matches[:max_matches, 0])
            motif_indices.append(query_matches[:max_matches, 1])

        if len(query_matches) == 0:
            # Basically, make a fake `query_matches` with only `candidate idx` inserted and nothing else
            query_matches = np.array([[np.nan, candidate_idx]])

        for idx in query_matches[:, 1]:
            core.apply_exclusion_zone(P, int(idx), excl_zone, np.inf)
```

> (3) However, mp[151, 0] is 0.0. So, we should have seen 0.0 instead of 1.10509969e-07. I am not sure if I missed anything here or not. Note that the cutoff is set to 0 in this case. This means that the result might sound strange because when cutoff is zero, we should expect 0 as the first element in motif_dist[1]

I think there is a misunderstanding here. The `cutoff` is strictly used to identify candidate indices that have a matrix profile distance value (i.e., distance to one nearest neighbor) below the cutoff value. Technically, `motif_dist` and `motif_indices` correspond to subsequence **matches** to the aforementioned candidate subsequences and, in those cases, the distance criteria is controlled separately by the `max_distance` parameter. In other words, you can have a candidate subsequence that has a perfectly matching one-nearest neighbor (with a 0.0 distance) but, for that candidate index, we return at most the top `max_matches` that have a distance below `max_distance`. So, again, cutoff does not affect the matches that get returned and only affects the list of candidates.

**Comment by NimaSarajpoor** [comment]
> So, we don't make this decision for the user and force them to think through what this means. What do you think?

You are right. we should not  make decision for the user as much as possible. I think providing a warning is much better.



> Can you provide an example that triggers the error?

data : [your_time_series.csv](https://github.com/TDAmeritrade/stumpy/files/9549510/your_time_series.csv)
```
# T : the data in the attached file
m = 5
mp = stumpy.stump(T, m)
P = mp[:, 0].astype(np.float64)

>>> stumpy.motifs(T, P, cutoff=np.mean(P), max_motifs=4)
```

And, the error:
```
File ~\anaconda3\envs\stumpy\lib\site-packages\stumpy\motifs.py:132, in _motifs(T, P, M_T, Σ_T, excl_zone, min_neighbors, max_distance, cutoff, max_matches, max_motifs, atol)
    129     motif_distances.append(query_matches[:max_matches, 0])
    130     motif_indices.append(query_matches[:max_matches, 1])
--> 132 for idx in query_matches[:, 1]:
    133     core.apply_exclusion_zone(P, int(idx), excl_zone, np.inf)
    135 candidate_idx = np.argmin(P[-1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
The error is raised because `query_matches` is empty here.

I think your suggestion (creating fake `query_matches`) is cleaner.

**Comment by NimaSarajpoor** [comment]
> I think there is a misunderstanding here.

Yeah...I thought more and you are correct. `mp[151, 0]` is not related to the first value of distance in the set of  matches (but it is  in fact the value of the second element in the list of distances of matches discovered for subseq at index 151)


> I'm not sure why the self-match isn't zero but it is "close enough" in this case that I'm guessing that it is due to precision issues

Yeah...I got confused before. As you said, the first element is first match (and hence, it should be `0` anyway). But, like you.. I do not know why it is not zero. Also, I think the second element in `[1.29047841e-07, 1.15423898e-07, ...]`  should also be zero because `mp[151, 0]` is zero. 


> Perhaps, it might make sense to add a note to the `cutoff` parameter to adjust the `max_distance`

`cutoff` is only for the distance between a motif and its 1NN (the matrix profile value). So, when `cutoff=0`, a user expects to see the second element in the list of distances (of matches) to be `<= cutoff`, hence `0` in this case. (The first element, as you mentioned, is self-match and it is zero anyway). So, I am not sure if we should add note about adjusting `max_distance` as it can be unrelated (or maybe you have a particular reason in your mind that I may have missed/misunderstood)

**Comment by seanlaw** [comment]
> Yeah...I got confused before. As you said, the first element is self match (and hence, it should be 0 anyway). But, like you.. I do not know why it is not zero. Also, I think the second element in [1.29047841e-07, 1.15423898e-07, ...] should be zero because mp[151, 0] is zero.

Okay, so I checked and all of this actually makes sense. When `cutoff=None`, the `cutoff` got set to `0.0` since that is what is below two stddevs relative to the mean matrix profile value. This `cutoff` only reveals `idx = 11` and `idx = 151` to be the indices for candidate subsequences. This `cutoff` is no longer used for anything else. Then, we compute the distance between `T[11 : 11+m]` and `T` and extract all subsequences that have a distance smaller than `max_distance`. In this case, since `max_distance=None`, it was set to `1.5547467740567846` for `idx=11` and `1.8967706187412408 ` for `idx=151`. Any subsequence matches below those respective `max_distance` values are returned.

Now, the reason why the two self-matches are not zero is due to numerical precision:

```
print(stumpy.core.mass(T[11:151+m], T)[11])
print(stumpy.core.mass(T[151:151+m], T)[151])
```

Gives:

```
1.0536712127723508e-07
1.2904784139758926e-07
```

I notice that precision issues tends to be more pronounced when `m` is small. Though, I'm not sure there is really an issue here.

> So, when cutoff=0, a user expects to see the second element in the list of distances (of matches) to be <= cutoff, hence 0 in this case. 

No, this is not correct. The cutoff is only for selecting the set of candidate subsequence (indices) and has nothing to do with the matches being returned.

**Comment by NimaSarajpoor** [comment]
> > So, when cutoff=0, a user expects to see the second element in the list of distances (of matches) to be <= cutoff, hence 0 in this case.
> 
> No, this is not correct. The cutoff is only for selecting the set of candidate subsequence (indices) and has nothing to do with the matches being returned.

Maybe I am wrong...but this is what I see when I read the code:

```
# in stumpy/motifs.py
# in function _motifs.py

profile_value = P[-1, candidate_idx]
if profile_value > cutoff or not np.isfinite(profile_value):  # pragma: no cover
    break
```

So, `profile value`  is actually the distance between `candidate_idx` and its non-trivial 1NN (because it is chosen from matrix profile). Later in the function, we call function `match` to find the matches to `candidate_idx` using its distance profile. So, the indices of matches is an array where the first element is self-match, the second element is its 1NN, and its third element is second-NN, and so on.

In fact,  let's take a look at the distances and indices of the matches for `candidate_idx=151`:
 
> And for candidate_idx=151, the set of matches have a distance of:
> `[1.29047841e-07, 1.15423898e-07, 3.85898606e-01, 6.83177904e-01,
         6.86564262e-01, 7.19938198e-01, 1.02741328e+00, 1.66644709e+00]`
> and indices of:
`[151, 222,  23,  12,  18,   7, 231,  33]`

we can see that the second element is `222`, and if check out the value of `mp[151,1]`, we can see that it is `222` as well. And, `mp[151, 0]` is `0.0`, which is the distance between 151 and 222. However, the second element in the distances of matches is not zeros. So, we have (at least) two cases of imprecision here.

**Comment by seanlaw** [comment]
> So, profile value is actually the distance between candidate_idx and its non-trivial 1NN (because it is chosen from matrix profile). Later in the function, we call function match to find the matches to candidate_idx using its distance profile. So, the indices of matches is an array where the first element is self-match, the second element is its 1NN, and its third element is second-NN, and so on.

Yes, I have no objection to this paragraph but note that `cutoff` is not used in finding `matches`. That is the only point that I am trying to make here.

> So, when cutoff=0, a user expects to see the second element in the list of distances (of matches) to be <= cutoff, hence 0 in this case.

I was trying to say that this statement is the wrong mindset for the user. Instead, I would change it to:

> So, even when cutoff=0.0, the user would expect to see the second element in the list of distances (of matches) to be <= max_distance (not <= 0.0  !!).

> So, the second element in the distances of matches should have been zero (the profile_value, which was <= cutoff). So, we have (at least) two cases of imprecision here.

Yes, there is more imprecision problems in this case:

```
print(stumpy.core.mass(T[151:151+m], T)[222])
```

Gives:

```
1.1542389828584841e-07
```

which is pretty bad but acceptable 😢

**Comment by NimaSarajpoor** [comment]
> I was trying to say that this statement is the wrong mindset for the user. Instead, I would change it to:
> 
> > So, even when cutoff=0.0, the user would expect to see the all elements in the list of distances (of matches) to be <= max_distance (not <= 0.0  !!).

Got it 👍
