### ISSUE TITLE
None of your Notebooks Neither working in Colab nor working in Anaconda Jupiter Notebooks 

### ISSUE THREAD

**Issue by BalasubramaniamDakshinamoorthi** [TDAmeritrade/stumpy#688]
None of your Notebooks Neither working in Colab nor working in Anaconda Jupiter Notebooks ,  getting this error 
Unreadable Notebook: Tutorial_Fast_Approximate_Matrix_Profiles.ipynb NotJSONError("Notebook does not appear to be JSON: '../docs/Tutorial_Fast_Approximate_Matri...")

**Comment by seanlaw** [comment]
Unfortunately, without more information, it's nearly impossible to guess at what you are doing and why it "isn't working". These notebooks seem to be working fine for others and for myself locally. I just verified that you can access them via [our tutorials](https://stumpy.readthedocs.io/en/latest/tutorials.html) OR, alternatively, you can access interactive versions of the notebook via the MyBinder link at the top of each tutorial (e.g., [try this one](https://mybinder.org/v2/gh/TDAmeritrade/stumpy/main?filepath=notebooks/Tutorial_Fast_Approximate_Matrix_Profiles.ipynb)). I could be wrong but this doesn't appear to be an issue with STUMPY or the notebook tutorials and, instead, it appears to be a problem with the environment that you are attempting to run them in.

**Comment by seanlaw** [comment]
@BalasubramaniamDakshinamoorthi Closing this for now due to inactivity but please feel free to re-open if you have more questions.
