### ISSUE TITLE
Replace `is False` with `== False`  and Refactor warning of `ignore_trivial`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#693]
(1) As discussed in #691, `is` checks if two objects have the same `id`s or not. The outcome of an expression can be `False` but it can have different `id` than the object `False`. Hence, we need to replace `is False` with `== False`

(2) As suggested by @seanlaw in #691, it is better to refactor the warning messages that check the param `ignore_trivial` and add test function(s) to check its functionality

**Comment by NimaSarajpoor** [comment]
@seanlaw 
So I checked the `.py` files that contain `is False`. I was wondering if it would be okay to take care of `top-k` PR #595 first and then take care of this one. I think if we want to merge this first, I might get several merge conflicts in `top-k` branch. I think it would be easier. 

What do you think?

**Comment by seanlaw** [comment]
That sounds good

**Comment by NimaSarajpoor** [comment]
I have been thinking about `ignore_trivial` lately, and I cannot get my head around it. In below, I am going to consider four different cases (In all of the following cases, the input `T_A` must be provided)

* case 1: T_B is None, ignore_trivial=True --> self-match, reasonable
* case 2: T_B is not None, ignore_trivial=False ---> AB-join, reasonable

* case 3: T_B is None, ignore_trivial=False
This one is meaningless because we will end of with all 0 when k=1 (in top-k). However, the point I am about to make is something else! When `ignore_trivial ==False`, we are traversing ALL diagonals (see [these lines](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/stump.py#L686-L689)). Well, one might say: that is okay. we are just wasting some time. But, a similar issue becomes a problem in case 4!

* case 4: T_B is not None, ignore_trivial=True
Now, if I look at [these lines](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/stump.py#L686-L689) again, I can see that I am just considering half of diagonals! Isn't this strage? I think we should have considered all distance matrix (i.e. ALL diagonals).

**Comment by seanlaw** [comment]
I think your assessment seems reasonable. 

* Case 1: Normal
* Case 2: Normal
* Case 3: In our current setup, this should not be possible because the moment `T_B is None` then it implies a self-join and `T_B = T_A` and `ignore_trivial` is automatically set to `True` and so Case 3 becomes Case 1
* Case 4: We hoped that it would hit a warning that the user is likely doing something wrong (although it should be `== False` instead of `is False`!!)

https://github.com/TDAmeritrade/stumpy/blob/3228917a9d7896844295da2855f657871a181994/stumpy/stump.py#L676-L678

I feel like I'm not getting your point. What are you trying t wrap your head around?

**Comment by NimaSarajpoor** [comment]
> Case 3: In our current setup, this should not be possible because the moment T_B is None then it implies a self-join and T_B = T_A and ignore_trivial is automatically set to True and so Case 3 becomes Case 1

Right! I missed it!


> I feel like I'm not getting your point. What are you trying t wrap your head around?

I haven' t investigated the whole thing but I think case4 can result in weird output.

Example:
```
T_A = np.random.rand(1000)
T_B = np.random.rand(100)
m=10

out = stumpy.stump(T_A, m, T_B, ignore_trivial=True)

>>>out
array([[2.151248127028018, 64, -1, 64],
       [2.2832053303081894, 65, -1, 65],
       [2.263242208500775, 55, -1, 55],
       ...,
       [inf, -1, -1, -1],
       [inf, -1, -1, -1],
       [inf, -1, -1, -1]], dtype=object)
```

Should I get `inf` for the last subseq when `ignore_trivial==True`?  Maybe the problem is somewhere else. What I am saying is that, the warning may not be enough. Maybe I should stop overthinking this `ignore_trivial` thing 😄

**Comment by seanlaw** [comment]
Basically, the results of `stumpy.stump(T_A, m, T_B, ignore_trivial=True)` makes absolutely zero sense unless `T_A == T_B`. Let's say `T_A` and `T_B` are completely unrelated, then the trivial zone in `T_A` has no meaning relative to `T_B`.

**Comment by NimaSarajpoor** [comment]
> Basically, the results of stumpy.stump(T_A, m, T_B, ignore_trivial=True) makes absolutely zero sense unless T_A == T_B.

EXACTLY!!!

> Additionally, the diagonals selected also do not make sense.

YES! EXACTLY! this is what I tried to say when I provided the link to [these lines](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/stump.py#L686-L689) in my previous  comment

> Perhaps we should disallow ignore_trivial=True when T_B is not None. This is the logical thing to do

I think we should.

**Comment by seanlaw** [comment]
> I think we should. (btw, I know you prefer to keep the backward compatibility if possible. so, I think you can better decide whether this is the right thing to do or not)

In this case, we would sum it up as a bug. I am okay changing the helper function to:

```
# core.py
def check_ignore_trivial(T_A, T_B, ignore_trivial):
    if ignore_trivial == False and core.are_arrays_equal(T_A, T_B):  # pragma: no cover
        logger.warning("Arrays T_A, T_B are equal, which implies a self-join.")
        logger.warning("Try setting `ignore_trivial = True`.")

    if ignore_trivial and core.are_arrays_equal(T_A, T_B) == False:  # pragma: no cover
        error = "Arrays T_A, T_B are not equal, which implies an AB-join.\n"
        error += "Try setting `ignore_trivial = False`."
        raise ValueError(error)
```

Either that or we simply force `ignore_trivial=False` since we know that it should never be false when core.are_arrays_equal(T_A, T_B) == False. So, in `stumpy.stump` we'd replace:

```
# stumpy.stump function

if ignore_trivial and core.are_arrays_equal(T_A, T_B) == False:  # pragma: no cover
    logger.warning("Arrays T_A, T_B are not equal, which implies an AB-join.")
    logger.warning("`ignore_trivial` has been automatically set to `False`.")
    ignore_trivial = False    
```

**Comment by NimaSarajpoor** [comment]
> To some extent, I prefer the latter since it avoids erroring out.

Yeah.., The latter has less burden for the user, and it also makes sense to make such change ourselves.

**Comment by seanlaw** [comment]
> Yeah.., The latter has less burden for the user, and it also makes sense to make such change ourselves.

Cool. Let's do that
