### ISSUE TITLE
Move to CalVer

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#701]
Currently, STUMPY uses Semantic Versioning. It might make sense to switch to Calendar Versioning and follow `Year.Month.Micro` where `Micro` would start at zero when there is a new version being released in a new year+month and all subsequent releases in that same year+month would simply increment `Micro` by one. So, `Micro` is **not** related to the day-of-the-month but, instead, simply a monthly release counter that resets to zero every month.

The benefit of [CalVer](https://calver.org/) is that it allows users to immediately know how outdated their version is. Of course, STUMPY may not be releasing frequently enough to benefit from any of this.

**Comment by seanlaw** [comment]
@jacobtomlinson wrote an [excellent article](https://jacobtomlinson.dev/posts/2023/sometimes-i-regret-using-calver/) on this topic and I am now convinced that STUMPY would find little value by switching to CalVer.

Closing this...

**Comment by jacobtomlinson** [comment]
You might find [EffVer](https://jacobtomlinson.dev/effver/) interesting!
