### ISSUE TITLE
module 'cffi' has no attribute 'FFI'

### ISSUE THREAD

**Issue by snnmst** [TDAmeritrade/stumpy#704]
Hi,

I installed stumpy via : pip install stumpy and I have numpy, scipy, and numba installed. When trying to code snippet below,

import stumpy
your_time_series = np.random.rand(10000)
window_size = 50  # Approximately, how many data points might be found in a pattern

matrix_profile = stumpy.stump(your_time_series, m=window_size)

I'm encountering that error : module 'cffi' has no attribute 'FFI'

could anyone help please ?

**Comment by seanlaw** [comment]
@snnmst Thank you for your question and welcome to the STUMPY community. Can you provide the full Python traceback (long error) being printed out? The simplest thing you can try is `pip install cffi` but it is unlikely a problem with STUMPY. Additionally, can you please provide the output from `pip list`?

**Comment by snnmst** [comment]
@seanlaw, When I set up a new clean environment and tried it, the problem was solved. Thanks for your time.
