### ISSUE TITLE
Question: Clustering w/ Motifs

### ISSUE THREAD

**Issue by pindapuj** [TDAmeritrade/stumpy#71]
Thank you for this great package! 

I'm trying to cluster a set of time series, based on a "shared" set of motifs, and corresponding sub-sequences. I thought of extracting the motifs given the matrix profile for each time series separately, and then doing some k-means clustering based on the subsequences of each time series over all motifs. (The subsequences for each found motif for a given time series would represent the "features.") 
```
//pseudo-code
for sample in sample_set:
    motif_set += find_motifs_from_sample(sample)

//some post processing b/c the motifs will result in different lengths
clusters  = kmeans(motif_set)
   ```
But, I think that this approach amplifies individual time series differences, so the motifs aren't generalizable. Instead, I was wondering if it made more sense to find motifs _shared_ across the set of time series. (Not sure if this is the correct way to think about the time series set. Its not really a multi-dimensional dataset b/c each sample is a representation of the same phenomenon.) 

```
for i in sample_set:
   for j in sample_set:
      mp = matrix_profile(i,j)
      motifs += find_motifs_from_profile(mp)

//somehow compute which motifs are most shared

// compute the subsequences for this shared set of motifs
// use those as "features" for kmeans.
```

Is there a natural or better way of finding these motifs or using matrix-profiles/motifs for clustering? For example, I assume it would be incorrect to simply concatenate all my time series together separated by nans, and find the matrix profile and motifs for the entire profile. Then, treat those motifs as "shared" for clustering.

Any help would be appreciated! I'm very new to the world of time series mining. Thank you!

**Comment by seanlaw** [comment]
@pindapuj Thank you for your interest in STUMPY and please correct me if I'm not understanding correctly. It sounds like you are essentially looking for a distance measure that allows you to compare multiple time series (of course, you can use that distance measure as input for clustering). Is this correct?

**Comment by seanlaw** [comment]
@pindapuj I'm always curious as to what applications there are. Can you give me a brief description of what specific use case you are using STUMPY for?

**Comment by pindapuj** [comment]
@seanlaw Yes, I believe that is correct. If I understood correctly, I would have pairwise similarity and not necessarily full set similarity. (This is why I planning to compute the motifs across the entire set of observations and using the corresponding sub sequences as "features"-- I'd capture "global" structure.) MPdist does implicitly capture pair-wise motif-like information b/c it looks for the nearest neighbor subsequences. If I understand correctly, I'd be doing the following. 
```
   // From #46 
    Compute the matrix profile AB for stumpy.stump(A, m=50, T_B=B, ignore_trivial=False)
    Compute the matrix profile BA for stumpy.stump(B, m=50, T_B=A, ignore_trivial=False)
    Concatenate both matrix profiles into PABBA
    Choose some k that is 5 percent of 2 * n
```
Say I have n samples. Then I would need to do _n^2_ matrix profile computations, and pull out k for each of them. 

```
//len(obs_a) = 30
//k = 3
// mpdist is upper triangular
mpdist = np.empty((n,n))

for i in range(len(observations)):
     for j in range(i,len(observations)):
         if i != j:
               mp_ab= stumpy.stump(observations[i], m=4, T_B=observations[j], ignore_trivial=False)
               mp_ba = stumpy.stumpy(observations[j], m=4, T_B=observation[i], ignore_trivial=False)
               mp_abba = np.concat(mp_ab,mp_ba)
               \\ Can I really just pull out the k lowest?
               k_smallest =  np.argpartition(mp_abba,k=3)
               mp_dist[i][j] = k_smallest
               mp_dist[j][i] = k_smallest

\\ Now, given the full matrix of mp_dist, each row represents the features of each observation.  
```
Each row of the matrix, can be seen as that observation's feature vector. The maximum of the row gives the 1NN, but it need not be symmetric. ( NN(A) = B != NN(B) = A).  I can use kmeans or some other clustering algorithm to group the edges. 

I'm using STUMPY to do some exploratory analysis on some graph edge streams. I'd like understand the different types of edges that occur in my graph setting, so that I can use the edge clusters as "prototypes" for predicting graph behavior. 

Thank you for your help!

**Comment by seanlaw** [comment]
Yes, I believe that what you showed above is the right approach. I strongly suggest that you go over the MPdist paper if you haven’t already. 

Please report back and let us know if it worked out!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seanlaw** [comment]
@pindapuj Closing this for now but feel free to re-open if you have any further questions or comments!
