### ISSUE TITLE
issue in documentation

### ISSUE THREAD

**Issue by pavlexander** [TDAmeritrade/stumpy#711]
Hi,

I have just been reading trough your documentation on the page https://stumpy.readthedocs.io/en/latest/Tutorial_The_Matrix_Profile.html

and it seems like you have an error there in formula in section **Euclidean Distance**

![image](https://user-images.githubusercontent.com/20644772/201199316-2ef54ad2-d073-43fb-b0ba-a315091fb4a9.png)

For the first 3 calculations the data point of subsequence 2 is substracted from subsequence 1, but in case of the last pair of values it's the opposite.

If I understand correctly it should have been 10 - 2, instead of 2 - 10..

**Comment by seanlaw** [comment]
@pavlexander Yes, you're absolutely right! However, since it's `(2-10)` squared, the result is the same as `(10-2)` squared (i.e., both will give you `64` as answer).

**Comment by pavlexander** [comment]
I am absolutely amazed by the documentation of this library! It has so many examples, with the real world use-cases (queen song vs ice ice baby song comparison, as an example). I wish all of the libraries were following your approach!

On the topic - I will mark this "issue" as closed, since, as you mentioned, the result is the same and I don't expect this discussion to continue any further :)

**Comment by seanlaw** [comment]
@pavlexander Thank you for your valuable feedback and kind words! Please let us know if there's any way that we can improve your user experience.
