### ISSUE TITLE
In `aampi`: wrong left matrix profile index when its corresponding value is np.inf

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#721]
I think the existing `naive.aampi` (and its performant version) are incorrect in handling nan value.

```
# Example
m = 3
seed = 10844
n = 30
T = np.random.rand(n)
T[-1] = np.nan

ref_mp = naive.aampi_egress(T, m)
t = np.random.rand()
ref_mp.update(t) # egress

>>> ref_mp.left_I_[-1]
1
```
However, I think the last value in `ref_mp.left_I_` should be `-1` because the value-before-last in time series is `np.nan`. 
(and hence the last subsequence contains non-finite value)

---

It seems the problem lies in the fact that 
```
# in tests/naive.py
# in aampi

D = core.mass_absolute(self._T[-self._m :], self._T)   # btw, this line is redundant in the script
D = cdist(
            core.rolling_window(self._T[-self._m :], self._m),
            core.rolling_window(self._T, self._m),
            metric="minkowski",
            p=self._p,
        )[0]
```

gives `D` with `nan` values. Therefore, later in the code, there is the following if-block, which will not be effective in handing `nan`:

```
I_last = np.argmin(D)
if np.isinf(D[I_last]):
    self.I_[-1] = -1
    self.P_[-1] = np.inf
```

Solutions:
* we can do `if not np.isfinite(D[I_last])`
* Or, we can just preprocess `T` right from the beginning and get rid of `np.inf` / `np.nan`

And, we should fix the performant version `stumpy/aampi.py` as well.

---

I can handle it in PR #714 if that is okay.

**Comment by seanlaw** [comment]
> And, we should fix the performant version stumpy/aampi.py as well.

Can you explain what needs to be fixed in the performant version? From what I can see, it looks fine and should be able to handle `np.nan` and `np.inf`?

**Comment by seanlaw** [comment]
> I can handle it in PR https://github.com/TDAmeritrade/stumpy/pull/714 if that is okay.

Actually, I'd prefer for this to be a separate PR

**Comment by NimaSarajpoor** [comment]
sorry...I made a mistake in explanation. It was around 4 a.m. 😄 


> Unit tests already exist for checking non-finite numbers. Why aren't those failing? OR why are they insufficient for catching this?

I think this is because we have problems in both naive and performant versions. 


> > And, we should fix the performant version stumpy/aampi.py as well.
> 
> Can you explain what needs to be fixed in the performant version? From what I can see, it looks fine and should be able to handle `np.nan` and `np.inf`?

**In performant**
we have the following lines of code:
https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/aampi.py#L219-L231

Note that we handle `inf` for `P` and `I`, but not for `left_P` and `left_I`. In other words, we should check to see if `left_P` is  `np.inf`, reset `left_I` to `-1`.

So, something like this:
```
# line 228
self._left_I[-1] = I_last + self._n_appended
self._left_P[-1] = D[I_last]

if np.isinf(self._left_P[-1]):
     self._left_I[-1] = -1
```

And, we should also check the non-egress `update` method as well as we have a similar situation there.


**In naive version**
we have the same problem:
https://github.com/TDAmeritrade/stumpy/blob/main/tests/naive.py#L786-L787

And, we need to check to see if this `left_P[-1]` is `np.inf` or not. If yes, then we need to set `left_I[-1]` to `-1`.

**Comment by seanlaw** [comment]
@NimaSarajpoor Can you confirm whether this problem also exists for the `left_P` in `stumpi` as well?

**Comment by seanlaw** [comment]
> Note that we handle inf for P and I, but not for left_P and left_I. In other words, we should check to see if left_P is np.inf, reset left_I to -1.

Ahh, I see. Now that I look at line 228, it does look strange. Is it incorrect to combine things and do:

```
        if np.isinf(D[I_last]):
            self._I[-1] = -1
            self._P[-1] = np.inf
            self._left_I[-1] = -1
            self._left_P[-1] = np.inf
        else:
            self._I[-1] = I_last + self._n_appended
            self._P[-1] = D[I_last]
            self._left_I[-1] = I_last + self._n_appended
            self._left_P[-1] = D[I_last]
```

**Comment by NimaSarajpoor** [comment]
> @NimaSarajpoor Can you confirm whether this problem also exists for the `left_P` in `stumpi` as well?

`stumpi` is good. 



> Is it incorrect to combine things and do:

No, it is not incorrect. But, we can make it cleaner:
```
if np.isinf(D[I_last]):
            self._I[-1] = -1
            self._P[-1] = np.inf
        else:
            self._I[-1] = I_last + self._n_appended
            self._P[-1] = D[I_last]

self._left_I[-1] = self._I[-1]
self._left_P[-1] = self._P[-1]
```

Recall that for the last subsequence, the profile/index is the same as left-profile/left-index. 
(As a side note, the profile/index of the first subseq is the same as its right-profile/index.

**Comment by seanlaw** [comment]
> Recall that for the last subsequence, the profile/index is the same as left-profile/left-index.

Of course! Thanks for the reminder. I accept you proposal
