### ISSUE TITLE
Use mocks in tests instead of overwriting config variables

### ISSUE THREAD

**Issue by alvii147** [TDAmeritrade/stumpy#722]
There are numerous instances where `config` variables are overwritten for the purpose of testing. I feel like using [unittest mocks](https://docs.python.org/3/library/unittest.mock.html) to temporarily change the `config` variables is a cleaner way of doing this, especially because the unittest mock/patch module was written specifically for this use case. It also makes things more "DRY", as we don't have to set the `config` variable back to its original value once we're done.

Here's an example from `tests/test_core.py`:

```python
@pytest.mark.parametrize("Q, T", test_data)
def test_compute_mean_std_chunked(Q, T):
    m = Q.shape[0]

    config.STUMPY_MEAN_STD_NUM_CHUNKS = 2
    ref_μ_Q, ref_σ_Q = naive.compute_mean_std(Q, m)
    ref_M_T, ref_Σ_T = naive.compute_mean_std(T, m)
    comp_μ_Q, comp_σ_Q = core.compute_mean_std(Q, m)
    comp_M_T, comp_Σ_T = core.compute_mean_std(T, m)
    config.STUMPY_MEAN_STD_NUM_CHUNKS = 1

    npt.assert_almost_equal(ref_μ_Q, comp_μ_Q)
    npt.assert_almost_equal(ref_σ_Q, comp_σ_Q)
    npt.assert_almost_equal(ref_M_T, comp_M_T)
    npt.assert_almost_equal(ref_Σ_T, comp_Σ_T)
```

Instead of directly changing `config.STUMPY_MEAN_STD_NUM_CHUNKS`, we would do this:

```python
from unittest.mock import patch


@pytest.mark.parametrize("Q, T", test_data)
def test_compute_mean_std_chunked(Q, T):
    m = Q.shape[0]

    with patch("config.STUMPY_MEAN_STD_NUM_CHUNKS", 2):
        # STUMPY_MEAN_STD_NUM_CHUNKS is set to 2 in this "with" block
        ref_μ_Q, ref_σ_Q = naive.compute_mean_std(Q, m)
        ref_M_T, ref_Σ_T = naive.compute_mean_std(T, m)
        comp_μ_Q, comp_σ_Q = core.compute_mean_std(Q, m)
        comp_M_T, comp_Σ_T = core.compute_mean_std(T, m)

    # STUMPY_MEAN_STD_NUM_CHUNKS is back to its original value, i.e. 1
    npt.assert_almost_equal(ref_μ_Q, comp_μ_Q)
    npt.assert_almost_equal(ref_σ_Q, comp_σ_Q)
    npt.assert_almost_equal(ref_M_T, comp_M_T)
    npt.assert_almost_equal(ref_Σ_T, comp_Σ_T)
```

**Comment by alvii147** [comment]
@seanlaw let me know if you think we should do it this way. If you think we should leave the testcases as-is, I'm happy to close this issue.

**Comment by seanlaw** [comment]
@alvii147 Admittedly, I am not well versed in mocking but I see the value here. If you would submit a PR for this along with any other cases where a `patch` could be used then I'd be happy to merge it.
