### ISSUE TITLE
 if-continue block in `scrump` and `scraamp` 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#750]
It seems that this

https://github.com/TDAmeritrade/stumpy/blob/8da71ecec45e947cf448eb3dba8a75c98f5dbfe2/stumpy/scrump.py#L209-L211

is never executed, and even if it is executed, there will be no change! 

The reason is that: 
(1) all elements of `P_squared` are initially set to `np.inf` and their corresponding indices in `I` are initially set to -1. 
(2) `P_squared` is sorted ascendingly. Thus, after finding at least one finite distance, the value `P_squared[thread_idx, i, 0]` becomes finite. This is because the smallest distance will be at index 0.

Therefore, after finding the first finite distance between subseq `i` and one of its neighbor, the value at `P_squared[thread_idx, i, 0]` becomes finite. Note that if we never find a finite distance for subseq `i`, then all values in `P_squared[thread_idx, i, :]` remain `np.inf` and their corresponding indices remain `-1`. Hence, if-block results in no change.

We have a similar situation in `scraamp`. see [Lines 194-197](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/scraamp.py#L194-L197)

---

The only drawback is that `P_squared` is a variable that is passed to the function `_prescrump`. Hence, we may need to improve the docstring to let user know that the default value in `P_squared` is `np.inf`, and its corresponding index in `I` is `-1`.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
On second thought, I now think the `continue` part of the if-block is important. I think we can replace the aforementioned if-block with this:

```
# in scrump.py
# lines 209-211 can be replaced with:

if squared_distance_profile[nn_i] == np.inf:
     continue
``` 

And, I think this is more readable and better connected to the code.

**Comment by seanlaw** [comment]
@NimaSarajpoor What happens if the input time series contains all `np.nan`?

**Comment by seanlaw** [comment]
Btw, in these scenarios, instead of referencing the lines of code, you can copy/paste the "permalink" (as I've edited in your original post) and that will display the code in-line

**Comment by NimaSarajpoor** [comment]
# NOTE I
> What happens if the input time series contains all np.nan?

When input contains all `np.nan`,  each distance profile (`squared_distance_profile`) will contain only `np.inf` value. That means the if-condition in the following if-block becomes `False` and we do not update `P_squared`.

https://github.com/TDAmeritrade/stumpy/blob/8da71ecec45e947cf448eb3dba8a75c98f5dbfe2/stumpy/scrump.py#L194-L207

And, that is okay because `P_squared` is initially filled with `np.inf`. That means this if-block:
https://github.com/TDAmeritrade/stumpy/blob/8da71ecec45e947cf448eb3dba8a75c98f5dbfe2/stumpy/scrump.py#L209-L211

is executed... but the line `I[thread_idx, i, 0] = -1` is not necessary.

----

# NOTE II

In fact, I think things should be fine if we add 

```
if squared_distance_profile[nn_i] == np.inf:
     continue
```

right after this line
https://github.com/TDAmeritrade/stumpy/blob/8da71ecec45e947cf448eb3dba8a75c98f5dbfe2/stumpy/scrump.py#L194


It still passes all test functions in `test_scrump`. Also, I tested it for input `T` with all `np.nan`:

```
import numpy as np
from stumpy.scrump import prescrump

T = np.random.rand(64)
m = 10

T[:] = np.nan
P, I = prescrump(T, m)

>>> np.all(P == np.inf)
True

>>> np.all(I == -1)
True
```

**Comment by seanlaw** [comment]
I am good with that

**Comment by NimaSarajpoor** [comment]
@seanlaw 

> @NimaSarajpoor What happens if the input time series contains all np.nan? If you can show that an all np.nan or np.inf time series input doesn't fail any tests then I think I'm okay with the change. I can't really remember why it was written this way except to catch weird edge cases like this.

I tested the folllowing case [before]: 

> Also, I tested it for input `T` with all `np.nan`:
> 
> ```
> import numpy as np
> from stumpy.scrump import prescrump # modified version
> 
> T = np.random.rand(64)
> m = 10
> 
> T[:] = np.nan
> P, I = prescrump(T, m)
> 
> >>> np.all(P == np.inf)
> True
> 
> >>> np.all(I == -1)
> True
> ```

Is this enough? Or, do you think we should add a test function regarding this matter in the PR #887 ?

**Comment by seanlaw** [comment]
Probably good enough
