### ISSUE TITLE
simplify if-else block in scraamp

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#751]
I was wondering if it would be reasonable to replace

https://github.com/TDAmeritrade/stumpy/blob/8da71ecec45e947cf448eb3dba8a75c98f5dbfe2/stumpy/scraamp.py#L168-L174

with this:

```
# in scraamp

for i in indices[start:stop]:
    if not T_A_subseq_isfinite[i]:  # pragma: no cover
         continue
     
    # rest of the code
```

**Comment by seanlaw** [comment]
@NimaSarajpoor Frankly, I don't have a good response to this as I don't recall why it was there in the first place except that it was likely for insurance to protect against some edge case like when an entire time series contains all `np.nan`?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
What I am trying to say here is that if `T_A_subseq_isfinite[i] == False`, then the distance profile `p_norm_profile` becomes all `np.inf`. Therefore, it does not help with updating our `P_NORM` profile (which is our matrix profile). In other words, we do not need to continue and we just need to check the next iteration (i.e. another subsequence). 

---

I now think my proposed suggestion in  [this comment](https://github.com/TDAmeritrade/stumpy/issues/750#issuecomment-1336169094) should suffice and it is readable as well. So, we can ignore this issue.

**Comment by seanlaw** [comment]
@NimaSarajpoor Shall I close this?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Sure.
