### ISSUE TITLE
Add Faster rolling_isconstant

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#766]
@NimaSarajpoor I came across a numpy "peak-to-peak" function called [np.ptp](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html) that computes the difference between the max and min. On my machine it is around 2x faster for computing the rolling_isconstant:

```
@njit(parallel=True, fastmath={"nsz", "arcp", "contract", "afn", "reassoc"})
def _rolling_isconstant(a, w):
    l = a.shape[0] - w + 1
    out = np.empty(l)
    for i in prange(l):
        out[i] = np.ptp(a[i : i + w])

    return np.where(out == 0.0, True, False)


def rolling_isconstant(a, w):
    axis = a.ndim - 1
    return np.apply_along_axis(
            lambda a_row, w: _rolling_isconstant(a_row, w), axis=axis, arr=a, w=w
        )
```

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Awesome! it is very nice that numba supports this! Thank you for this suggestion :)

![image](https://user-images.githubusercontent.com/38519522/208217375-b792b157-8a44-4357-9378-d55de27b3ce5.png)

In my PC, it is about 6x faster :)

**Comment by seanlaw** [comment]
Cool. I will upgrade it to this (and generalize it)
