### ISSUE TITLE
Inconsistency in the name of variables 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#767]
I have been reading the `gpu_stump` code and I found this...

First, we see this in function `gpu_stump`:
https://github.com/TDAmeritrade/stumpy/blob/11d24dfe98cdb2774230f7b533a8dc9533c9a5c2/stumpy/gpu_stump.py#L577-L578

So, the variables `M_T` and `Σ_T`  correspond to `T_A`.  Then, we see this in `_gpu_stump`:

https://github.com/TDAmeritrade/stumpy/blob/11d24dfe98cdb2774230f7b533a8dc9533c9a5c2/stumpy/gpu_stump.py#L343-L357

Now, if we look at the if-block, we can feel something weird is going on. On the right hand side of statements in the if-block, we see `T_A` and `μ_Q`, `σ_Q` !!! The latter two variables correspond to `T_B`. 

**side note:** I think this if-block is here to reduce the calls to `cude.to_device`  in self-join. If not, we can remove it because we already handle `ignore_trivial` in `gpu_stump` by doing: `if ignor_trivial: T_B = T_A` and things should be fine. 

The aforementioned if-block is an example that shows that having  `T_A, T_B, M_T, μ_Q` can be confusing as we do not know which relates to what. Also, such information cannot be obtained from the docstring of `_gpu_stump`.

I felt the same thing in different parts of the code. If we are using `Q` because of the word `Query`, then we can do: 
```
T, M_T, Σ_T = core.preprocess(T_A, m)
Q, μ_Q, σ_Q = core.preprocess(T_B, m)
```
(Btw, in AB-join, I think a subseq in `T_A` is actually a query and we find its closest neighbor in `T_B`)

There might be some cases in the code where we use `M_T` to denote only a slice of "M_T_A" but we need to pass the full time series `T_A` to the function. I do not know if such cases exist. If yes, then we may keep `T_A, M_T, Σ_T = core.preprocess(T_A, m)` but just enhance the docstring.

**Comment by seanlaw** [comment]
I mostly agree and can take a closer look. I've since forgotten the details but I recall something "backwards" was happening with gpu_stump due to the way that we were forced to traverse the subsequences on the GPU that was different from the CPU STOMP implementation. 

The great thing is that, as long as we don't change the unit tests, we can change the variable names however we please as long as the tests pass. Note that it is important to relate things back to the original papers where possible. However, if it no longer makes sense or if it is adding confusion then we should propose appropriate changes.

Is this something you would like to try to fix?

**Comment by seanlaw** [comment]
I wonder if it would be helpful to:

1. Revisit the documentation and come up with a consistent nomenclature of common variables
2. Identify all of the parts of the documentation that are inconsistent with the expected nomenclature in step 1
3. Discuss/debate whether the nomenclature should be adjusted/changed or if should stay the same (both would likely require changing the docs)
4. Document the nomenclature so that others can easily refer to it and use it as our single source of truth

**Comment by NimaSarajpoor** [comment]
> The great thing is that, as long as we don't change the unit tests, we can change the variable names however we please as long as the tests pass.

Yes. The good thing is that we have good unit tests that can catch bugs (hopefully).

> Is this something you would like to try to fix?

So, to make sure we are on the same page, I want to mention that the `M_T` and `Σ_T` correspond to `T_A` in the whole module `gpu_stump`. Even if you look at the kernel ` _compute_and_update_PI_kernel`, you  can see that `M_T` and `Σ_T`  correspond to `T_A`. 

So, the first thing it to fix these following lines:

> 
> https://github.com/TDAmeritrade/stumpy/blob/11d24dfe98cdb2774230f7b533a8dc9533c9a5c2/stumpy/gpu_stump.py#L343-L357
> 
> Now, if we look at the if-block, we can feel something weird is going on. On the right hand side of statements in the if-block, we see `T_A` and `μ_Q`, `σ_Q` !!! The latter two variables correspond to `T_B`.

We should change them to:
```
with cuda.gpus[device_id]: 
     device_T_A = cuda.to_device(T_A) 
     device_QT_odd = cuda.to_device(QT) 
     device_QT_even = cuda.to_device(QT) 
     device_QT_first = cuda.to_device(QT_first) 
     device_M_T = cuda.to_device(M_T) 
     device_Σ_T = cuda.to_device(Σ_T) 
     if ignore_trivial: 
         device_T_B = device_T_A 
         device_μ_Q  = device_M_T 
         device_σ_Q = device_Σ_T  
     else: 
         device_T_B = cuda.to_device(T_B) 
         device_μ_Q = cuda.to_device(μ_Q) 
         device_σ_Q = cuda.to_device(σ_Q)
```

---



> I wonder if it would be helpful to:

I think this would be a great idea !!!

**Comment by seanlaw** [comment]
> We should change them to:

If you have access to your GPU, would you mind changing it and see if the unit tests pass?

**Comment by NimaSarajpoor** [comment]
> > We should change them to:
> 
> I see. That seems simple enough. If you have access to your GPU, would you mind changing it (and check `gpu_aamp` as well) and see if the unit tests pass?

I will test it when I get access to my other PC and will let you know. (Btw, nothing is wrong with the existing code. The proposed change is just to make it consistent with the concept of `if ignore_trivial: T_B = T_A`)

> So, I think `T_A` should usually correspond to `μ_Q` and `σ_Q` while `T_B` should correspond to `M_T` and `Σ_T`. In `stump` function:

Yeah...I think `stump` is good regarding this matter! Because query is in `T_A`, and we search for query in `T_B`. So, this naming makes sense better. In `gpu_stump`, `T_A` corresponds to `M_T` and `Σ_T`. We keep this naming format in the module `gpu_stump`, so there is no error. But, to make it consistent with the module `stump`, we should replace:

> First, we see this in function `gpu_stump`:
> 
> https://github.com/TDAmeritrade/stumpy/blob/11d24dfe98cdb2774230f7b533a8dc9533c9a5c2/stumpy/gpu_stump.py#L577-L578

with:
```
 T_A, μ_Q, σ_Q = core.preprocess(T_A, m)  
 T_B, M_T, Σ_T = core.preprocess(T_B, m) 
```

**Comment by seanlaw** [comment]
Got it! I understand now. Thank you
