### ISSUE TITLE
stumpy.config.STUMPY_EXCL_ZONE_DENOM not wroking

### ISSUE THREAD

**Issue by lxs0202** [TDAmeritrade/stumpy#780]
Hi, The stumpy.config.STUMPY_EXCL_ZONE_DENOM config seems not working in version 1.11.1. I set it to different values but always having the same results from stumpy.stump function. Could someone help to check?

**Comment by seanlaw** [comment]
@lxs0202 Closing this issue for now but please feel free to post to our Github Discussions if you have further questions
