### ISSUE TITLE
Write GPU vs CPU Blog

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#79]
- [ ] Discuss lessons learned
- [ ] Provide percentage speedup (relative to naive and STOMP)
- [ ] Talk about future improvements

**Comment by seanlaw** [comment]
@datametrician Here's a sneak peek to some preliminary timing calculations of the GPU performance vs CPU performance:

https://github.com/TDAmeritrade/stumpy/issues/91

**Comment by datametrician** [comment]
This is great... looks like at n^18 GPU are 5x faster, but not sure what CPU and GPU you're using.

**Comment by seanlaw** [comment]
For CPU timing, I’m using my 2017 13-inch Macbook Pro that has 2x 3.5 GHz Intel Core i7. For GPU, I am using a single 1080Ti

**Comment by quasiben** [comment]
@seanlaw and I were discussing yesterday the data generation and distribution is counted in timing measurements 

## DGX1 

```
64 7.945619821548462
128 6.877759695053101
256 6.483005523681641
512 6.367481708526611
1024 6.332911014556885
2048 6.476325035095215
4096 6.5155768394470215
8192 6.925555944442749
16384 7.092826843261719
32768 7.245383262634277
65536 8.31165599822998
131072 9.893739938735962
262144 13.08260703086853
524288 20.567565441131592
1048576 34.97314476966858
2097152 66.49404716491699
4194304 242.02571725845337
8388608 944.0460131168365
16777216 3690.350241661072
17729800 4046.869893312454
33554432 14357.105961561203
```

## DGX2

```
128 30.983444452285767
256 27.269370794296265
512 29.24271059036255
1024 29.583590030670166
2048 32.91362690925598
4096 32.89309501647949
8192 34.264721393585205
16384 35.41696572303772
32768 35.24996304512024
65536 36.32199287414551
131072 35.280667543411255
262144 38.65528893470764
524288 40.7723867893219
1048576 44.64985013008118
2097152 61.75120687484741
4194304 140.4903802871704
8388608 488.09951305389404
16777216 1755.2647705078125
17729800 1975.7738416194916
33554432 6933.41335439682
```

**Comment by seanlaw** [comment]
@quasiben Thank you again for your willingness and enthusiasm to help with running these timing calculations on such short notice! They look really impressive and it should make for a nice story.

**Comment by seanlaw** [comment]
We ran into some challenges using Python's multiprocessing where serialization of large data files beyond 4GiB (via pickle) was causing our jobs to error out. Without adding any new package dependencies, we overcame this by replacing the serialization parts with file I/O. The new DGX1 and DGX2 results (produced by @quasiben). The updated results are shown [here](https://github.com/TDAmeritrade/stumpy#performance) and, essentially, we have very nice linear scaling as the data size increases. I think these timing calculations are informative for users as it will give them a rough estimate of how long they should expect their computations to take depending on their resources.
