### ISSUE TITLE
Add short description for Matrix Profile in README.rst

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#8]
Currently, the README does not provide a description of what a "Matrix Profile" is and, instead, only points to the user to a paper. It would be better to have a short description of the matrix profile in the README without referring to an external paper. This could be done in a section labeled "The Matrix Profile" with a description, which was what a user would expect from the anchor link in the intro.

- [ ] Add "The Matrix Profile" description section to README.rst
- [ ] Update link in the package description (first sentence) to reference/point to this section

**Comment by seanlaw** [comment]
@bdice I've added an entire intro tutorial that explains the matrix profile: https://github.com/TDAmeritrade/stumpy/blob/master/docs/Tutorial_0.ipynb

**Comment by bdice** [comment]
@seanlaw Oh, this is so awesome! The animations and everything! 💯
