### ISSUE TITLE
parameter `p` (as in `p-norm`) is missing in some cases

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#802]
1) In `floss`

It seems that the parameter `p` (as in `p-norm`) is mssing in floss. Hence, the non-normalized case is limited to two-norm only.

https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/stumpy/floss.py#L399-L410

In the `if / else` block below, we can see that the computed distance in the non-normalized case is two-norm only.
https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/stumpy/floss.py#L500-L510

-----

2) In function `_idx_to_mp` (in `core.py`):

https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/stumpy/core.py#L2374

**Comment by seanlaw** [comment]
Good catch @NimaSarajpoor! This should be an easy fix, right?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Yes, I believe so. I just wanted to pointed this out here rather than solving it in a current, exisitng PR.

**Comment by seanlaw** [comment]
Excellent! Let me know if/how I can help

**Comment by NimaSarajpoor** [comment]
Sure. Sicne this seems to be small changes, I will submit a PR to fix them first, and then resume the current one.
