### ISSUE TITLE
Adding `T_subseq_isconstant` to `core._idx_to_mp`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#803]
Currently, the function `core._idx_to_mp` calculate profile value based on the profie indices. However, this calculation, from index to matrix profile, needs to consider the constant subseqs. Hence, we need to add the parma `T_subseq_isconstant` to `core._idx_to_mp`

```
# in core.py

def _idx_to_mp(I, T, m, normalize=True, T_subseq_isconstant=None):
    """
    """
    I = I.astype(np.int64)
    T = T.copy()
    
    if T_subseq_isconstnat is None:  
        T_subseq_isconstnat = rolling_isconstant(T, m)

    T_isfinite = np.isfinite(T)
    T_subseq_isfinite = np.all(rolling_window(T_isfinite, m), axis=1)

    T[~T_isfinite] = 0.0
    T_subseqs = rolling_window(T, m)
    nn_subseqs = T_subseqs[I]
    if normalize:
        P = linalg.norm(z_norm(T_subseqs, axis=1) - z_norm(nn_subseqs, axis=1), axis=1)
        T_NNsubseq_isconstant = T_subseq_isconstnat[I] 
        both_subseq_isconstant = T_subseq_isconstnat & T_NNsubseq_isconstant
        only_one_subseq_isconstant = np.logical_xor(T_subseq_isconstnat, T_NNsubseq_isconstant)
        P[both_subseq_isconstant] = 0
        P[only_one_subseq_isconstant] = np.sqrt(m)
    else:
        P = linalg.norm(T_subseqs - nn_subseqs, axis=1)
        
    P[~T_subseq_isfinite] = np.inf
    P[I < 0] = np.inf

    return P
```

**Comment by NimaSarajpoor** [comment]
Currently, we do not take advantage of this function in floss. See below:

https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/stumpy/floss.py#L500-L513

After refactoring the above code and replacing it with the function `core._idx_to_mp`, we should be easily pass the param `T_subseq_isconstant` to the floss API.

**Comment by seanlaw** [comment]
I think:

```
if T_subseq_isconstnat is None:  
        T_subseq_isconstnat = rolling_isconstant(T, m)
```

Should get moved into the `if normalize`, right?

Also, this part looks a bit complicated:

```
        T_NNsubseq_isconstant = T_subseq_isconstnat[I] 
        both_subseq_isconstant = T_subseq_isconstnat & T_NNsubseq_isconstant
        only_one_subseq_isconstant = np.logical_xor(T_subseq_isconstnat, T_NNsubseq_isconstant)
        P[both_subseq_isconstant] = 0
        P[only_one_subseq_isconstant] = np.sqrt(m)
```

Can it be cleaned up?

**Comment by NimaSarajpoor** [comment]
> ```
> if T_subseq_isconstnat is None:  
>         T_subseq_isconstnat = rolling_isconstant(T, m)
> ```
> 
> 
>     
>   
> 
> Should get moved into the `if normalize`, right?

Right! To improve readability and save computing cost when `normalize==False`, we should put it under `if normalize`. However, this should be done before cleaning `T`. Hence, just in the beginning, we should add a new if block.

**Comment by NimaSarajpoor** [comment]
> Also, this part looks a bit complicated:
> 
> ```
>         T_NNsubseq_isconstant = T_subseq_isconstnat[I] 
>         both_subseq_isconstant = T_subseq_isconstnat & T_NNsubseq_isconstant
>         only_one_subseq_isconstant = np.logical_xor(T_subseq_isconstnat, T_NNsubseq_isconstant)
>         P[both_subseq_isconstant] = 0
>         P[only_one_subseq_isconstant] = np.sqrt(m)
> ```
> 
> Can it be cleaned up?

Another way that I can think of is to go through the concept. If we replace a constant subseq with all 0, we should be fine. Hence, one idea is to just pass it to the `core.z_norm`, which is currently as follows:
https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/stumpy/core.py#L257-L281

I think instead of the `threshold` param, we should pass something like `T_subseq_isconstant`, or wrap a function around `core.z_norm` that modify its input. Conceptually speaking, z-norm of a constant subseq is all `0`. So, I THINK if we just modify the output of `core.z_norm` and sets the constant subseq to all `0`, we should automatically get the correct result. Becuse, the distance between two constant subseq will be 0 for sure, and the distance between a constant subseq and a non-constant one is `sqrt(m)` as we discussed before.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
please kindly note that in my previous comment, I did not talk about specifc subseqs and their nearest neighbors according to matrix profile index `I`. My point is that all we need is the `T_subseq_isconstant` and then we call `core.Z_norm_new` which takes `T_subseq_isconstant` as one of its arguments. It calls `core.z_norm` and modify its output by setting the constant ones to `0`. This is like tacking the problem at its core. Mathematically speaking, this should give us the correct result at the end, similar to the one I proposed initially.

**Comment by NimaSarajpoor** [comment]
@seanlaw 

The naive version of calculating. `z_norm` is currently as follows:
 
https://github.com/TDAmeritrade/stumpy/blob/92ef4d56f4cf875638077cf595ebd8abfd4b7499/tests/naive.py#L20-L24

So, we may do this:
```
def z_norm(..., a_isconstant=None)
    if a_isconstant is none:
         # calculate it along the axis==axis

    std = np.std(a, axis, keepdims=True)
    std = np.where(std > 0, std, 1.0)
    
    out = (a - np.mean(a, axis, keepdims=True)) / std
    out = np.where(a_isconstant, out, 0)
    
    return out
    return 
``` 

What do you think?

**Comment by seanlaw** [comment]
Hmm, I don't love setting the `z_norm` to zero as I do want to keep `z_norm` as pure as possible.

> Can it be cleaned up?

Apologies. When I said this, I didn't actually have any problem with the steps that were presented. I like that it is a series of post-processing steps. I simply meant that some of the variables (e.g., `T_NNsubseq_isconstant`) looked a bit ugly or maybe one of the steps could possibly be written in a more easily digestable way. In other words, I think the code is really close and could use a little polish if possible. May not :)

**Comment by NimaSarajpoor** [comment]
> I do want to keep `z_norm` as pure as possible.

Yeah...I had to fight with this in my mind to allow myself to propose such suggesion :) You are right.... better to not touch it if possible. Its purpose should not be changed. 



> Apologies. When I said this, I didn't actually have any problem with the steps that were presented. I like that it is a series of post-processing steps. I simply meant that some of the variables (e.g., `T_NNsubseq_isconstant`) looked a bit ugly or maybe one of the steps could possibly be written in a more easily digestable way. I

Got it! I will ask about. One way is to just use the word `mask` and then add a comment to explain what that mask is. I will think about it.

**Comment by seanlaw** [comment]
I think even something like this feels slightly cleaner (debatable!!):

```
        nn_subseq_isconstant = T_subseq_isconstant[I] 
        P[T_subseq_isconstnat & nn_subseq_isconstant] = 0
        P[np.logical_xor(T_subseq_isconstnat, nn_subseq_isconstant)] = np.sqrt(m)
```

**Comment by NimaSarajpoor** [comment]
I think it is good as it does not use the ugly names and it has descriptive comment. I wanted to use `mask` as it would be easier (for me) to read it, however, I am not sure if using that intermediate variable takes any additional memory compared to what you proposed above, or if mine will look better.

I will go with your suggestion. Thank you for the input :)
