### ISSUE TITLE
minor issue in `floss`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#808]
It seems that there exists a minor issue in the `floss` module.

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/floss.py#L519-L521

If I understand correctly, the last line should be ` self._mp[inf_indices, 3] = -1 `. In fact, the last line is not necessary because `self._mp[:, 3]` is already set at `-1`, and we use this column to find `inf_indices` in line 519. So, a good fix is to just remove the last line.

**Comment by NimaSarajpoor** [comment]
**Refactoring**

In `stumpi`, we also use indices to calculate matrix profile value:

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/stumpi.py#L148-L170

And, in `core.py`, we have this function:
https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/core.py#L2374
that does the same thing.

Hence, I think there is an opportunity to do refactoring here.

**Comment by NimaSarajpoor** [comment]
As a follow up to my previous comment, the following line needs to be fixed as well:

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/floss.py#L566

I think it should have been: `self._mp[-1, 3] = -1 `

**Comment by seanlaw** [comment]
@NimaSarajpoor I don't know if I agree. It's been a long time since I've written that code and I don't remember the details but I'm guessing that there's an issue with actually allowing the right index (i.e., `self._mp[:, 3]`) to have negative values. Technically, a negative index value has no meaning (i.e., it is an invalid index). However, in `numpy`, a negative value corresponds to the last position of an array and so we can't "trust" that negative index value anymore and we need to replace it with something else that is not `-1`.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
> so we can't "trust" that negative index value anymore

Right! I missed that. Now that you mentioned it, I checked out the `core._idx_to_mp` code again:

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/core.py#L2417-L2432

Note that the same thing is happening here. However, we have a postprocessing at the end that will take care of it. Having said that, I think I can get your point. If `I[idx]==-1`, then it is safer to replace it with `I[idx]=idx`. Because, at least, we know that the distance that is being calculated is `0`, which makes sense. 


**Warning:**
 If we decide to change our mindset, and manipulate `I` (self._mp[:, 3] in our case), then we need to remember that we did such change in our code. As shown below, I think `self.I_` is wrong and needs to be corrected:

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/floss.py#L621-L626


We may do:
```
self.I_[self.P_ == np.inf] = -1
```

**Comment by seanlaw** [comment]
> It's been a long time since I've written that code and I don't remember the details but I'm guessing that there's an issue with actually allowing the right index (i.e., self._mp[:, 3]) to have negative values. Technically, a negative index value has no meaning (i.e., it is an invalid index). However, in numpy, a negative value corresponds to the last position of an array and so we can't "trust" that negative index value anymore and we need to replace it with something else that is not -1.

I do think that we should probably add a note explaining this subtle thing in the code. What do you think?

**Comment by NimaSarajpoor** [comment]
> we should never use `self.P_` within the class and, instead, use their raw equivalent

Thanks for the input! There is always something to learn :) 



> I do think that we should probably add a note explaining this subtle thing in the code. What do you think?

I think that is a good idea. I will add a comment.

**Comment by seanlaw** [comment]
Maybe `we should never use self.P_ within the class` is too strong but, in general, I tend to treat methods/attributes that are decorated with the `@property` as being "public" facing and gives people who created an instance of the class the opportunity to access some internal information. In other words, information that is "read-only". Sometimes, the decorated method/attribute itself may require some processing before it is exposed and so, internally, we don't want to rely on that processing. Of course, if the processing is necessary for both internally and externally then we should throw that into a new function and then we can call that processing function everywhere. I've just been burned before when relying on that external facing attribute as it may be very limiting since it is public facing and often cannot be changed.

**Comment by NimaSarajpoor** [comment]
> I tend to treat methods/attributes that are decorated with the @property as being "public" facing and gives people who created an instance of the class the opportunity to access some internal information. In other words, information that is "read-only".

> I've just been burned before when relying on that external facing attribute as it may be very limiting since it is public facing and often cannot be changed.


Yeah...I can see your point. Since we may decide to change something later (internally), we prefer to keep the public attribute untouched. I hope I have understood you correctly :) Thank you for the elaboration.

**Comment by NimaSarajpoor** [comment]
It seems that we have already addressed the two items that were discussed before in this issue:

> Should we do something like:
> 
> ```
>     @property 
>     def I_(self): 
>         """ 
>         Get the updated (right) matrix profile indices 
>         """ 
>         I = self._mp[:, 3].astype(np.int64).copy()
>         I[self._mp[:, 0] == np.inf] = -1
>         return I
> ```
> 
> IMHO, we should never use `self.P_` within the class and, instead, use their raw equivalent

please see: https://github.com/TDAmeritrade/stumpy/blob/286cb178d201ea4378d8dde70f6d24c1b8caa5a2/stumpy/floss.py#L716-L741



> > It's been a long time since I've written that code and I don't remember the details but I'm guessing that there's an issue with actually allowing the right index (i.e., self._mp[:, 3]) to have negative values. Technically, a negative index value has no meaning (i.e., it is an invalid index). However, in numpy, a negative value corresponds to the last position of an array and so we can't "trust" that negative index value anymore and we need to replace it with something else that is not -1.
> 
> I do think that we should probably add a note explaining this subtle thing in the code.

please see: https://github.com/TDAmeritrade/stumpy/blob/286cb178d201ea4378d8dde70f6d24c1b8caa5a2/stumpy/floss.py#L579-L588

What do you think @seanlaw ?

**Comment by seanlaw** [comment]
> What do you think @seanlaw ?

Looks good to me. Shall I merge it @NimaSarajpoor ?

**Comment by NimaSarajpoor** [comment]
[The provided links in my previous comment show the existing code]

Please feel free to close this issue.
