### ISSUE TITLE
An opportunity for Refactoring

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#809]
In floss, we use matrix profile indices to calculate matrix profile values:
https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/floss.py#L493-L521

Also: In `stumpi`, we use indices to calculate matrix profile value:

https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/stumpi.py#L148-L170

And, in `core.py`, we have this function:
https://github.com/TDAmeritrade/stumpy/blob/b6aba2b3f9b7d5cf8256f633c5ae0b0d2ada1d2a/stumpy/core.py#L2374
that does the same thing.

Hence, I think there is an opportunity to do refactoring here.

**Comment by seanlaw** [comment]
That might be useful in `floss`. 

However, I don't necessarily agree for `stumpi` as the current implementation may be faster since it skips some steps by not explicitly computing the z-norm for each subsequence first before computing the final distance. For streaming data, this subtle speed up may be important

**Comment by NimaSarajpoor** [comment]
> However, I don't necessarily agree for `stumpi` as the current implementation may be faster since it skips some steps by not explicitly computing the z-norm for each subsequence first before computing the final distance.

In fact, I was thinking of using the faster method in `_idx_to_mp`, and then just use that function for refactoring. I haven't looked at the details yet.

**Comment by seanlaw** [comment]
> In fact, I was thinking of using the faster method in _idx_to_mp, and then just use that function for refactoring. I haven't looked at the details yet.

That seems messy as the "faster" method requires pre-computing the means and stddevs and then passing them into `_idx_to_mp`. Note that either you pass ALL of the additional means/stddevs or you pass none of them (i.e., you can't pass in some and not others). 

The more I think about it, the more I don't think it is worth refactoring to add support for means/stddevs.

**Comment by NimaSarajpoor** [comment]
> as the "faster" method requires pre-computing the means and stddevs and then passing them into

Correct! That can get messy!!


> The more I think about it, the more I don't think it is worth refactoring to add support for means/stddevs.

I understand. Okay...so let's leave it as is then.

**Comment by seanlaw** [comment]
@NimaSarajpoor Shall I close this as well?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Yes. I think it is better to close it for now. I think we can re-open it later if needed.
