### ISSUE TITLE
Discrepency between performant and naive computation in `test_stumpi`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#814]
It seems that there is a slight discrepency between the performant version of stumpi and its naive computation in `test_stumpi`. This issue is exposed after adding the  `T_subseq_isconstant_func` parameter.

In `stumpy/stumpi.py`, we can see the following line of code:
https://github.com/TDAmeritrade/stumpy/blob/a4bb1e1836e76562974d6b611d1dd71f36eb3202/stumpy/stumpi.py#L139

which computes matrix profile using the performant version `stump`. Note that the approach of performant stump is the same as `naive.stump(T, row_wise=False)`. Also, note that when we call the method `update()`, we update matrix profile in a way that is similar to `naive.stump(row_wise=True)` Because, each time that we update, we calculate the distance profile, and update the matrix profile value/indices accordingly. Hence, we have a mixure of  `row_wise=False` and `row_wise=True` here. However, in `test_stumpi`, we just do `naive.stump(T_updated, row_wise=True)`, as shown below:

https://github.com/TDAmeritrade/stumpy/blob/a4bb1e1836e76562974d6b611d1dd71f36eb3202/tests/test_stumpi.py#L36

Note that `stream._T` is the updated version of `T`. In other words, we apply function `naive.stump(row_wise=True)` on full data whereas in the performant version, we first compute `mp` for the initial chunk via `row_wise==False` approach and then update it in a manner that is similar to `row_wise==True`.

---

To make sure this is the reason behind getting failure in my local test, I am going to add param `mp=None` to stumpi, and then compute`mp` using `naive.stump(T, row_wise=True)` and pass it to the `stumpi`. I think this should resolve the issue and `    npt.assert_almost_equal(ref_left_I, comp_left_I)` will pass.

**Comment by NimaSarajpoor** [comment]
[Update]
Adding the param `mp` to `stumpi`  and passing `naive.stump(T, m, row_wise=True)` as `mp` to the function `stumpi` fixed the issue. So, as I mentioned in my previous comment, we should avoid comparing the `ref_I` and `comp_I` as the way the datapoints are traversed are different. I think we should avoid comparing `ref_I` and `comp_I` in all test functions in `test_stumpi.py`. Logically speaking, these two arrays can be compared only when the datapoints are being travesed in the same manner in both performant and naive version in  a test funcion.

**Comment by seanlaw** [comment]
> we have a mixure of row_wise=False and row_wise=True here. 

I see. That is tricky and makes sense.

> Adding the param mp to stumpi and passing naive.stump(T, m, row_wise=True) as mp to the function stumpi fixed the issue.

Great! When you say that you added `mp` to `stumpi`, isn't this related to issue #621 to some extent? If so, we should add `mp` and as a PR for that issue instead.

> So, as I mentioned in my previous comment, we should avoid comparing the ref_I and comp_I as the way the datapoints are traversed are different. I think we should avoid comparing ref_I and comp_I in all test functions in test_stumpi.py. Logically speaking, these two arrays can be compared only when the datapoints are being travesed in the same manner in both performant and naive version in a test funcion.

I am hesitant to stop comparing `ref_I` and `comp_I` for all test functions in `test_stumpi.py` given that this is the first time we've seen the tests fail due to this mixture of `row_wise=False` and `row_wise=True`. Instead, I would do two things:

1. Do **not** compare `ref_I` and `comp_I` when you are testing `T_subseq_isconstant` with a custom input array that actually contains legitimate constant subsequences. However, for all other existing input arrays (which are likely random and do not contain constant subsequences), continue comparing `ref_I` and `comp_I` as they have not had any issues and should always pass (as they have been). Presumably, adding `T_subseq_isconstant` has not/should not affect these types of input arrays, correct?
2. Leave this issue open and continue monitoring the situation. If it persists for the random array inputs then we can remove the comparison of `ref_I` and `comp_I` at a later time.

Again, while adding `mp` fixes the issue, I would **not** submit a PR (for adding `mp`) to this issue. I would submit a PR for #621 instead and then fix the corresponding unit test(s) in PR #815 (pertaining to comparing `ref_I` and `comp_I`). I would keep this issue focused around whether or not we should turn off comparing `ref_I` and `comp_I` in the future if the problem persists.

**Comment by NimaSarajpoor** [comment]
> To be clear, the matrix profile DISTANCES should still be the same (beyond precision), correct? It is only a problem with comparing `ref_I` and `comp_I`, right?

Correct. The problem is with the matrix profile indices and I think it is not related to the precision as the issue is exposed when we consider several constant subseqs in the data which results in them having distance `0` between each other (so, we have no loss of precision here)

I think the issue is only with matrix profile indices: `ref_I` and `comp_I`, as well as `ref_left_I` and `comp_left_I`. I will try again to make sure the aforemntioned error occurs for both case (bidirectional and left)

> When you say that you added `mp` to `stumpi`, isn't this related to issue #621 to some extent?

Indeed, this is related to #621.

> Again, while adding mp fixes the issue, I would not submit a PR (for adding mp) to this issue. I would submit a PR for https://github.com/TDAmeritrade/stumpy/issues/621 instead and then fix the corresponding unit test(s) in PR https://github.com/TDAmeritrade/stumpy/pull/815 (pertaining to comparing ref_I and comp_I).

That totally makes sense. I can submit a PR to add `mp` to `stumpi`. Then, after merging that PR as well as #810, I can continue my work in #815.

> Presumably, adding T_subseq_isconstant has not/should not affect these types of input arrays, correct?

Correct. Adding the param `T_subseq_isconstant=None` (default) should not affect the existing test functions as the input is random and the chance of having two identical value of distance between a subsequence and two of its neighbors should be really low. So, does not matter how we traverse the distance matrix as we should eventually end up with the unique global minimum. 

> Leave this issue open and continue monitoring the situation. If it persists for the random array inputs then we can remove the comparison of ref_I and comp_I at a later time.

Alternatve solution: we can pass `naive.stump(row_wise=True)` whenever we want to compare matrix profile indices and distances both. In a different test function, we can pass `None` (which means that `mp` will be computed internally in a `row_wise==False` manner) and then we can just compare the matrix profile values only in that case.

**Comment by seanlaw** [comment]
> Alternatve solution: we can pass naive.stump(row_wise=True) whenever we want to compare matrix profile indices and distances both. In a different test function, we can pass None (which means that mp will be computed internally in a row_wise==False manner) and then we can just compare the matrix profile values only in that case.

Sounds good if it works

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I was wondering if we should close this issue. Please see the following notes:

(1) see [stumpy/stumpi.py](https://github.com/TDAmeritrade/stumpy/blob/main/stumpy/stumpi.py): It supports the param `mp` which, in the default mode, computes the matrix profile by calling `stumpy.stump`. This means matrix profile is computed in a digonal manner. We have the same approach in [tests/naive.py: stumpi](https://github.com/TDAmeritrade/stumpy/blob/d609a07675779b6448b0ac254937a8f6737fcf81/tests/naive.py#L1001-L1010)

(2) As discussed in this issue, I have made no change in the test functions where matrix profile indices were compared between performant and naive versions even if they traverse matrix profile in different manner. The rationale is that the chance of having two global minimum in a distance profile of a subsequence is very low when the the time series are random and there are no "constant" subsequences.

(3) In the test functions that were added regarding "isconstant" param: 

* If traversing the distance matrix between ref and comp is different, the assertion of matrix profile indices are commented out (e.g. see: https://github.com/TDAmeritrade/stumpy/blob/d609a07675779b6448b0ac254937a8f6737fcf81/tests/test_stumpi.py#L1126-L1188).

* If one wants to compare the matrix profile indices, then distance matrix should be traversed the same in both naive and peformant. See: https://github.com/TDAmeritrade/stumpy/blob/d609a07675779b6448b0ac254937a8f6737fcf81/tests/test_stumpi.py#L1190-L1243 
If needed, we may  move the part above and put it in its own test function.

**Comment by seanlaw** [comment]
I am okay with closing it. At least we've had the discussion and talked through it
