### ISSUE TITLE
Update documentation regarding Euclidian distance instead of Pearson's correlation

### ISSUE THREAD

**Issue by lucaspg96** [TDAmeritrade/stumpy#822]
According to the [docs](https://stumpy.readthedocs.io/en/latest/api.html), the `stumpy.stump` method:
```
Compute the z-normalized matrix profile
    
    This is a convenience wrapper around the Numba JIT-compiled parallelized
    `_stump` function which computes the matrix profile according to STOMPopt with
    Pearson correlations.
```

However, computing the matrix profile over a time series (`from scipy.misc import electrocardiogram`) is returning only positive values and they are bigger than 1. I boxplotted them:

![image](https://user-images.githubusercontent.com/20579647/229115177-233bd0a2-c215-4357-abc1-2ae35dac0d85.png)

**Comment by seanlaw** [comment]
@lucaspg96 Thank you for your question. I can understand the confusion. However, the emphasis of "Pearson correlation" is relating to the "STOMPopt" algorithm, which actually first computes the Pearson correlation before ultimately converting this to a z-normalized Euclidean distance. As opposed to the "STOMP" algorithm, which computes the z-normalized Euclidean distance directly without computing the Pearson correlation first. 

Fundamentally, a "matrix profile" contains some sort of distance but it depends on the value of the `normalize` and/or `p` parameters (i.e., it isn't always z-normalized Euclidean distance).

**Comment by seanlaw** [comment]
Perhaps it would be helpful to say:

> Compute the matrix profile (default z-normalized Euclidean distance)

**Comment by seanlaw** [comment]
@lucaspg96 Are you able to provide some feedback?
