### ISSUE TITLE
distance between Q and itself is not zero

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#828]
```
seed = 13
np.random.seed(seed)
T = np.random.uniform(-1000, 1000, [64]).astype(np.float64)

Q = T[44 : 48]
```

The distance between a sequence and itself should be zero. However, this is not true for the `Q` shown above if we use  pearson approach. Let's see:

```
QT = np.dot(Q, Q)
μ_Q = np.mean(Q)
M_T = np.mean(Q)

σ_Q = np.std(Q)
Σ_T = np.std(Q)

denom = m * σ_Q * Σ_T
ρ = (QT - m * μ_Q * M_T) / denom 
D_squared = np.abs(2 * m * (1.0 - ρ))
D = np.sqrt(D_squared)
```
And, we have:
```
>>> ρ
0.9999999999999999

>>> D_squared
8.881784197001252e-16

>>> D
2.9802322387695312e-08
```

Note that `D` should have been 0. Althought `npt.assert_almost_equal(d, 0)` does not raise an error, `D` is greater than 0. This can become an issue in testing snippet module (Explained below)

---

The performant snippet uses performant `_mpdist_vect`, which computes mpdist profile using `_mass`. The naive snippet uses naive ` mpdist_vect` which computes distances using naive `stump`.  so, the distance between `Q` and itself is  `2.9802322387695312e-08` in naive approach. In performant approach, however, it is 0. This small difference can result in a considerable change in the boolean array `mask`:

https://github.com/TDAmeritrade/stumpy/blob/2d003ff2c2e0212eba32b22211a743306bafa992/stumpy/snippets.py#L285

which, in turn, results in a considerable change in `np.sum(mask)` and, consequently `snippet_fractions`.

https://github.com/TDAmeritrade/stumpy/blob/2d003ff2c2e0212eba32b22211a743306bafa992/stumpy/snippets.py#L286

Note that `np.sum(mask)` is a an interger. So, we are not talking about approx. `1e-8` loss of precision here! That small loss of precision in `D` can result in a loss of precision of at least `1` in `np.sum(mask)`. 

If we look at the errors in https://github.com/TDAmeritrade/stumpy/actions/runs/4636087916/jobs/8203665926?pr=823 we can see that all errors are related to `snippets_fractions`, and the errors are not negligible due to the reason explained earlier.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
> I should've been more clear and asked, "where is the difference in precision coming from?". Because, at the end of the day, we are going to assert that two values are the same but they are not. And so why are the two different ways of computing some value diverging?

From my point of view:  At first, it is just a very small loss of precision in computing the distance between a sequence and itself. So, that `some value` is the distance between a seq and itself. Then, this small loss of precision affects the boolean array `mask`, which is another `some value`. The loss of precision is not small anymore. Then, it changes the `snippets_fraction`, which is `some value` that is being asserted.

**Comment by NimaSarajpoor** [comment]
Note: 
While the distance-to-self-being-not-zero issue (mentioned in the first post) still exists, its impact (i.e. the error in snippet) is resolved by passing the param `query_idx` to the function `_mpdist_vect` when it is called in the module snippet. (see #823)

**Comment by seanlaw** [comment]
Do you have a proposal on what we can/should do to address the original post? Or do you think this issue can be closed?

**Comment by NimaSarajpoor** [comment]
Unfortunately not at this moment. One ill(?) solution is to use threshold. But I prefer to not use threshold.

**Comment by NimaSarajpoor** [comment]
As a follow up to my previous comment, I would like to mention that the original post is the very first root cause of the bug. The added param query-idx does not resolve that root cause but it resolves its impact in core.mass which results in resolving the bug.

So, I think we should be okay with closing it. What do you think?
