### ISSUE TITLE
Enhance `docstring.py` 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#839]
Currently, `dosctring.py` checks whether an argument in a function (or  class) has  a description in its docsting or not.

https://github.com/TDAmeritrade/stumpy/blob/89db087914084a5e9e5915567c5f1a3bc9ec895d/docstring.py#L25-L30

I was wondering if we could add function to check the opposite, i.e. to see if there is a description for an argument that is not in the signature of a function. This is not a big deal as adding such function to `docstring.py` may not help users that much. It can help with keeping the docstrings clean.

---

Example:
The function `_prescrump` does not have the argument `idx_ranges` but we can see its description in its docstring (see below).

https://github.com/TDAmeritrade/stumpy/blob/89db087914084a5e9e5915567c5f1a3bc9ec895d/stumpy/scrump.py#L367-L420

**Comment by seanlaw** [comment]
Is the idea to use this to inform us to, maybe, remove a docstring parameter if that parameter is not actually listed in the signature?

**Comment by seanlaw** [comment]
So, I haven't thought about this in great detail but it might be as simple as reversing the order in:

```
def check_args(doc_args, sig_args, file_name, func_name, class_name=None, reverse=False):
    """
    Compare docstring arguments and signature arguments
    """
    if reverse:
        diff_args = docstring_args.difference(signature_args)
        adjective = "extra"
    else:
        diff_args = signature_args.difference(docstring_args)
        adjective = "missing"        

    if len(diff_args) > 0:
        msg = "Found one or more arguments/parameters with "
        msg += f"{adjective} docstring in \n"
        msg += f"file: {file_name}\n"
        if class_name is not None:
            msg += f"class: {class_name}\n"
        msg += f"function/method: {func_name}\n"
        msg += f"parameter(s): {diff_args}\n"
        raise RuntimeError(msg)
```

**Comment by NimaSarajpoor** [comment]
> Is the idea to use this to inform us to, maybe, remove a docstring parameter if that parameter is not actually listed in the signature?

Yes...this can be helpful when we change the signatures of a private API and we forget to update docstring accoridngly. 

> but it might be as simple as reversing the order of the check by doing something like:

I was thinking of using the set method `symmetric_difference` but I now think what you proposed is better as it seperates the two cases, one check for the existence of a description and the other check for the existence of argument in the signature.

> if reverse:
> diff_args = docstring_args.difference(signature_args)
> adjective = "extra/unnecessary"

I think we are almost there. we just need to search for `r"(R|r)eturn(s\b | s: | \b| :\b)"`  or Attribute/Method followed by some dashes in the next line, and get `docstring_args` from that part only. Otherwise, the `docstring_args` contain the outputs of the function as well.

(The reason that I mentioned the `dashes` is to make sure we find the correct position in the docstring. I tried to just search for return and I realized the term `return` might appear more than once in some docstrings.)

**Comment by seanlaw** [comment]
I get your point now. Perhaps we can do:

```
def get_docstring_args(fd):
    """
    Extract docstring parameters from function definition
    """
    docstring = ast.get_docstring(fd)
    params_section = re.findall(r"(?<=Parameters)(.*)(?=Returns)", docstring, re.DOTALL)[0]
    args = re.findall(r"(\w+)\s+\:", params_section)
    args = set([a for a in args])
    return args
```

**Comment by NimaSarajpoor** [comment]
I really like your diverse skills :) I will try it out when I get some time, and see how it works.

**Comment by seanlaw** [comment]
> I really like your diverse skills :) I will try it out when I get some time, and see how it works.

More like "diverse Googling skills" :D  

I will say that I, originally, when I wrote these functions, I was too lazy to figure out how to isolate the match to that section. This is definitely the better way to go!

**Comment by NimaSarajpoor** [comment]
> > I really like your diverse skills :) I will try it out when I get some time, and see how it works.
> 
> More like "diverse Googling skills" :D


>  I was too lazy to figure out how to isolate the match to that section. 

It is important to just take the first step!
