### ISSUE TITLE
wrong post-processing on distance matrix in naive mass_PI

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#842]
In `naive.py::mass_PI`, we can see the following code:

https://github.com/TDAmeritrade/stumpy/blob/8cc59b2bc5ec7222002ae68234303b09d007bc4a/tests/naive.py#L147-L160

However, the last line `D[np.isnan(D)] = np.inf ` cannot be always effective as the value might be already set to a finite value because of the elif in line 151. To sovle this, we have two solutions:

(1) `D[np.isnan(D)] = np.inf ` right after computing D in line 147, and then add a if-check before applying isconstant-related post-processing as follows:

```
for i in range(len(T) - m + 1):
     if np.isfinite(D[i]):
         if Q_subseq_isconstant and T_subseq_isconstant[i]: 
              ...
         elif .... 
```  

Or alternatively: 

(2) we can compute D_isfinite = np.isfinite(D) right after computing `D`. Then, at the end, we can do:
```
D[~D_isfinite] = np.inf
```

**Comment by NimaSarajpoor** [comment]
I think `naive.mass_PI` is only used in `test_stamp`, and `stamp` is not supported anymore. So, this issue itself is a  low priority but it is good to be careful in post-processing `D` so that we do not get into that trap.

**Comment by seanlaw** [comment]
I think the if/else solution in 1) is fine

**Comment by seanlaw** [comment]
I've been thinking if we might want to move the if/else logic into a separate helper function since we are starting to repeat that logic in multiple places:

```
def _get_isconstant_distance(D, m, T_A_subseq_isconstant, T_B_subseq_isconstant):
    """
    Assume that all inputs are scaler/singular values (i.e., not an array)
    """
    if T_A_subseq_isconstant and T_B_subseq_isconstant: 
         return 0.0 
     elif T_A_subseq_isconstant or T_B_subseq_isconstant: 
         return np.sqrt(m) 
     else:
         return D
```

**Comment by NimaSarajpoor** [comment]
> I've been thinking if we might want to move the if/else logic into a separate helper function 

I think that might be helpful. I am assuming the check for `D==np.inf / np.nan` is happing as post-processing outside of this function. I am not sure but I think I saw this logical mostly in naive and not in performant functions. I need to check the functions again to make sure of it.

**Comment by seanlaw** [comment]
I guess this is similar but not the same:

https://github.com/TDAmeritrade/stumpy/blob/43a1cea710c004ed08fb1de0e712e3335917f61d/stumpy/stump.py#L202-L210

I actually thought that it was in more places but maybe I'm wrong and it isn't necessary

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Correct. They are similar. However, I cannot find a way to generalize `_get_isconstant_distance` so that it can work with pearson case.

> I actually thought that it was in more places

I know I saw it several times in naive.py as I was addding "isconstant" support to different modules. `mass_PI` was one example. There are some other examples from `naive.py`:


https://github.com/TDAmeritrade/stumpy/blob/43a1cea710c004ed08fb1de0e712e3335917f61d/tests/naive.py#L255-L264

https://github.com/TDAmeritrade/stumpy/blob/43a1cea710c004ed08fb1de0e712e3335917f61d/tests/naive.py#L1717-L1727

https://github.com/TDAmeritrade/stumpy/blob/43a1cea710c004ed08fb1de0e712e3335917f61d/tests/naive.py#L1816-L1828

I guess the reason that we have this mostly in naive is because this "isconstant" support is for normalized version which usually works with pearson rather than the distance, and mostly we pass the isconstant value all the way to `mass` or some other functions that use pearson. 

---

The case you showed is also similar to function `_calculate_squared_distance`, where we can see the following code:
 https://github.com/TDAmeritrade/stumpy/blob/43a1cea710c004ed08fb1de0e712e3335917f61d/stumpy/core.py#L987-L1002

**Comment by seanlaw** [comment]
Okay, please ignore my comment 😊
