### ISSUE TITLE
numba JIT-compiled func `core._compute_multi_PI` is not parallel?

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#868]
The funciton `core._compute_multi_PI` seems to be parallel according to its decorator:

https://github.com/TDAmeritrade/stumpy/blob/76cb9806dec2d32f80ff20a5a3c484c34b7a54bf/stumpy/core.py#L3955-L3960

However, it uses `range` instead of `prange`:
https://github.com/TDAmeritrade/stumpy/blob/76cb9806dec2d32f80ff20a5a3c484c34b7a54bf/stumpy/core.py#L3997-L3998

**Comment by seanlaw** [comment]
I'm guessing that, at some point, it was using `prange` but we found that it was inefficient and we moved `prange` to the function that called `compute_multi_PI`. What happens when you remove `parallel=True`? Does it affect the performance? If not, it can be removed.
