### ISSUE TITLE
conflict in the logic of function `core._idx_to_mp` 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#873]
In function `core._idx_mp`, we can see the following if block:

https://github.com/TDAmeritrade/stumpy/blob/e91d813f553f14a7207c310ccaef1887fea02ab5/stumpy/core.py#L2801-L2807

where `check_neg` is one of the argument of the function, defaulted to `True`. Hence, it seems that we are expecting user to provide the matrix profile index `I` that has no negative value `-1`. However, later in the code, we see this line:

https://github.com/TDAmeritrade/stumpy/blob/e91d813f553f14a7207c310ccaef1887fea02ab5/stumpy/core.py#L2830

whose purpose is to post-process the matrix profile values. So, if user is expected to provide `I` containing non-negative values only, then the line shown above cannot be effective. So, I think it is better to ask user to provide non-modified `I` and we take care of it inside the function:

```
I_isNegative = I < 0

IDX = np.flatnonzero(I_isNegative)
I[IDX] = IDX
# At this point, `I` has non-negative value.

# some code

# post-processing:
P[I_isNegative] = np.inf
```

**Comment by seanlaw** [comment]
> So, if user is expected to provide I containing non-negative values only, then the line shown above cannot be effective.

Note that the `check_neg` only produces a warning to remind the user that negative indices are bad and, in this case, will always be set to `np.inf`. The goal of `check_neg=False` would simply be to turn off this annoying warning (but all negative indices will still cause the distance to be set to `np.inf`. So, negative indices are NEVER allowed.

**Comment by NimaSarajpoor** [comment]
Corretct! I got confused! It makes sense. Thank you for the explanation!
