### ISSUE TITLE
Error in minimum version testing (caused by python 3.7 in macOS)

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#874]
**Python 3.7 (to be more precise:  3.7.17) issue in macOS**

See: https://github.com/TDAmeritrade/stumpy/actions/runs/5285945141/jobs/9564904199

Related: 
* https://github.com/actions/setup-python/issues/682
* https://github.com/web-platform-tests/wpt/issues/40525

**Comment by seanlaw** [comment]
@NimaSarajpoor Thanks for reporting it. It looks like an issue unrelated to STUMPY that will require others to fix the base Python image. Let's wait a couple of days to see if it resolves itself

**Comment by seanlaw** [comment]
I believe this is resolved now
