### ISSUE TITLE
Revise the description of `Q_subseq_isconstant`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#876]
In the 1D case (outside of `mstump`), it seems inaccurate to say "that indicates whether a subsequence in Q is constant" for `Q_subseq_isconstant` since `Q` is the one and only subsequence (i.e., there is no other subsequence)

_Originally posted by @seanlaw in https://github.com/TDAmeritrade/stumpy/pull/871#discussion_r1225774120_
            

we should go through the modules and revise the description of `Q_subseq_isconstant` if appropriate.

For instace, the current description of `Q_subseq_isconstant` in `core.mass` is as follows:
```
A boolean array that indicates whether a subsequence in `Q` is constant (True). Alternatively, ...
```

This should be changed to "... whether THE subsequence ~in~ `Q` is ...."

**Comment by seanlaw** [comment]
Yes! That sounds more accurate
