### ISSUE TITLE
parameter is missing in the signature of function in the stumpy document 

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#879]
Please see this:

https://stumpy.readthedocs.io/en/latest/api.html#stumpy.gpu_stump

The parameter `k` is in the docstring but not in the signature of the function.

**Comment by seanlaw** [comment]
For any function that is GPU related, the signature must be updated manually in `docs/api.rst`

I wonder if there is a way to automate this?

**Comment by seanlaw** [comment]
@NimaSarajpoor I updated the docstrings and also preemptively fixed the other two GPU functions as well in #880
