### ISSUE TITLE
Add Parallel-GPU Support

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#88]
According to this [Numba unit test](https://github.com/numba/numba/blob/master/numba/cuda/tests/cudapy/test_multigpu.py) we can use multiple GPUs on the same server by using a context manager. However, it isn't clear if this is sequential execution on each GPU or concurrent.

**Comment by seanlaw** [comment]
This [Numba mailing list response](https://groups.google.com/a/continuum.io/forum/#!searchin/numba-users/multiple$20gpus%7Csort:date/numba-users/730ALCK9eks/0hIvF2QRl3QJ) hints at the fact that the context manager returns immediately (while the kernel is executed and ran in the background) but it isn't clear how one waits for the results when two kernels are executing on different GPUs.

**Comment by seanlaw** [comment]
According to the Numba Gitter channel, Stuart Archibald said: 

> that context manager is definitely suitable for pushing instructions to the declared GPU. Would interleaving the work with sync's help? Or perhaps run a thread for each GPU? The interleave (not tested, just guessing) might look like:

```
with cuda.gpu[0]:
  <launch kernel>
with cuda.gpu[1]:
  <launch kernel>
with cuda.gpu[0]:
  cuda.synchronize()
with cuda.gpu[1]:
  cuda.synchronize()
```

**Comment by seanlaw** [comment]
I've began to test this out and the added code complexity in managing what data each GPU sees is too much work

**Comment by seanlaw** [comment]
Perhaps, this problem can be simplified by treating it as multiple AB-joins and then concatenating the results.

**Comment by seanlaw** [comment]
Tried again and it is still too complex to implement and maintain. Closing.

**Comment by seanlaw** [comment]
This is an example of parallel GPU code:

```
#!/usr/bin/env python

from numba import cuda
import numpy as np
import math

@cuda.jit("(f8[:], i8, i8, i8)")
def some_kernel(x, start_idx, range_stop, value):
    range_start = cuda.grid(1)
    stride = cuda.gridsize(1)

    for i in range(range_start, range_stop, stride):
        x[start_idx + i] = x[start_idx + i] + 1 + value

if __name__ == '__main__':
    n_devices = len(cuda.gpus)
    device_ids = range(n_devices)

    x = np.zeros(1000000000)
    device_x = [None] * n_devices
    step = 1 + x.shape[0] // n_devices

    threads_per_block = 512
    blocks_per_grid = math.ceil(step / threads_per_block)

    for device_id in device_ids:
        with cuda.gpus[device_id]:
            start_idx = device_id * step
            range_stop = min(x.shape[0] - start_idx, step)
            device_x[device_id] = cuda.to_device(x)
            some_kernel[blocks_per_grid, threads_per_block](device_x[device_id], start_idx, range_stop, device_id)
            print(f"Device {device_id}: Execute")

    #for device_id in device_ids:
    #    with cuda.gpus[device_id]:
    #        cuda.synchronize()
    #        print("Device {device_id}: Sync")

    for device_id in device_ids:
        print(device_x[device_id].copy_to_host())
```

**Comment by seanlaw** [comment]
@datametrician FYI, I managed to figure out how to get the multi-GPU (on a single server) working via Python's Multiprocessing. I'm currently performing the the timing calculations but, beyond the initial overhead of spawning a new CPU process, the GPU speed up is essentially linear (I only have 2 GPUs on a single server). I'll let you know once the final timings are posted and I'll try to work on that blog post when I've had a moment to breath :)

**Comment by datametrician** [comment]
We can also get you time on a DGX-1 or P3DN (AWS) some other multi-GPU system if needed.  Do you use CUDA IPC for intranode GPU to GPU communication? If so NVLink should work just fine.

**Comment by seanlaw** [comment]
@datametrician Actually, it is an embarrassingly parallel calculation where there is no communication between the GPUs. Although, one essentially needs to spawn a new subprocess (via multiprocessing) for each GPU that is used. 

I think getting access to a beefier machine as you mentioned above would be interesting or maybe I could work with somebody on your side (maybe @quasiben) and hand over the simple timing code to him. There's no rush and will have to wait until after the holiday break!

**Comment by datametrician** [comment]
Sounds good. Sending the code to @quasiben is absolutely fine.

**Comment by seanlaw** [comment]
@quasiben posted some DGX1 and DGX2 timing results in #79
