### ISSUE TITLE
incorrect number of iterations in `snippets._get_all_mpdist_profiles`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#890]
# Issue
In the function `_get_all_mpdist_profiless`, the time series `T` is extended so that to have a length that is a multiples of `m`. 

https://github.com/TDAmeritrade/stumpy/blob/1ddb95036dc4ce1d3179b3bb6cb9fb80c4be529a/stumpy/snippets.py#L103-L108

Note that the length of the original `T` does not change IF `len(T) % m == 0`. In such case, it seems that the following for-loop misses the last non-overlapping window of length `m`

https://github.com/TDAmeritrade/stumpy/blob/1ddb95036dc4ce1d3179b3bb6cb9fb80c4be529a/stumpy/snippets.py#L113-L123

# Solution
Before the if check `if T.shape[0] % m != 0:`, we may add: `n_windows = T.shape[0] // m` and then we do for-loop using `range(n_windows)`

**Comment by seanlaw** [comment]
@NimaSarajpoor In both cases (with and without padding), wouldn't it be sufficient to do:

```
for i in range(n_padded // m): 
```

So we omit the `- 1`

**Comment by NimaSarajpoor** [comment]
First, I should mention that my aim was to fix the shape of distance matrix `D` as well. `D.shape[0]` should be `n_windows`. 


> wouldn't it be sufficient to do:

I don't think it would since I am inclined to believe that the snippet needs to have full-size `m`. Therefore, if `len(T) % m != 0`, then the `T[-r: ]` (where `r = len(T) % m`) should not be considered as snippet.

**Comment by seanlaw** [comment]
> Before the if check if T.shape[0] % m != 0:, we may add: n_windows = T.shape[0] // m and then we do for-loop using range(n_windows)

I accept your proposal. However, can we call it `n_contiguous_subseqs` ("contiguous" == "non-overlapping")?

**Comment by NimaSarajpoor** [comment]
> > Before the if check if T.shape[0] % m != 0:, we may add: n_windows = T.shape[0] // m and then we do for-loop using range(n_windows)
> 
> I accept your proposal. However, can we call it `n_contiguous_windows` ("contiguous" == "non-overlapping")?

Sure. `n_contiguous_windows` is more informative. Will make changes and submit a PR.
