### ISSUE TITLE
Add Continuous Integration (CI)

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#9]
Currently, there is no continuous integration for pull requests and everything is performed manually. Sadly, I have no experience here and would appreciate some help and/guidance.

- [ ] Use Azure Pipelines
- [ ] flake8
- [ ] mention code style requirement in CONTRIBUTING.md
- [ ] run unit tests (Dask is an additional dependency)
- [ ] run coverage tests (Dask is an additional dependency)
- [ ] Add CI badge(s) to README.rst (builds passing, test coverage, etc)

**Comment by cuichenli** [comment]
Hi, I may be able to help on this issue, can I jump in and work on it?

**Comment by seanlaw** [comment]
@cuichenli I appreciate and welcome your help and contribution. Let me know if you need anything from me

**Comment by cuichenli** [comment]
I was trying to create one `stumpy` organization in Azure Pipeline but turns out it already existed. May I know did you create such an organization?

**Comment by seanlaw** [comment]
No I did not create the `stumpy` org but maybe we can create a `stumpy_dev` org and make me the owner if possible?

**Comment by cuichenli** [comment]
Just created, may I know your email address?

**Comment by cuichenli** [comment]
Currently, the [pipeline](https://dev.azure.com/stumpy-dev/stumpy/_build?definitionId=1) has been set up. One potential issue is the pipeline currently only connect to the [forked repo](https://github.com/cuichenli/stumpy/tree/azure-pipelines) instead of yours. Once merged to master we may still need some additional efforts to make the pipeline points to yours. 

Another thing is I now sure what kind of `code style requirement` would you like?

**Comment by seanlaw** [comment]
Please use seanmylaw@gmail.com

Can we use [black](http://black.readthedocs.io/en/stable/) for formatting and [flake8](http://flake8.pycqa.org/en/latest/) for linting. 

Do you know if we can test on multiple operating systems?

**Comment by cuichenli** [comment]
Sure we can use black for formatting and flake8 for linting. Although there would still be some lint error after formatting. 
Yes, we can test on multiple operating systems. Which ones would you like to test?

**Comment by seanlaw** [comment]
If it’s okay with you then I can try to find some time today to make the code pass flake8 and black. Once done, I’ll commit master and you can pull it to your fork. Would that work?

For OSes, can we follow [conda-forge](https://github.com/conda-forge/staged-recipes/pull/8369/checks) and do:

Linux 64
OSX 64
Win 64

**Comment by cuichenli** [comment]
No problem. I can also raise a pull request first so the pipeline can start to work.

**Comment by seanlaw** [comment]
I just pushed a new [commit](https://github.com/TDAmeritrade/stumpy/commit/8ae2757430351917fb11ccc389f2b54396e5df8b) where I've:

1. Added a `.flake8` file with some rules to ignore, increased max-length to match `black`, and exclude the `tests` directory
2. Ran `black` on all files
3. Ran `flake8` on all files
4. Executed test suite and coverage testing and all pass. 

We should be a clean state.

@cuichenli Can you synchronize your forked version with this please? Then you should be ready to go. Let me know if I've missed anything
