### ISSUE TITLE
Problem importing stumpy

### ISSUE THREAD

**Issue by yeongnamtan** [TDAmeritrade/stumpy#925]
I am just starting to test out stumpy but faced a problem importing it.

I am using sagemaker studio instance.

i did a pip install for stumpy and keep getting below error when I do an 'import stumpy'.

I had uninstall and reinstall numba == 0.55.2 many times but the same error persists.

---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 import stumpy

File /opt/conda/lib/python3.10/site-packages/stumpy/__init__.py:185
    182             gpu_aamp_stimp.__doc__ = ast.get_docstring(cd)
    184 try:
--> 185     _dist = get_distribution("stumpy")
    186     # Normalize case for Windows systems
    187     dist_loc = os.path.normcase(_dist.location)

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:528, in get_distribution(dist)
    526     dist = Requirement.parse(dist)
    527 if isinstance(dist, Requirement):
--> 528     dist = get_provider(dist)
    529 if not isinstance(dist, Distribution):
    530     raise TypeError("Expected string, Requirement, or Distribution", dist)

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:400, in get_provider(moduleOrReq)
    398 """Return an IResourceProvider for the named module or requirement"""
    399 if isinstance(moduleOrReq, Requirement):
--> 400     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    401 try:
    402     module = sys.modules[moduleOrReq]

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:968, in WorkingSet.require(self, *requirements)
    959 def require(self, *requirements):
    960     """Ensure that distributions matching `requirements` are activated
    961 
    962     `requirements` must be a string or a (possibly-nested) sequence
   (...)
    966     included, even if they were already activated in this working set.
    967     """
--> 968     needed = self.resolve(parse_requirements(requirements))
    970     for dist in needed:
    971         self.add(dist)

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:829, in WorkingSet.resolve(self, requirements, env, installer, replace_conflicting, extras)
    826 if not req_extras.markers_pass(req, extras):
    827     continue
--> 829 dist = self._resolve_dist(
    830     req, best, replace_conflicting, env, installer, required_by, to_activate
    831 )
    833 # push the new requirements onto the stack
    834 new_requirements = dist.requires(req.extras)[::-1]

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:875, in WorkingSet._resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
    872 if dist not in req:
    873     # Oops, the "best" so far conflicts with a dependency
    874     dependent_req = required_by[req]
--> 875     raise VersionConflict(dist, req).with_context(dependent_req)
    876 return dist

ContextualVersionConflict: (numba 0.55.1 (/opt/conda/lib/python3.10/site-packages), Requirement.parse('numba>=0.55.2'), {'stumpy'})

**Comment by seanlaw** [comment]
@yeongnamtan Thank you for your question and welcome to the STUMPY community. I have no experience with Sagemaker but it appears that you were unsuccessful in installing the correct version of `numba`. The minimum version required is `0.55.2` and according to your last error line:

```
ContextualVersionConflict: (numba 0.55.1 (/opt/conda/lib/python3.10/site-packages), Requirement.parse('numba>=0.55.2'), {'stumpy'})
```

You only have version `0.55.1` installed. I'm guessing that if you correct this then you should be good to go. Version `0.55.2`  is the minimum required version but it is quite outdated and so I recommend installing the latest version of `numba` if you can.

**Comment by yeongnamtan** [comment]
Thanks @seanlaw.
When I install stumpy, it gives me 0.58.0 but I can't import stumpy with sagemaker studio.

I did a force install to 0.55.2 but it still doesn't work.

I think issue is with sagemaker.

I tried on Google Collab and it works perfectly the first time.

So I am sticking to Collab for now.

**Comment by seanlaw** [comment]
@yeongnamtan Please feel free to re-open this issue or start a new one if you have anything further to add

**Comment by seanlaw** [comment]
Indeed, the simplicity of matrix profiles makes it hard to hide the reality.

We spend most of our time maintaining the code base/adding new features/improving docs/performance and so we have not spent any time on collecting case studies as providing/curating them would certainly elicit even more questions than we have time to support. However, I recommend checking out all of the papers that are published by the original researchers:

https://www.cs.ucr.edu/~eamonn/MatrixProfile.html

Buried within them are numerous case studies.

**Comment by yeongnamtan** [comment]
Thank you @seanlaw
