### ISSUE TITLE
Request: stumpi equivalent for multivariate case

### ISSUE THREAD

**Issue by theconnectionist** [TDAmeritrade/stumpy#926]
Is there a stumpi equivalent for use with multiple variables (multiple timeseries) so I can incrementally add a new record? I read the article on using stumpi (much appreciated). When I initially asked chatGPT about incrementally updating a multivariate matrix profile in stumpy, it helpfully suggested "mstumpi". Looking at the documentation, it appears ChatGPT had a hallucination and sent me searching for that function :-)

Right now it appears the only way to do it is to batch a few streaming events and recompute the matrix in its entirety, perhaps using mstumped to benefit from distributed computing.

**Comment by seanlaw** [comment]
Unfortunately, there is no `mstumpi` equivalent as, fundamentally, multi-dimensional matrix profiles have a different/specific definition that is different from simply stacking individual matrix profiles one on top of the other. The interpretation of a multi-dimensional matrix profile is not so obvious. See a past `mstumpi` discussion [here](https://github.com/TDAmeritrade/stumpy/discussions/470#discussioncomment-1447716).

Are you really looking for a multi-dimensional matrix profile (i.e., the same as the one that is produced by `mstump`)?

**Comment by theconnectionist** [comment]
@seanlaw, I read through and played with mstumped to generate and visualize multi-dimensional timeseries. I understand the limitation you mentioned, but taking time to let that "multiple dimensions are not multiple single dimensions stacked together" sink in. I'll read what you pointed me to.

**Comment by seanlaw** [comment]
@theconnectionist In case you missed it, I strongly recommend reading through [this tutorial for multi-dimensional matrix profiles](https://stumpy.readthedocs.io/en/latest/Tutorial_Multidimensional_Motif_Discovery.html) as it goes through the (originally published) concept in detail.
