### ISSUE TITLE
Check for "dimensioanl" and other overlooked typos

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#95]
There are some typos in the docstrings where "dimensional" is mis-spelled as "dimensioanl". We need to check if any other ones exist.

**Comment by cydave** [comment]
A quick grep shows no more such issues. But please verify :+1:

**Comment by cydave** [comment]
But, the word  `default` is misspelled as `defailt`.

https://github.com/TDAmeritrade/stumpy/blob/13920571cc1591c05e9d4ff0943f1c5f8bb0c241/stumpy/gpu_stump.py#L378

**Comment by seanlaw** [comment]
@cydave I updated the title to this issue 😊
