### ISSUE TITLE
Update Code to work with NumPy 2.0

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#989]
Changes in `NumPy 2.0` resulted in error when running test suite in STUMPY.  

**Example:**
According to the [raised error](https://github.com/TDAmeritrade/stumpy/actions/runs/9547228532/job/26311804730?pr=983), `np.NINF` should be replaced with `-np.inf`. The exact error message is as follows:
```
AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.
```

The code needs to be updated accordingly.

**Comment by seanlaw** [comment]
@NimaSarajpoor It looks like the change is sufficient to be compatible with NumPy 2.0 and all tests are passing.  I am having some trouble getting things to install properly on my Apple M2 (well, things seem to install via `conda`/`mamba` but I'm getting some weird errors and only installing via `pip` resolves the issues). I will work on it but maybe it's just a matter of `conda`/`mamba` catching up to the `numpy` 2.0 changes

**Comment by seanlaw** [comment]
Alright, everything looks resolved now and we are now `numpy` 2.0 compatible

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Thanks for taking care of it so quickly.

**Comment by seanlaw** [comment]
I still need to do a bit more testing to be sure
