### ISSUE TITLE
Numba JIT decorator is missing in `stumpy/maamp.py:: _maamp` and `stumpy/mstump.py::_mstump`

### ISSUE THREAD

**Issue by NimaSarajpoor** [TDAmeritrade/stumpy#999]
The NJIT decorator is missing for the functions `_maamp` (in `stumpy/maamp.py`) and `_mstump`(in `stumpy/mstump.py`)

**Comment by seanlaw** [comment]
Actually, this is not needed. Both `_maamp` and `_mstump` do not need to be njit-ed as it is the inner function, `_compute_multi_D` that is `njit`-ed

**Comment by NimaSarajpoor** [comment]
Going to close this issue and its corresponding PR #1000.
